


1. set pages  or pagesize  ? this parameter determines how many lines SQL*Plus will print to the screen before starting a new page and reprinting the column headings.  To turn off column headings, set pages to zero.  To have the column headings appear only once, set pages very high (pages 999). pages defaults to 14.

2. set line or linesize - determines how long a line is.  It defaults to 80 characters.

3. set feed/feedback on/off ? This is the comment at the end of your listing that tells you how many rows were returned.  If you turn feedback off, and you query returns no rows, you will simply return to the SQL prompt.

4. set timing on - The most important SQL*plus set command, it times the response time for SQL and PL/SQL, used for tuning.

5. set verify off/on:  This enables/disables the feedback for substitution characters (with ampersands)

6. set trims or trimspool - normally SQL*Plus will fill out a column with blank spaces.  trimspool causes SQL*Plus to not fill spaces at the end of a line when spooling the results.

7. SET AUTOT[RACE] {ON | OFF | TRACE[ONLY]} [EXP[LAIN]] [STAT[ISTICS]] :: Displays a report on the execution of successful SQL DML statements (SELECT, INSERT, UPDATE, DELETE or MERGE).

{
SET AUTOTRACE OFF ::	No AUTOTRACE report is generated. This is the default.
SET AUTOTRACE ON :: EXPLAIN	The AUTOTRACE report shows only the optimizer execution path.
SET AUTOTRACE ON :: STATISTICS	The AUTOTRACE report shows only the SQL statement execution statistics.
SET AUTOTRACE ON  ::	The AUTOTRACE report includes both the optimizer execution path and the SQL statement execution statistics.
SET AUTOTRACE TRACEONLY	:: Like SET AUTOTRACE ON, but suppresses the printing of the users query output, if any. If STATISTICS is enabled, query data is still fetched, but not printed.
}

8. SET ECHO {ON | OFF} :: Controls whether the START command lists each command in a script as the command is executed.

9. SET COLSEP { | text} :: Sets the text to be printed between selected columns.
  ex.
CHDRNUM |ZENDCDE             |STATCODE|
--------|--------------------|--------|
06449930|UCS                 |IF      |

10.SET ERRORL[OGGING] {ON | OFF} [TABLE [schema.]tablename] [TRUNCATE] [IDENTIFIER identifier] :: Enables recording of SQL, PL/SQL and SQL*Plus errors to an error log table which you can query later.
We can check error later by below sql statement
SELECT * FROM SPERRORLOG;
VM1DTA	24-03-22 6:22:31.000000000 PM			"ORA-00942: table or view does not exist"	"SELECT * FROM GARBAGE"

11. SET HEA[DING] {ON | OFF} :: Controls printing of column headings in reports/spool files.

12.SET NULL text :: Sets the text that represents a null value in the result of a SQL SELECT command.
ex. SET NULL 'NULL'
result:
If value is null then it will show as null
|           |        |
|ZPCPNCDE   |ZCONVPOL|
|-----------|--------|
|NULL       |NULL    |


13.SET SERVEROUT[PUT] {ON | OFF} [SIZE {n | UNL[IMITED]}] [FOR[MAT] {WRA[PPED] | WOR[D_WRAPPED] | TRU[NCATED]}]

Controls whether to display the output (that is, DBMS_OUTPUT PUT_LINE) of stored procedures or PL/SQL blocks in SQL*Plus.



14.SET TERM[OUT] {ON | OFF}

Controls the display of output generated by commands executed from a script.
Controls the display of output generated by commands in a script that is executed with @, @@ or START. OFF suppresses the display so that you can spool output to a file without displaying the output on screen. ON displays the output on screen. TERMOUT OFF does not affect output from commands you enter interactively or redirect to SQL*Plus from the operating system.

15. SET TRIM[OUT] {ON | OFF}
Determines whether SQL*Plus puts trailing blanks at the end of each displayed line. ON removes blanks at the end of each line, improving performance especially when you access SQL*Plus from a slow communications device. OFF enables SQL*Plus to display trailing blanks. TRIMOUT ON does not affect spooled output.


16. PROMPT ::Sends the specified message to the users screen. 
--======================================================SHOW COMMAND=================================================================
1. SHOW ALL :: Represents any system variable set by the SET command.
ex. echo ON
errorlogging is ON TABLE SPERRORLOG
escape OFF

2.SHOW PARAMETERS 
PARAMETERS [parameter_name]
Displays the current values for one or more initialization parameters. You can use a string after the command to see a subset of parameters whose names include that string. For example, if you enter:

3.SELECT * FROM USER_RECYCLEBIN;
Shows objects in the recycle bin that can be reverted with the FLASHBACK BEFORE DROP command. You do not need to remember column names, or interpret the less readable output from the query:

---============================================================ORACLE SLQPLUS All Commands with short desc==========================================================

 