--------------------------------------------------------------------------------------------------------
--DATA MIGRATION SCRIPT FOR SQL LOADER TO LOAD DATA INTO SATGE 1 TABLE FROM CSV FILE
--CODE DEVELOPED BY JD
--DATE 26 DEC 2017
--VERSION 0.1
--THIS IS THE SQL LOADER CONTROL FILE
--THE FOLLOWING SCRIPT LOADS THE DATA INTO TITDMGAGENTPJ TABLE FROM CSV FILE
--------------------------------------------------------------------------------------------------------
LOAD DATA
CHARACTERSET JA16SJIS
APPEND INTO TABLE TITDMGAGENTPJ
FIELDS TERMINATED BY ","
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
ZAREFNUM "NVL(TRIM(:ZAREFNUM ),' ')",
AGTYPE "NVL(TRIM(:AGTYPE ),' ')",
AGNTBR "NVL(TRIM(:AGNTBR ),' ')",
SRDATE "NVL(TRIM(:SRDATE ),0)",
DATEEND "TRIM(:DATEEND )",
STCA "TRIM(:STCA )",
RIDESC "NVL(TRIM(:RIDESC ),' ')",
AGCLSD "NVL(TRIM(:AGCLSD ),' ')",
ZREPSTNM "NVL(TRIM(:ZREPSTNM ),' ')",
ZAGREGNO "TRIM(:ZAGREGNO )",
CPYNAME "TRIM(:CPYNAME )",
ZTRGTFLG "TRIM(:ZTRGTFLG )",
COUNT "TRIM(:COUNT )",
DCONSIGNEN "TRIM(:DCONSIGNEN )",
ZCONSIDT "TRIM(:ZCONSIDT )",
ZINSTYP01 "NVL(TRIM(:ZINSTYP01 ),' ')",
CMRATE01 "NVL(TRIM(:CMRATE01 ),0)",
ZINSTYP02 "NVL(TRIM(:ZINSTYP02 ),' ')",
CMRATE02 "NVL(TRIM(:CMRATE02 ),0)",
ZINSTYP03 "NVL(TRIM(:ZINSTYP03 ),' ')",
CMRATE03 "NVL(TRIM(:CMRATE03 ),0)",
ZINSTYP04 "NVL(TRIM(:ZINSTYP04 ),' ')",
CMRATE04 "NVL(TRIM(:CMRATE04 ),0)",
ZINSTYP05 "NVL(TRIM(:ZINSTYP05 ),' ')",
CMRATE05 "NVL(TRIM(:CMRATE05 ),0)",
ZINSTYP06 "NVL(TRIM(:ZINSTYP06 ),' ')",
CMRATE06 "NVL(TRIM(:CMRATE06 ),0)",
ZINSTYP07 "NVL(TRIM(:ZINSTYP07 ),' ')",
CMRATE07 "NVL(TRIM(:CMRATE07 ),0)",
ZINSTYP08 "NVL(TRIM(:ZINSTYP08 ),' ')",
CMRATE08 "NVL(TRIM(:CMRATE08 ),0)",
ZINSTYP09 "NVL(TRIM(:ZINSTYP09 ),' ')",
CMRATE09 "NVL(TRIM(:CMRATE09 ),0)",
ZINSTYP10 "NVL(TRIM(:ZINSTYP10 ),' ')",
CMRATE10 "NVL(TRIM(:CMRATE10 ),0)",
CLNTNUM "NVL(TRIM(:CLNTNUM ),' ')",
ZDRAGNT "NVL(TRIM(:ZDRAGNT ),' ')"
)


