MERGE INTO MIOKPF A USING MIOKPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET		
		A.SURNAME=B.SURNAME,
        A.GIVNAME=B.GIVNAME,
        A.CLTADDR01=B.CLTADDR01,
        A.CLTADDR02=B.CLTADDR02,
        A.CLTADDR03=B.CLTADDR03,
        A.CLTADDR04=B.CLTADDR04,
        A.CLTPHONE01=B.CLTPHONE01,
        A.CLTPHONE02=B.CLTPHONE02,
        A.FAXNO=B.FAXNO,
        A.RINTERNET=B.RINTERNET,
        A.LSURNAME=B.LSURNAME,
        A.LGIVNAME=B.LGIVNAME,
        A.BANKACCKEY=B.BANKACCKEY,
        A.CLTADDR05=B.CLTADDR05;