MERGE INTO ZVCHPF A USING ZVCHPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET
                A.CLTPHONE01   = B.CLTPHONE01  ,
                A.CLTPHONE02   = B.CLTPHONE02  ,
                A.KANJINME  =    B.KANJINME   ,     
		A.CLTDOBJP   =      B.CLTDOBJP      ,
		A.KANJICLTADDR   =     B.KANJICLTADDR  ,
		A.BANKKEY       =   B.BANKKEY   ,  
		A.CLTPHONE01    =   B.CLTPHONE01   ,              
		A.KANANME  = B.KANANME ,
		A.MEMIDNUM  = B.MEMIDNUM ,
		A.CLTDOB = B.CLTDOB ,
		A.CLTPCODE = B.CLTPCODE ,
		A.ZENSPCD01 = B.ZENSPCD01 ,
		A.ZENSPCD02 = B.ZENSPCD02 ,
		A.ZCIFCODE = B.ZCIFCODE
;
