MERGE INTO AUDIT_CLNT A USING AUDIT_CLNT_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET					
		A.OLDSURNAME=B.OLDSURNAME,
        A.OLDGIVNAME=B.OLDGIVNAME,
        A.OLDCLTPHONE01=B.OLDCLTPHONE01,
        A.OLDCLTPHONE02=B.OLDCLTPHONE02,
        A.NEWSURNAME=B.NEWSURNAME,
        A.NEWGIVNAME=B.NEWGIVNAME,
        A.NEWCLTPHONE01=B.NEWCLTPHONE01,
        A.NEWCLTPHONE02=B.NEWCLTPHONE02;

		
        