MERGE INTO AUDIT_CLNTPF A USING AUDIT_CLNTPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET					
		A.OLDSURNAME=B.OLDSURNAME,
        A.OLDGIVNAME=B.OLDGIVNAME,
        A.OLDCLTPHONE01=B.OLDCLTPHONE01,
        A.OLDCLTPHONE02=B.OLDCLTPHONE02,
        A.OLDFAXNO=B.OLDFAXNO,       
        A.OLDLGIVNAME=B.OLDLGIVNAME,
        A.OLDKANJISURNAME=B.OLDKANJISURNAME,
        A.OLDKANJIGIVNAME=B.OLDKANJIGIVNAME,
        A.OLDKANJICLTADDR01=B.OLDKANJICLTADDR01,
        A.OLDKANJICLTADDR02=B.OLDKANJICLTADDR02,
        A.OLDKANJICLTADDR03=B.OLDKANJICLTADDR03,
        A.OLDKANJICLTADDR04=B.OLDKANJICLTADDR04,
        A.OLDKANJICLTADDR05=B.OLDKANJICLTADDR05,
        A.OLDZKANASNM=B.OLDZKANASNM,
        A.OLDZKANAGNM=B.OLDZKANAGNM,
        A.OLDZKANADDR01=B.OLDZKANADDR01,
        A.OLDZKANADDR02=B.OLDZKANADDR02,
        A.OLDZKANADDR03=B.OLDZKANADDR03,
        A.OLDZKANADDR04=B.OLDZKANADDR04,
        A.OLDZKANADDR05=B.OLDZKANADDR05,
        A.OLDZADDRCD=B.OLDZADDRCD,
        A.OLDZKANASNMNOR=B.OLDZKANASNMNOR,
        A.OLDZKANAGNMNOR=B.OLDZKANAGNMNOR,
        A.NEWSURNAME=B.NEWSURNAME,
        A.NEWGIVNAME=B.NEWGIVNAME,
        A.NEWCLTPHONE01=B.NEWCLTPHONE01,
        A.NEWCLTPHONE02=B.NEWCLTPHONE02,
        A.NEWFAXNO=B.NEWFAXNO,
        A.NEWLSURNAME=B.NEWLSURNAME,
        A.NEWLGIVNAME=B.NEWLGIVNAME,
        A.NEWKANJISURNAME=B.NEWKANJISURNAME,
        A.NEWKANJIGIVNAME=B.NEWKANJIGIVNAME,
        A.NEWKANJICLTADDR01=B.NEWKANJICLTADDR01,
        A.NEWKANJICLTADDR02=B.NEWKANJICLTADDR02,
        A.NEWKANJICLTADDR03=B.NEWKANJICLTADDR03,
        A.NEWKANJICLTADDR04=B.NEWKANJICLTADDR04,
        A.NEWKANJICLTADDR05=B.NEWKANJICLTADDR05,
        A.NEWZKANASNM=B.NEWZKANASNM,
        A.NEWZKANAGNM=B.NEWZKANAGNM,
        A.NEWZKANADDR01=B.NEWZKANADDR01,
        A.NEWZKANADDR02=B.NEWZKANADDR02,
        A.NEWZKANADDR03=B.NEWZKANADDR03,
        A.NEWZKANADDR04=B.NEWZKANADDR04,
        A.NEWZKANADDR05=B.NEWZKANADDR05,
        A.NEWZADDRCD=B.NEWZADDRCD,
        A.NEWZKANASNMNOR=B.NEWZKANASNMNOR,
        A.NEWZKANAGNMNOR=B.NEWZKANASNMNOR;

		

       


       
        
                               
