MERGE INTO BABRPF A USING BABRPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET					
		A.BANKACCKEY=B.BANKACCKEY,
        B.BANKACCDSC=B.BANKACCDSC,
		A.ZKANADDR01=B.ZKANADDR01,
        A.ZKANADDR02=B.ZKANADDR02,
        A.ZKANADDR03=B.ZKANADDR03,
        A.ZKANADDR04=B.ZKANADDR04;

       


       
        
                               
