MERGE INTO CLNTPF A USING CLNTPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET					
		A.SURNAME=B.SURNAME,
        A.GIVNAME=B.GIVNAME,
        A.CLTADDR01=B.CLTADDR01,
        A.CLTADDR02=B.CLTADDR02,
        A.CLTADDR03=B.CLTADDR03,
        A.CLTADDR04=B.CLTADDR04,
        A.CLTADDR05=B.CLTADDR05,
        A.CLTPHONE01=B.CLTPHONE01,
        A.CLTPHONE02=B.CLTPHONE02,
        A.FAXNO=B.FAXNO,
        A.LSURNAME=B.LSURNAME,
        A.LGIVNAME=B.LGIVNAME,
        A.KANJISURNAME=B.KANJISURNAME,
        A.ZKANASNM=B.ZKANASNM,
        A.ZKANAGNM=B.ZKANAGNM,
        A.ZKANADDR01=B.ZKANADDR01,
        A.ZKANADDR02=B.ZKANADDR02,
        A.ZKANADDR03=B.ZKANADDR03,
        A.ZKANADDR04=B.ZKANADDR04,
        A.ZKANADDR05=B.ZKANADDR05,
        A.ZADDRCD=B.ZADDRCD,
        A.ZKANASNMNOR=B.ZKANASNMNOR,
        A.ZKANAGNMNOR=B.ZKANAGNMNOR,
        A.ZWORKPLCE=B.ZWORKPLCE;

        

        
		
        