MERGE INTO ZALTPF A USING ZALTPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET					
		A.CRDTCARD=B.CRDTCARD,
        A.ZKANASNM=B.ZKANASNM,
        A.ZKANAGNM=B.ZKANAGNM,
        A.KANJISURNAME=KANJISURNAME,
        A.ZKANADDR01=B.ZKANADDR01,
        A.ZKANADDR02=B.ZKANADDR02,
        A.ZKANADDR03=B.ZKANADDR03,
        A.ZKANADDR04=B.ZKANADDR04,
        A.CLTPHONE01=B.CLTPHONE01,
        A.ZWORKPLCE1=B.ZWORKPLCE1,
        A.ZWORKPLCE2=B.ZWORKPLCE2;
        

        
		
        