CREATE TABLE "TITPAMMONTRF_EXT" 
(
        "RECIDXMONTRF" NUMBER(38,0), 
		"BANKACCKEY"   VARCHAR2(20 CHAR),
		"CBANKACKEY"   VARCHAR2(20 CHAR)
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'TITPAMMONTRF_EXT.bad'
    LOGFILE 'TITPAMMONTRF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
        "RECIDXMONTRF"   CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"BANKACCKEY"      CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"CBANKACKEY"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
    )
  )
  location 
  (
    'outputTITPAMMONTRF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table TITPAMMONTRF_EXT;

--select * from TITPAMMONTRF_EXT; 