MERGE INTO AUDIT_ASRDPF A USING AUDIT_ASRDPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET					
		A.OLDSURNAME=B.OLDSURNAME,
        A.OLDGIVNAME=B.OLDGIVNAME,
        A.NEWSURNAME=B.NEWSURNAME,
        A.NEWGIVNAME=B.NEWGIVNAME;

        
		
        