MERGE INTO ZMUPPF A USING ZMUPPF_EXT B
ON (A.UNIQUE_NUMBER = B.UNIQUE_NUMBER)
WHEN MATCHED THEN
    UPDATE SET		
		A.LSURNAME = B.LSURNAME,
		A.OWNERKANASURNAME=B.OWNERKANASURNAME;
                               
