select count(*) from CLBAPF_TEMP;
select count(*) from CLEXPF_TEMP;
select count(*) from GMHDPF_TEMP;
select count(*) from GMHIPF_TEMP;
select count(*) from ZALTPF_TEMP;
select count(*) from ZCLNPF_TEMP;
select count(*) from ZMCIPF_TEMP;
select count(*) from audit_clntpf_temp;--2166868
select count(*) from audit_clnt_temp;
select count(*) from audit_clexpf_temp;
select count(*) from clntpf_temp;

truncate table CLBAPF_TEMP;
truncate table CLEXPF_TEMP;
truncate table GMHDPF_TEMP;
truncate table GMHIPF_TEMP;
truncate table ZALTPF_TEMP;
truncate table ZCLNPF_TEMP;
truncate table ZMCIPF_TEMP;
truncate table audit_clntpf_temp;--2166868
truncate table audit_clnt_temp;
truncate table audit_clexpf_temp;
truncate table clntpf_temp;




select count(*)/24 from CLBAPF_TEMP;--28107.9583333333333333333333333333333333
select count(*)/24 from CLEXPF_TEMP;--41658.0416666666666666666666666666666667
select count(*)/24 from GMHDPF_TEMP;--41749.1666666666666666666666666666666667
select count(*)/24 from GMHIPF_TEMP;--41978.0416666666666666666666666666666667
select count(*)/24 from ZALTPF_TEMP;--57363.1666666666666666666666666666666667
select count(*)/24 from ZCLNPF_TEMP;--42367.0833333333333333333333333333333333
select count(*)/24 from ZMCIPF_TEMP;--54592.4166666666666666666666666666666667
select count(*)/24 from audit_clntpf_temp;--45143.0833333333333333333333333333333333
select count(*)/24 from audit_clnt_temp;--4317.125
select count(*)/24 from audit_clexpf_temp;--41855.0833333333333333333333333333333333
select count(*)/24 from clntpf_temp;--41665.875


------------Normal Vm1dta---
select count(1) from AUDIT_ASRDPF_EXT;
select count(1) from CLNTQY_EXT;
select count(1) from MIOKPF_EXT;
select count(1) from POLDATATEMP_EXT;
select count(1) from ZCORPF_EXT;
select count(1) from ZMIEPF_EXT;
select count(1) from ZMUPPF_EXT;
select count(1) from ZPDAPF_EXT;
select count(1) from ZREPPF_EXT;
select count(1) from ZSTGPF_EXT;
select count(1) from ZVCHPF_EXT;

select 
(select count(1) from AUDIT_ASRDPF_EXT) AS AUDIT_ASRDPF_EXT,
(select count(1) from CLNTQY_EXT) AS CLNTQY_EXT,
(select count(1) from MIOKPF_EXT) AS MIOKPF_EXT,
(select count(1) from ZCORPF_EXT) AS ZCORPF_EXT,
(select count(1) from ZMIEPF_EXT) AS ZMIEPF_EXT,
(select count(1) from ZMUPPF_EXT) AS ZMUPPF_EXT,
(select count(1) from ZPDAPF_EXT) AS ZPDAPF_EXT,
(select count(1) from ZREPPF_EXT) AS ZREPPF_EXT,
(select count(1) from ZSTGPF_EXT) AS ZSTGPF_EXT,
(select count(1) from ZVCHPF_EXT) AS ZVCHPF_EXT
(select count(1) from ZREPPF_EXT) AS ZREPPF_EXT
from dual;



------stage--------
select count(1) from TITPAMMONTRF_EXT;
select count(1) from TITPAMCAMPAIGN_EXT;

-------------Verifactoin of masking-----------
---Vm1dta  normal---
select A.UNIQUE_NUMBER,A.NEWSURNAME,B.NEWSURNAME MASK_NEWSURNAME from AUDIT_ASRDPF_EXT A INNER JOIN AUDIT_ASRDPF B on A.UNIQUE_NUMBER = B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.SURNAME,B.SURNAME MASK_SURNAME from CLNTQY_EXT A INNER JOIN CLNTQY B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.SURNAME,B.SURNAME MASK_SURNAME from MIOKPF_EXT A INNER JOIN MIOKPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.chdrnum,A.ZKANAGNM,B.ZKANAGNM MASK_ZKANAGNM from POLDATATEMP_EXT A INNER JOIN POLDATATEMP  B ON A.CHDRNUM= B.CHDRNUM and A.TRANNO = B.TRANNO;
select A.UNIQUE_NUMBER,A.ZKANASNM,B.ZKANASNM MASK_ZKANASNM from ZCORPF_EXT A INNER JOIN ZCORPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.LSURNAME,B.LSURNAME MASK_LSURNAME from ZMIEPF_EXT A INNER JOIN ZMIEPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.LSURNAME,B.LSURNAME MASK_LSURNAME from ZMUPPF_EXT A INNER JOIN ZMUPPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.ZKANADDR01,B.ZKANADDR01 MASK_ZKANADDR01 from ZPDAPF_EXT A INNER JOIN ZPDAPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.BANKACCDSC,B.BANKACCDSC MASK_BANKACCDSC from ZREPPF_EXT A INNER JOIN ZREPPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.BANKACCKEY01,B.BANKACCKEY01 MASK_BANKACCKEY01 from ZSTGPF_EXT A INNER JOIN ZSTGPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER;
select A.UNIQUE_NUMBER,A.CLTPHONE01,B.CLTPHONE01 MASK_CLTPHONE01 from ZVCHPF_EXT A INNER JOIN ZVCHPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER where TRIM(A.CLTPHONE01) is not null ;
select A.UNIQUE_NUMBER,A.CLTPHONE01,B.CLTPHONE01 MASK_CLTPHONE01 from ZVCHPF_EXT A INNER JOIN ZVCHPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER where TRIM(A.CLTPHONE01) is not null ;


---stg----------
select A.RECIDXMONTRF,A.BANKACCKEY,B.BANKACCKEY MASK_BANKACCKEY from TITPAMMONTRF_EXT A INNER JOIN TITPAMMONTRF  B ON A.RECIDXMONTRF= B.RECIDXMONTRF ;
select A.RECIDXCAMP,A.SURNAMEKANA,B.SURNAMEKANA MASK_SURNAMEKANA from TITPAMCAMPAIGN_EXT A INNER JOIN TITPAMCAMPAIGN  B ON A.RECIDXCAMP= B.RECIDXCAMP ;

-----------parallel Vm1dta----

select A.UNIQUE_NUMBER,A.BANKACCDSC,B.BANKACCDSC MASK_BANKACCDSC from CLBAPF_TEMP A INNER JOIN CLBAPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.FAXNO,B.FAXNO MASK_FAXNO from CLEXPF_TEMP A INNER JOIN CLEXPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.BANKACCKEY,B.BANKACCKEY MASK_BANKACCKEY from GMHDPF_TEMP A INNER JOIN GMHDPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.ZWORKPLCE1,B.ZWORKPLCE1 MASK_ZWORKPLCE1 from GMHIPF_TEMP A INNER JOIN GMHIPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.CRDTCARD,B.CRDTCARD MASK_CRDTCARD from ZALTPF_TEMP A INNER JOIN ZALTPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.LSURNAME,B.LSURNAME MASK_LSURNAME from ZCLNPF_TEMP A INNER JOIN ZCLNPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.CRDTCARD,B.CRDTCARD MASK_CRDTCARD from ZMCIPF_TEMP A INNER JOIN ZMCIPF  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.NEWLSURNAME,B.NEWLSURNAME MASK_NEWLSURNAME from audit_clntpf_temp A INNER JOIN audit_clntpf  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.NEWFAXNO,B.NEWFAXNO MASK_NEWFAXNO from audit_clexpf_temp A INNER JOIN audit_clexpf  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;
select A.UNIQUE_NUMBER,A.CLTADDR01,B.CLTADDR01 MASK_CLTADDR01 from clntpf_temp A INNER JOIN clntpf  B ON A.UNIQUE_NUMBER= B.UNIQUE_NUMBER ;














