CREATE TABLE "IG_TITDMGPOLTRNH_EXT" 
(
        "RECIDXPHIST"	NUMBER(38,0),
        "CRDTCARD"	    CHAR(16 CHAR)        
   
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'IG_TITDMGPOLTRNH_EXT.bad'
    LOGFILE 'IG_TITDMGPOLTRNH_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
        "UNIQUE_NUMBER"      CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',		
		"CRDTCARD"	         CHAR(255)   TERMINATED BY "," ENCLOSED BY '"'
		
	)
  )
  location 
  (
    '/opt/ig/hitoku/user/output/outputIG_TITDMGPOLTRNH.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table IG_TITDMGPOLTRNH_EXT;

--select * from IG_TITDMGPOLTRNH_EXT;