CREATE TABLE "ZMIEPF_EXT" 
(
        "UNIQUE_NUMBER"       NUMBER(18,0), 
		"LSURNAME"            VARCHAR2(60 CHAR)
				
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZMIEPF_EXT.bad'
    LOGFILE 'ZMIEPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
        "UNIQUE_NUMBER"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"LSURNAME"        CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'				  
    )
  )
  location 
  (
    '/opt/ig/hitoku/user/output/outputZMIEPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZMIEPF_EXT;

--select * from ZMIEPF_EXT; 