CREATE TABLE "ZSTGPF_EXT" 
(
        "UNIQUE_NUMBER" NUMBER(18), 
		"CLTPHONE01"    VARCHAR2(16 CHAR),
		"CLTPHONE02"    VARCHAR2(16 CHAR),
        "KANJISURNAME"	VARCHAR2(60 CHAR),
        "LSURNAME"	    VARCHAR2(60 CHAR),
        "LGIVNAME"	    VARCHAR2(60 CHAR),
        "ZKANASNM"	    VARCHAR2(60 CHAR),
        "ZKANAGNM"	    VARCHAR2(60 CHAR),
        "CLTADDR01"	    VARCHAR2(50 CHAR),
        "CLTADDR02"	    VARCHAR2(50 CHAR),
        "CLTADDR03"	    VARCHAR2(50 CHAR),
        "CLTADDR04"	    VARCHAR2(50 CHAR),
        "ZKANADDR01"	VARCHAR2(60 CHAR),
        "ZKANADDR02"	VARCHAR2(60 CHAR),
        "ZKANADDR03"	VARCHAR2(60 CHAR),
        "ZKANADDR04"	VARCHAR2(60 CHAR),
        "CLTPHONE01"	VARCHAR2(16 CHAR),
        "ZIKANSNM"	    VARCHAR2(60 CHAR),
        "ZIKANGNM"	    VARCHAR2(60 CHAR),
        "ZIKJADR1"	    VARCHAR2(50 CHAR),
        "ZIKJADR2"	    VARCHAR2(50 CHAR),
        "ZIKJADR3"	    VARCHAR2(50 CHAR),
        "ZIKJADR4"	    VARCHAR2(50 CHAR),
        "ZIKAADR1"	    VARCHAR2(60 CHAR),
        "ZIKAADR2"	    VARCHAR2(60 CHAR),
        "ZIKAADR3"	    VARCHAR2(60 CHAR),
        "ZIKAADR4"	    VARCHAR2(60 CHAR),
        "CRDTCARD"	    VARCHAR2(20 CHAR),
        "BANKACCKEY01"	VARCHAR2(20 CHAR),
        "BANKACCKEY02"	VARCHAR2(20 CHAR),
        "BANKACCDSC01"	VARCHAR2(30 CHAR),
        "ZFINAMKJ"	    VARCHAR2(20 CHAR),
        "KANJIGIVNAME"	VARCHAR2(60 CHAR)
		
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZSTGPF_EXT.bad'
    LOGFILE 'ZSTGPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
        "UNIQUE_NUMBER"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"CLTPHONE01"       CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"CLTPHONE02"       CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"KANJISURNAME"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"LSURNAME"	       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"LGIVNAME"	       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"ZKANASNM"	       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"ZKANAGNM"	       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"CLTADDR01"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"CLTADDR02"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"CLTADDR03"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
        "CLTADDR04"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"ZKANADDR01"       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
	    "ZKANADDR02"       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
	    "ZKANADDR03"       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
	    "ZKANADDR04"       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
        "CLTPHONE01"       CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKANSNM"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKANGNM"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKJADR1"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKJADR2"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKJADR3"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKJADR4"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKAADR1"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKAADR2"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKAADR3"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZIKAADR4"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "CRDTCARD"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "BANKACCKEY01"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "BANKACCKEY02"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "BANKACCDSC01"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "ZFINAMKJ"        CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		 "KANJIGIVNAME"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"'
		 )
       )	 
		 
  location 
  (
    '/opt/ig/hitoku/user/output/outputZSTGPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZSTGPF_EXT;

--select * from ZSTGPF_EXT; 