SELECT COUNT(1) CNT_GCHD_GCHP_DFPOPF_SHOULD_0
FROM (
	WITH CHDR_TEMPPLATE AS (
		SELECT GCHD.CHDRCOY, GCHD.CHDRNUM,  GCHD.CNTTYPE, GCHP.ZPLANCLS, GCHD.MPLNUM, TRIM((GCHD.CNTTYPE || GCHP.ZPLANCLS)) TEM 
			,  ITEM.ITEMITEM
			, TRIM(SUBSTR(UTL_RAW.CAST_TO_VARCHAR2(ITEM.GENAREA ),9,8)) TEMPLAT
		FROM Jd1dta.CHDRPF GCHD
		INNER JOIN  Jd1dta.GCHPPF GCHP ON (  GCHD.CHDRNUM= GCHP.CHDRNUM AND GCHD.CHDRCOY= GCHP.CHDRCOY )
		LEFT OUTER JOIN ITEMPF ITEM ON (ITEMPFX = 'IT' AND ITEMCOY= '1' AND ITEMTABL= 'TQ9FK'  AND TRIM(ITEMITEM)=TRIM((GCHD.CNTTYPE || GCHP.ZPLANCLS)))
	)
	SELECT 
		GCHD.CHDRNUM, GCHD.CHDRCOY, GCHD.CNTTYPE, GCHP.ZPLANCLS, GCHD.MPLNUM, TEMPLT.TEMPLAT, DFPO.TEMPLATE
		 , GCHD.CNTCURR  ,  DFPO.CNTCURR, GCHD.BILLCURR  ,  DFPO.BILLCURR, GCHD.HRSKIND  ,  DFPO.HRSKIND, GCHD.GPRNLTYP  ,  DFPO.GPRNLTYP
		 , GCHD.GPRMNTHS  ,  DFPO.GPRMNTHS, GCHD.COYSRVAC  ,  DFPO.COYSRVAC, GCHD.MRKSRVAC  ,  DFPO.MRKSRVAC, GCHD.TAXFLAG  ,  DFPO.TAXFLAG, GCHD.AGEDEF  
		 ,  DFPO.AGEDEF, GCHD.PERSONCOV  ,  DFPO.PERSONCOV, GCHD.ENROLLTYP  ,  DFPO.ENROLLTYP, GCHD.SPLITSUBS  ,  DFPO.SPLITSUBS  , GCHD.RNLNOTTO  ,  DFPO.RNLNOTTO 
		 , GCHP.EXBRKNM  ,  DFPO.EXBRKNM, GCHP.EXUNDNM  ,  DFPO.EXUNDNM, GCHP.BRKSRVAC  ,  DFPO.BRKSRVAC, GCHP.REFNO  ,  DFPO.REFNO
		 , GCHP.MBRDATA  ,  DFPO.MBRDATA, GCHP.ADMNRULE  ,  DFPO.ADMNRULE, GCHP.DEFPLANDI  ,  DFPO.DEFPLANDI, GCHP.DEFCLMPYE  ,  DFPO.DEFCLMPYE
		 , GCHP.EMPGRP  ,  DFPO.EMPGRP, GCHP.INWINCTYP  ,  DFPO.INWINCTYP, GCHP.AREACOD  ,  DFPO.AREACOD, GCHP.INDUSTRY  ,  DFPO.INDUSTRY
		 , GCHP.MAJORMET  ,  DFPO.MAJORMET, GCHP.BULKIND  ,  DFPO.BULKIND, GCHP.PRODMIX  ,  DFPO.PRODMIX, GCHP.FEELVL  ,  DFPO.FEELVL
		 , GCHP.CTBEFFDT  ,  DFPO.CTBEFFDT, GCHP.EXBFML  ,  DFPO.EXBFML, GCHP.EXBLDAYS  ,  DFPO.EXBLDAYS, GCHP.CTBFML  ,  DFPO.CTBFML
		 , GCHP.CTBNDAYS  ,  DFPO.CTBNDAYS, GCHP.EFAIS  ,  DFPO.EFAIS, GCHP.EFADP  ,  DFPO.EFADP, GCHP.NOREM  ,  DFPO.NOREM
		 , GCHP.FSTRMFML  ,  DFPO.FSTRMFML, GCHP.FSTRMDAY  ,  DFPO.FSTRMDAY, GCHP.SNDRMFML  ,  DFPO.SNDRMFML
		 , GCHP.SNDRMDAY  ,  DFPO.SNDRMDAY, GCHP.TRDRMFML  ,  DFPO.TRDRMFML, GCHP.TRDRMDAY  ,  DFPO.TRDRMDAY, GCHP.MBRIDFLD  ,  DFPO.MBRIDFLD
		 , GCHP.CTBRULE  ,  DFPO.CTBRULE, GCHP.ACBLRULE  ,  DFPO.ACBLRULE, GCHP.FMCRULE  ,  DFPO.FMCRULE, GCHP.FEEWHO  ,  DFPO.FEEWHO
		 , GCHP.CALCMTHD  ,  DFPO.CALCMTHD, GCHP.AGEBASIS  ,  DFPO.AGEBASIS, GCHP.FCLLVL  ,  DFPO.FCLLVL, GCHP.PRMPYOPT  ,  DFPO.PRMPYOPT
		 , GCHP.PRMBRLVL  ,  DFPO.PRMBRLVL, GCHP.TOLRULE  ,  DFPO.TOLRULE, GCHP.SWCFLG  ,  DFPO.SWCFLG, GCHP.CERTINFM  ,  DFPO.CERTINFM
		 , GCHP.FMC2RULE  ,  DFPO.FMC2RULE, GCHP.LOYBNFLG  ,  DFPO.LOYBNFLG, GCHP.AUTORNW  ,  DFPO.AUTORNW, GCHP.GAPLPFX  ,  DFPO.GAPLPFX
		 , GCHP.NMLVAR  ,  DFPO.NMLVAR, GCHP.EXTFMLY  ,  DFPO.EXTFMLY
		
	FROM Jd1dta.CHDRPF GCHD
	LEFT OUTER JOIN Jd1dta.GCHPPF GCHP ON (  GCHD.CHDRNUM= GCHP.CHDRNUM AND GCHD.CHDRCOY= GCHP.CHDRCOY )
	LEFT OUTER JOIN CHDR_TEMPPLATE TEMPLT ON (GCHD.CHDRNUM = TEMPLT.CHDRNUM AND GCHD.CHDRCOY= TEMPLT.CHDRCOY )
	LEFT OUTER JOIN DFPOPF DFPO ON (trim(DFPO.TEMPLATE) =  trim(TEMPLT.TEMPLAT))
	WHERE 
			 (  (	GCHD.CNTCURR	  <> 	DFPO.CNTCURR	 )  OR   (	DFPO.CNTCURR  IS NULL	 ) )
		OR 	 (  (	GCHD.BILLCURR	  <> 	DFPO.BILLCURR	 )  OR   (	DFPO.BILLCURR  IS NULL	 ) )
		OR 	 (  (	GCHD.HRSKIND	  <> 	DFPO.HRSKIND	 )  OR   (	DFPO.HRSKIND  IS NULL	 ) )
		OR 	 (  (	GCHD.GPRNLTYP	  <> 	DFPO.GPRNLTYP	 )  OR   (	DFPO.GPRNLTYP  IS NULL	 ) )
		OR 	 (  (	GCHD.GPRMNTHS	  <> 	DFPO.GPRMNTHS	 )  OR   (	DFPO.GPRMNTHS  IS NULL	 ) )
		OR 	 (  (	GCHD.COYSRVAC	  <> 	DFPO.COYSRVAC	 )  OR   (	DFPO.COYSRVAC  IS NULL	 ) )
		OR 	 (  (	GCHD.MRKSRVAC	  <> 	DFPO.MRKSRVAC	 )  OR   (	DFPO.MRKSRVAC  IS NULL	 ) )
		OR 	 (  (	GCHD.TAXFLAG	  <> 	DFPO.TAXFLAG	 )  OR   (	DFPO.TAXFLAG  IS NULL	 ) )
		OR 	 (  (	GCHD.AGEDEF	  <> 	DFPO.AGEDEF	 )  OR   (	DFPO.AGEDEF  IS NULL	 ) )
		OR 	 (  (	GCHD.PERSONCOV	  <> 	DFPO.PERSONCOV	 )  OR   (	DFPO.PERSONCOV  IS NULL	 ) )
		OR 	 (  (	GCHD.ENROLLTYP	  <> 	DFPO.ENROLLTYP	 )  OR   (	DFPO.ENROLLTYP  IS NULL	 ) )
		OR 	 (  (	GCHD.SPLITSUBS	  <> 	DFPO.SPLITSUBS	 )  OR   (	DFPO.SPLITSUBS  IS NULL	 ) )
		OR 	 (  (	GCHD.RNLNOTTO	  <> 	DFPO.RNLNOTTO	 )  OR   (	DFPO.RNLNOTTO  IS NULL	 ) )
		OR 	 (  (	GCHP.EXBRKNM	  <> 	DFPO.EXBRKNM	 )  OR   (	DFPO.EXBRKNM  IS NULL	 ) )
		OR 	 (  (	GCHP.EXUNDNM	  <> 	DFPO.EXUNDNM	 )  OR   (	DFPO.EXUNDNM  IS NULL	 ) )
		OR 	 (  (	GCHP.BRKSRVAC	  <> 	DFPO.BRKSRVAC	 )  OR   (	DFPO.BRKSRVAC  IS NULL	 ) )
		OR 	 (  (	GCHP.REFNO	  <> 	DFPO.REFNO	 )  OR   (	DFPO.REFNO  IS NULL	 ) )
		OR 	 (  (	GCHP.MBRDATA	  <> 	DFPO.MBRDATA	 )  OR   (	DFPO.MBRDATA  IS NULL	 ) )
		OR 	 (  (	GCHP.ADMNRULE	  <> 	DFPO.ADMNRULE	 )  OR   (	DFPO.ADMNRULE  IS NULL	 ) )
		OR 	 (  (	GCHP.DEFPLANDI	  <> 	DFPO.DEFPLANDI	 )  OR   (	DFPO.DEFPLANDI  IS NULL	 ) )
		OR 	 (  (	GCHP.DEFCLMPYE	  <> 	DFPO.DEFCLMPYE	 )  OR   (	DFPO.DEFCLMPYE  IS NULL	 ) )
		OR 	 (  (	GCHP.EMPGRP	  <> 	DFPO.EMPGRP	 )  OR   (	DFPO.EMPGRP  IS NULL	 ) )
		OR 	 (  (	GCHP.INWINCTYP	  <> 	DFPO.INWINCTYP	 )  OR   (	DFPO.INWINCTYP  IS NULL	 ) )
		OR 	 (  (	GCHP.AREACOD	  <> 	DFPO.AREACOD	 )  OR   (	DFPO.AREACOD  IS NULL	 ) )
		OR 	 (  (	GCHP.INDUSTRY	  <> 	DFPO.INDUSTRY	 )  OR   (	DFPO.INDUSTRY  IS NULL	 ) )
		OR 	 (  (	GCHP.MAJORMET	  <> 	DFPO.MAJORMET	 )  OR   (	DFPO.MAJORMET  IS NULL	 ) )
		OR 	 (  (	GCHP.BULKIND	  <> 	DFPO.BULKIND	 )  OR   (	DFPO.BULKIND  IS NULL	 ) )
		OR 	 (  (	GCHP.PRODMIX	  <> 	DFPO.PRODMIX	 )  OR   (	DFPO.PRODMIX  IS NULL	 ) )
		OR 	 (  (	GCHP.FEELVL	  <> 	DFPO.FEELVL	 )  OR   (	DFPO.FEELVL  IS NULL	 ) )
		OR 	 (  (	GCHP.CTBEFFDT	  <> 	DFPO.CTBEFFDT	 )  OR   (	DFPO.CTBEFFDT  IS NULL	 ) )
		OR 	 (  (	GCHP.EXBFML	  <> 	DFPO.EXBFML	 )  OR   (	DFPO.EXBFML  IS NULL	 ) )
		OR 	 (  (	GCHP.EXBLDAYS	  <> 	DFPO.EXBLDAYS	 )  OR   (	DFPO.EXBLDAYS  IS NULL	 ) )
		OR 	 (  (	GCHP.CTBFML	  <> 	DFPO.CTBFML	 )  OR   (	DFPO.CTBFML  IS NULL	 ) )
		OR 	 (  (	GCHP.CTBNDAYS	  <> 	DFPO.CTBNDAYS	 )  OR   (	DFPO.CTBNDAYS  IS NULL	 ) )
		OR 	 (  (	GCHP.EFAIS	  <> 	DFPO.EFAIS	 )  OR   (	DFPO.EFAIS  IS NULL	 ) )
		OR 	 (  (	GCHP.EFADP	  <> 	DFPO.EFADP	 )  OR   (	DFPO.EFADP  IS NULL	 ) )
		OR 	 (  (	GCHP.NOREM	  <> 	DFPO.NOREM	 )  OR   (	DFPO.NOREM  IS NULL	 ) )
		OR 	 (  (	GCHP.FSTRMFML	  <> 	DFPO.FSTRMFML	 )  OR   (	DFPO.FSTRMFML  IS NULL	 ) )
		OR 	 (  (	GCHP.FSTRMDAY	  <> 	DFPO.FSTRMDAY	 )  OR   (	DFPO.FSTRMDAY  IS NULL	 ) )
		OR 	 (  (	GCHP.SNDRMFML	  <> 	DFPO.SNDRMFML	 )  OR   (	DFPO.SNDRMFML  IS NULL	 ) )
		OR 	 (  (	GCHP.SNDRMDAY	  <> 	DFPO.SNDRMDAY	 )  OR   (	DFPO.SNDRMDAY  IS NULL	 ) )
		OR 	 (  (	GCHP.TRDRMFML	  <> 	DFPO.TRDRMFML	 )  OR   (	DFPO.TRDRMFML  IS NULL	 ) )
		OR 	 (  (	GCHP.TRDRMDAY	  <> 	DFPO.TRDRMDAY	 )  OR   (	DFPO.TRDRMDAY  IS NULL	 ) )
		OR 	 (  (	GCHP.MBRIDFLD	  <> 	DFPO.MBRIDFLD	 )  OR   (	DFPO.MBRIDFLD  IS NULL	 ) )
		OR 	 (  (	GCHP.CTBRULE	  <> 	DFPO.CTBRULE	 )  OR   (	DFPO.CTBRULE  IS NULL	 ) )
		OR 	 (  (	GCHP.ACBLRULE	  <> 	DFPO.ACBLRULE	 )  OR   (	DFPO.ACBLRULE  IS NULL	 ) )
		OR 	 (  (	GCHP.FMCRULE	  <> 	DFPO.FMCRULE	 )  OR   (	DFPO.FMCRULE  IS NULL	 ) )
		OR 	 (  (	GCHP.FEEWHO	  <> 	DFPO.FEEWHO	 )  OR   (	DFPO.FEEWHO  IS NULL	 ) )
		OR 	 (  (	GCHP.CALCMTHD	  <> 	DFPO.CALCMTHD	 )  OR   (	DFPO.CALCMTHD  IS NULL	 ) )
		OR 	 (  (	GCHP.AGEBASIS	  <> 	DFPO.AGEBASIS	 )  OR   (	DFPO.AGEBASIS  IS NULL	 ) )
		OR 	 (  (	GCHP.FCLLVL	  <> 	DFPO.FCLLVL	 )  OR   (	DFPO.FCLLVL  IS NULL	 ) )
		OR 	 (  (	GCHP.PRMPYOPT	  <> 	DFPO.PRMPYOPT	 )  OR   (	DFPO.PRMPYOPT  IS NULL	 ) )
		OR 	 (  (	GCHP.PRMBRLVL	  <> 	DFPO.PRMBRLVL	 )  OR   (	DFPO.PRMBRLVL  IS NULL	 ) )
		OR 	 (  (	GCHP.TOLRULE	  <> 	DFPO.TOLRULE	 )  OR   (	DFPO.TOLRULE  IS NULL	 ) )
		OR 	 (  (	GCHP.SWCFLG	  <> 	DFPO.SWCFLG	 )  OR   (	DFPO.SWCFLG  IS NULL	 ) )
		OR 	 (  (	GCHP.CERTINFM	  <> 	DFPO.CERTINFM	 )  OR   (	DFPO.CERTINFM  IS NULL	 ) )
		OR 	 (  (	GCHP.FMC2RULE	  <> 	DFPO.FMC2RULE	 )  OR   (	DFPO.FMC2RULE  IS NULL	 ) )
		OR 	 (  (	GCHP.LOYBNFLG	  <> 	DFPO.LOYBNFLG	 )  OR   (	DFPO.LOYBNFLG  IS NULL	 ) )
		OR 	 (  (	GCHP.AUTORNW	  <> 	DFPO.AUTORNW	 )  OR   (	DFPO.AUTORNW  IS NULL	 ) )
		OR 	 (  (	GCHP.GAPLPFX	  <> 	DFPO.GAPLPFX	 )  OR   (	DFPO.GAPLPFX  IS NULL	 ) )
		OR 	 (  (	GCHP.NMLVAR	  <> 	DFPO.NMLVAR	 )  OR   (	DFPO.NMLVAR  IS NULL	 ) )
		OR 	 (  (	GCHP.EXTFMLY	  <> 	DFPO.EXTFMLY	 )  OR   (	DFPO.EXTFMLY  IS NULL	 ) )

	-- OR 	 (  (	GCHP.LMBRPFX	  <> 	DFPO.LMBRPFX	 )  OR   (	DFPO.LMBRPFX  IS NULL	 ) )

) TBL
;

-- ============================== 02_SRC_GCHD_GCHP_GCHI.sql ==============================================================
-----------------------------------------------------------------
WITH SRC_GCHD_GCHP_GCHI AS (
SELECT REFNUM, SUBSTR(TRIM(REFNUM),1,8) CHDRNUM
	, MBRNO
  , TRIM(CNTTYPIND) CNTTYPIND
  , CASE WHEN (TRIM(CNTTYPIND) = 'I') THEN ' '   ELSE MPOLNUM END  MPLNUM
  , TRIM(STATCODE) STATCODE
  , CASE WHEN (TRIM(STATCODE) = 'PN') THEN EFFDATE   ELSE TO_NUMBER('99999999') END AS PNDATE
  , CASE WHEN (TRIM(STATCODE) = 'CA') THEN DTETRM   ELSE TO_NUMBER('99999999') END  AS EFFDCLDT
  , CASE WHEN (TRIM(STATCODE) = 'PN') THEN 'T902'   ELSE ' ' END AS PNTRCDE
  , CASE WHEN (TRIM(TREFNUM) IS NOT NULL ) THEN P1.TREFNUM   ELSE NULL END AS ZPRVCHDR
  , TO_NUMBER(TO_CHAR(TO_DATE(P1.CRDATE, 'YYYYMMDD') - 1,  'YYYYMMDD')) AS ZPENDDT
  , CASE WHEN  (TRIM(ZPOLTDATE) IS NOT NULL ) THEN ZPOLTDATE  ELSE TO_NUMBER('99999999') END AS ZPOLTDATE
  , TO_NUMBER(TO_CHAR(TO_DATE(P1.CRDATE, 'YYYYMMDD') - 1,  'YYYYMMDD')) AS CRDATE
  , TO_NUMBER(TO_CHAR(TO_DATE(P1.CRDATE, 'YYYYMMDD') + 1,  'YYYYMMDD')) AS INSENDTE
  , PAZD.ZIGVALUE COWNNUM
  , TRIM(ZCMPCODE) ZCMPCODE
  , TRIM(ZPOLTDATE) ORG_ZPOLTDATE
  , TERMAGE 
  , ZRWNLAGE 
  , ZNBMNAGE


FROM STAGEDBUSR.TITDMGMBRINDP1@DMSTAGEDBLINK P1
LEFT OUTER JOIN Jd1dta.PAZDCLPF PAZD ON (TRIM(P1.CLIENTNO) = TRIM(PAZD.ZENTITY) )
WHERE P1.MBRNO IS NULL
-- AND TRIM(CNTTYPIND) <> 'I'
)

SELECT SRC.REFNUM, SRC.MBRNO, SRC.CNTTYPIND, SRC.ORG_ZPOLTDATE
, SRC.COWNNUM, 	GCHD.COWNNUM, SRC.STATCODE, 	GCHD.STATCODE
, SRC.MPLNUM, GCHD.MPLNUM , SRC.PNDATE, GCHD.PNDATE , SRC.EFFDCLDT, GCHD.EFFDCLDT
, SRC.PNTRCDE, GCHD.PNTRCDE , SRC.ZPRVCHDR, GCHD.ZPRVCHDR

, SRC.ZPENDDT, GCHP.ZPENDDT , GCHI.ZPENDDT

, SRC.CRDATE, GCHI.CRDATE, SRC.INSENDTE, GCHI.INSENDTE

, GCHP.ZPLANCLS
, SRC.TERMAGE, GCHD.TERMAGE  , SRC.ZRWNLAGE, GCHD.ZRWNLAGE , SRC.ZNBMNAGE, GCHP.ZNBMNAGE

, SRC.ZPOLTDATE , GCHP.ZPOLTDATE, (TO_NUMBER(TO_CHAR(TO_DATE(GCHI.CRDATE, 'YYYYMMDD') + 1,  'YYYYMMDD'))) GCHI_CRDATE_PLUS_1


FROM SRC_GCHD_GCHP_GCHI SRC
LEFT OUTER JOIN CHDRPF GCHD ON ( SRC.CHDRNUM = GCHD.CHDRNUM )
LEFT OUTER JOIN GCHPPF GCHP ON ( GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRNUM = GCHD.CHDRNUM  )
LEFT OUTER JOIN GCHIPF GCHI ON ( GCHI.CHDRNUM = GCHD.CHDRNUM AND GCHI.CHDRNUM = GCHD.CHDRNUM  )
 
WHERE 1=1
AND (
    (GCHD.CHDRNUM IS NULL ) -- GCHD.COWNNUM = NULL means Record is not present in IG
   OR (  (SRC.COWNNUM  <> GCHD.COWNNUM )  ) 
   OR ( (TRIM(SRC.STATCODE)  <> TRIM(GCHD.STATCODE) )   )
  OR ( (TRIM(SRC.MPLNUM)  <> TRIM(GCHD.MPLNUM) )   )
  OR (  TRIM(SRC.PNDATE) <> TRIM(GCHD.PNDATE) )
  OR (  TRIM(SRC.EFFDCLDT) <> TRIM(GCHD.EFFDCLDT) )
  OR (  TRIM(SRC.PNTRCDE) <> TRIM(GCHD.PNTRCDE) )
  OR (  TRIM(SRC.ZPRVCHDR) <> TRIM(GCHD.ZPRVCHDR) )
  OR (  TRIM(SRC.ZPENDDT) <> TRIM(GCHP.ZPENDDT) )
--  OR (  TRIM(SRC.ZPOLTDATE) <> TRIM(GCHP.ZPOLTDATE) )  -- error occured
  OR (  TRIM(SRC.CRDATE) <> TRIM(GCHI.CRDATE) )
--  OR (  TRIM(SRC.INSENDTE) <> TRIM(GCHI.INSENDTE) )  -- Error record
  OR (  TRIM(SRC.ZPENDDT) <> TRIM(GCHI.ZPENDDT) ) 
   OR (  (SRC.COWNNUM  <> GCHI.COWNNUM )  ) 
   
   OR ( GCHP.ZPLANCLS = 'PP' AND SRC.TERMAGE <> GCHD.TERMAGE  )
   OR ( GCHP.ZPLANCLS = 'FP' AND GCHD.TERMAGE <> '100' )
   OR ( GCHP.ZPLANCLS = 'PP' AND SRC.ZRWNLAGE <> GCHD.ZRWNLAGE  )
   OR ( GCHP.ZPLANCLS = 'FP' AND GCHD.ZRWNLAGE <>  '100' )
   OR ( GCHP.ZPLANCLS = 'PP' AND SRC.ZNBMNAGE <> GCHP.ZNBMNAGE  )
   OR ( GCHP.ZPLANCLS = 'FP' AND GCHP.ZNBMNAGE <>  '0' )
   
    OR ( GCHP.ZPLANCLS = 'PP' AND SRC.ZPOLTDATE <> GCHP.ZPOLTDATE  )
    OR ( GCHP.ZPLANCLS = 'FP' AND GCHP.ZPOLTDATE <> (TO_NUMBER(TO_CHAR(TO_DATE(GCHI.CRDATE, 'YYYYMMDD') + 1,  'YYYYMMDD')))  )


)

;

------------------------ GCHI_TIMECH01 -----------------------

WITH CHDR_TIMECH AS (
		SELECT GCHD.CHDRCOY, GCHD.CHDRNUM,  GCHD.CNTTYPE, GCHP.ZPLANCLS, GCHD.MPLNUM, TRIM((GCHD.CNTTYPE || GCHP.ZPLANCLS)) TEM 
			,  ITEM.ITEMITEM
			, TRIM(SUBSTR(UTL_RAW.CAST_TO_VARCHAR2(ITEM.GENAREA ),0,5)) TQ9GX_TIMECH01
      , TRIM(SUBSTR(UTL_RAW.CAST_TO_VARCHAR2(ITEM.GENAREA ),6,5)) TQ9GX_TIMECH02
      , TRIM(GCHI.TIMECH01) GCHI_TIMECH01
      , TRIM(GCHI.TIMECH02) GCHI_TIMECH02
		FROM Jd1dta.CHDRPF GCHD
		INNER JOIN  Jd1dta.GCHPPF GCHP ON (  GCHD.CHDRNUM= GCHP.CHDRNUM AND GCHD.CHDRCOY= GCHP.CHDRCOY )
    INNER JOIN  Jd1dta.GCHIPF GCHI ON (  GCHI.CHDRNUM= GCHP.CHDRNUM AND GCHI.CHDRCOY= GCHP.CHDRCOY )
		LEFT OUTER JOIN ITEMPF ITEM ON (ITEMPFX = 'IT' AND ITEMCOY= '1' AND ITEMTABL= 'TQ9GX'  AND TRIM(ITEMITEM)=TRIM((GCHD.CNTTYPE || 'T902')))
	)
SELECT * 
FROM CHDR_TIMECH
WHERE 1=1 AND
( 
    ( TRIM(TQ9GX_TIMECH01) <> TRIM(GCHI_TIMECH01) )
OR  ( TRIM(TQ9GX_TIMECH02) <> TRIM(GCHI_TIMECH02) )
)
;


----------------------- GCHD_BTDATENR ---------------------


WITH GCHD_BTDATENR AS (
SELECT GCHD.CHDRNUM, GCHD.CNTTYPE, GCHP.ZPLANCLS
, GCHI.CCDATE, GCHI.CRDATE, GCHI.BTDATENR
, TO_CHAR ( ADD_MONTHS(to_date(GCHI.CCDATE, 'YYYYMMDD'),1) , 'YYYYMMDD') CCDATE_PLUS_1
FROM  CHDRPF GCHD 
LEFT OUTER JOIN GCHPPF GCHP ON ( GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRNUM = GCHD.CHDRNUM  )
LEFT OUTER JOIN GCHIPF GCHI ON ( GCHI.CHDRNUM = GCHD.CHDRNUM AND GCHI.CHDRNUM = GCHD.CHDRNUM  )
WHERE 1= 1 AND GCHD.JOBNM= 'G1ZDMBRIND' 
)
SELECT 
* 
FROM GCHD_BTDATENR DTA
WHERE 1=1 AND 
(
  ( DTA.ZPLANCLS = 'FP' AND DTA.BTDATENR <> DTA.CRDATE )
  OR ( DTA.ZPLANCLS = 'PP' AND DTA.BTDATENR <> (CCDATE_PLUS_1) )

)

;

-----------------------  MPLNUM_DATA  -----------------------
WITH MPLNUM_DATA AS (
  SELECT GCHD.CHDRNUM, GCHD.MPLNUM, GCHD.CNTTYPE , GCHP.ZPLANCLS , GCHP.POLANV , GCHP.ZCOLMCLS
  FROM  CHDRPF GCHD 
  LEFT OUTER JOIN GCHPPF GCHP ON ( GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRNUM = GCHD.CHDRNUM  )
  WHERE GCHD.CHDRNUM =  GCHD.MPLNUM
),
GCHD_DATA AS (
  SELECT GCHD.CHDRNUM, GCHD.MPLNUM, GCHP.POLANV, GCHP.ZPLANCLS, GCHP.ZCOLMCLS
  FROM  CHDRPF GCHD 
  LEFT OUTER JOIN GCHPPF GCHP ON ( GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRNUM = GCHD.CHDRNUM  )
  WHERE GCHD.CHDRNUM  <>  GCHD.MPLNUM
  AND GCHD.JOBNM= 'G1ZDMBRIND' 
 -- AND 
)
SELECT GCHD_DATA.CHDRNUM, GCHD_DATA.MPLNUM MPLNUM, MPL_DATA.CNTTYPE MPLNUM_CNTTYPE
, MPL_DATA.POLANV MPLNUM_POLANV, GCHD_DATA.POLANV
,  MPL_DATA.ZPLANCLS MPLNUM_ZPLANCLS, GCHD_DATA.ZPLANCLS
,  MPL_DATA.ZCOLMCLS MPLNUM_ZCOLMCLS, GCHD_DATA.ZCOLMCLS
FROM GCHD_DATA
LEFT OUTER JOIN MPLNUM_DATA MPL_DATA ON (MPL_DATA.MPLNUM = GCHD_DATA.MPLNUM)
WHERE 1=1
AND 
(
   ( (TRIM(GCHD_DATA.MPLNUM) IS NOT NULL) AND  TRIM(GCHD_DATA.POLANV) <> TRIM(MPL_DATA.POLANV)  )  -- GROUP MEMBER - POLANV check
--  OR ( (TRIM(GCHD_DATA.MPLNUM) IS  NULL) AND  TRIM(GCHD_DATA.POLANV) IS NOT NULL ) -- INDIVIDUAL MEMBER - POLANV check       -- error

 OR ( (TRIM(GCHD_DATA.MPLNUM) IS NOT NULL) AND  TRIM(GCHD_DATA.ZPLANCLS) <> TRIM(MPL_DATA.ZPLANCLS)  )  -- GROUP MEMBER - ZPLANCLS check
  OR ( (TRIM(GCHD_DATA.MPLNUM) IS  NULL) AND  TRIM(GCHD_DATA.ZPLANCLS)  <> 'PP' ) -- INDIVIDUAL MEMBER - POLANV check
  
   OR ( (TRIM(GCHD_DATA.MPLNUM) IS NOT NULL) AND  TRIM(GCHD_DATA.ZCOLMCLS) <> TRIM(MPL_DATA.ZCOLMCLS)  )  -- GROUP MEMBER - ZCOLMCLS check

)
;

------------------------- GCHD_ZCMPCODE -----------
WITH GCHD_ZCMPCODE AS (
select GCHD.CHDRNUM, GCHI.ZAGPTNUM, TRIM(GCHI.ZCMPCODE) GCHI_ZCMPCODE
, TRIM(ZCPN.ZCMPCODE) ZCPN_ZCMPCODE
, TRIM(GCHP.PETNAME) GCHP_PETNAME, TRIM(ZCPN.ZPETNAME) ZCPN_ZPETNAME
, TRIM(GCHP.ZGPORIPCLS) GCHP_ZGPORIPCLS, TRIM(ZCPN.ZPOLCLS) ZCPN_ZPOLCLS 
FROM CHDRPF GCHD 
LEFT OUTER JOIN GCHPPF GCHP ON ( GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRCOY = GCHD.CHDRCOY  )
LEFT OUTER JOIN GCHIPF GCHI ON ( GCHI.CHDRNUM = GCHD.CHDRNUM AND GCHI.CHDRCOY = GCHD.CHDRCOY  )
LEFT OUTER JOIN ZCPNPF ZCPN ON ( TRIM(GCHI.ZCMPCODE) = TRIM(ZCPN.ZCMPCODE) )
WHERE GCHD.JOBNM= 'G1ZDMBRIND'
)
SELECT *
FROM GCHD_ZCMPCODE SRC
WHERE 1=1 AND
(   (SRC.GCHP_ZGPORIPCLS <> SRC.ZCPN_ZPOLCLS)
 OR (SRC.GCHP_PETNAME = SRC.ZCPN_ZPETNAME)
)
;



---------------------- SRC_TRANO  -------------


WITH SRC_TRANO AS ( 
  SELECT CHDRNUM, MAX(MX_TRANO) MX_TRANO 
  FROM (
  select CHDRNUM, max(TRANNO) MX_TRANO from GBIHPF group by CHDRNUM
  UNION ALL 
  select CHDRNUM, max(TRANNO) MX_TRANO from ZTRAPF group by CHDRNUM 
  ) T
  GROUP BY CHDRNUM
)
SELECT GCHD.CHDRNUM, GCHD.TRANLUSED, SRC_TRANO.MX_TRANO
FROM CHDRPF GCHD 
LEFT OUTER JOIN SRC_TRANO SRC_TRANO ON (SRC_TRANO.CHDRNUM = GCHD.CHDRNUM)
WHERE GCHD.JOBNM= 'G1ZDMBRIND' 
AND (GCHD.TRANLUSED <> SRC_TRANO.MX_TRANO)
;
 



---------------------- ENDR_HLDCONDITION   -------------

SELECT *
FROM (
SELECT GCHD.CHDRNUM, GCHP.ZENDCDE, GCHP.HLDCOUNT, GCHI.CCDATE, GCHI.CRDATE
, ZESD.ZCOVCMDT, ZESD.ZBKTRFDT
, GCHP.ZCOLMCLS
, (CASE WHEN ZESD.ZBKTRFDT < ZESD.ZCOVCMDT THEN '-1' ELSE '0' END) AS ENDR_HLDCONDITION
, ROW_NUMBER() OVER (PARTITION BY GCHD.CHDRNUM ORDER BY ZESD.ZCOVCMDT desc) RN
  FROM CHDRPF GCHD
  LEFT OUTER JOIN GCHPPF GCHP ON ( GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRCOY = GCHD.CHDRCOY  )
  LEFT OUTER JOIN GCHIPF GCHI ON ( GCHI.CHDRNUM = GCHD.CHDRNUM AND GCHI.CHDRCOY = GCHD.CHDRCOY  )
  LEFT OUTER JOIN ZENDRPF ZENDR ON (ZENDR.ZENDCDE =  GCHP.ZENDCDE)
  LEFT OUTER JOIN ZESDPF ZESD ON (ZESD.ZENDSCID = ZENDR.ZENDSCID AND ZESD.ZCOVCMDT <= GCHI.CCDATE) 
  WHERE GCHD.JOBNM= 'G1ZDMBRIND'
  
) t
WHERE RN=1
AND  ( 
      ( TRIM(t.ZCOLMCLS) = 'F'   AND HLDCOUNT <> 0  )
    OR ( TRIM(t.ZCOLMCLS) <> 'F'   AND HLDCOUNT <> ENDR_HLDCONDITION )    --- ERROR
  )
  
;

------------------- GCHP_ZGRPCLS_DATA ---------------------
WITH GCHP_ZGRPCLS_DATA AS (
  SELECT * FROM (
    SELECT GCHD.CHDRNUM, GCHD.MPLNUM , GCHI.CCDATE, GCHI.CRDATE
    , GCHP.ZCOLMCLS
    , ZTGM.ZGRPCLS ZTGM_ZGRPCLS
    , GCHP.ZGRPCLS GCHP_ZGRPCLS 
    , ROW_NUMBER() OVER (PARTITION BY GCHD.CHDRNUM ORDER BY ZTGM.EFFDATE desc) RN
      FROM CHDRPF GCHD
      LEFT OUTER JOIN GCHPPF GCHP ON ( GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRCOY = GCHD.CHDRCOY  )
      LEFT OUTER JOIN GCHIPF GCHI ON ( GCHI.CHDRNUM = GCHD.CHDRNUM AND GCHI.CHDRCOY = GCHD.CHDRCOY  )
      LEFT OUTER JOIN ZTGMPF ZTGM ON (ZTGM.CHDRNUM = GCHD.MPLNUM AND ZTGM.EFFDATE <= GCHI.CCDATE) 
      WHERE GCHD.JOBNM= 'G1ZDMBRIND'
    ) t
  WHERE RN=1
 ) 
 SELECT *
 FROM GCHP_ZGRPCLS_DATA
  WHERE ZTGM_ZGRPCLS <> GCHP_ZGRPCLS
;


-----------  GMHD_AGE_SRC ----------
WITH GMHD_AGE_SRC AS (
  SELECT GMHD.CHDRNUM, GMHD.CLNTNUM, GMHD.AGE
  , CLNT.CLNTNUM CLNT_CLNTNUM , CLNT.CLTDOB, GCHI.EFFDATE GCHI_EFFDATE
  , floor(months_between( to_date(TO_CHAR(GCHI.EFFDATE),'YYYYMMDD'), to_date(TO_CHAR(CLNT.CLTDOB),'YYYYMMDD')) /12) AS CALC_AGE
  FROM GMHDPF GMHD
  LEFT OUTER JOIN CLNTPF CLNT ON (CLNT.CLNTNUM = GMHD.CLNTNUM)
  LEFT OUTER JOIN GCHIPF GCHI ON (GCHI.CHDRNUM = GMHD.CHDRNUM AND GCHI.CHDRCOY = GMHD.CHDRCOY)
  WHERE GMHD.JOBNM = 'G1ZDMBRIND'
  ORDER BY GMHD.CHDRNUM, GCHI.EFFDATE
)
SELECT *
FROM GMHD_AGE_SRC 
WHERE AGE <> CALC_AGE
;


------------  SRC_AGNTNUM : GCHP.ZGPORIPCLS = 'G'-----------
SELECT * FROM (
  
  WITH SRC_GCHD AS (
  SELECT GCHD.CHDRNUM, GCHP.ZPLANCLS, GCHP.ZPRDCTG, GCHP.ZGPORIPCLS, GCHD.MPLNUM 
  , GCHI.EFFDATE , GCHI.CCDATE, GCHI.AGNTNUM
  FROM CHDRPF GCHD
  LEFT OUTER JOIN GCHPPF GCHP ON (GCHP.CHDRNUM = GCHD.CHDRNUM AND GCHP.CHDRCOY = GCHD.CHDRCOY ) 
  LEFT OUTER JOIN GCHIPF GCHI ON (GCHI.CHDRNUM = GCHD.CHDRNUM AND GCHI.CHDRCOY = GCHD.CHDRCOY ) 
  WHERE GCHD.JOBNM= 'G1ZDMBRIND'
  AND GCHP.ZGPORIPCLS = 'G'  -- 01131656 - 01030981 - 	20356   
  ),
  SCR_MASTER AS (
     SELECT GCHP.MPLNUM,  GCHI.AGNTNUM, GCHI.CCDATE, GCHI.CRDATE, GCHI.EFFDATE
     FROM CHDRPF GCHP
      LEFT OUTER JOIN GCHIPF GCHI ON (GCHI.CHDRNUM = GCHP.CHDRNUM AND GCHI.CHDRCOY = GCHP.CHDRCOY ) 
        WHERE GCHP.CHDRNUM = GCHP.MPLNUM
  )
  
  SELECT SRC.CHDRNUM, SRC.ZGPORIPCLS, SRC.MPLNUM , SRC.EFFDATE , SRC.CCDATE
       , SRC.AGNTNUM SRC_AGNTNUM , MST.AGNTNUM   MST_AGNTNUM  
       ,  MST.EFFDATE MST_EFFDATE
       , ROW_NUMBER() OVER (PARTITION BY SRC.CHDRNUM ORDER BY MST.EFFDATE DESC) RN
  FROM SRC_GCHD SRC
  LEFT OUTER JOIN SCR_MASTER MST ON (MST.MPLNUM = SRC.MPLNUM AND MST.EFFDATE <= SRC.CCDATE )
) DT
WHERE RN=1
 AND TRIM(DT.SRC_AGNTNUM) <> TRIM(DT.MST_AGNTNUM)
 -- AND DT.CHDRNUM = '01131656'
;


----------------------------------------------------------------------------------
-- ================================= 03_SRC_GMHD_GMHI.sql ===========================================================

WITH SRC_GMHD_GMHI AS (
SELECT REFNUM, SUBSTR(TRIM(REFNUM),1,8) CHDRNUM
  , MBRNO
  , CASE WHEN (TRIM(STATCODE) = 'CA' OR TRIM(STATCODE) = 'LA') THEN DTETRM   ELSE TO_NUMBER('99999999') END  AS DTETRM
  , CASE WHEN (TRIM(STATCODE) = 'PN') THEN EFFDATE   ELSE TO_NUMBER('99999999') END AS PNDATE  
  , (zcmpcode ||zcpnscde02 )  AS ZCPNSCDE    
  , TO_char (CASE WHEN (TRIM(STATCODE) = 'PN') THEN '0'  
        WHEN   (ISSDATE  IS NULL OR  ISSDATE = '99999999')  THEN TO_CHAR(p1.issdate)
    ELSE '0'  END)  AS NOTSFROM
  , PAZD.ZIGVALUE CLNTNUM

FROM STAGEDBUSR.TITDMGMBRINDP1@DMSTAGEDBLINK P1
LEFT OUTER JOIN Jd1dta.PAZDCLPF PAZD ON (TRIM(P1.CLIENTNO) = TRIM(PAZD.ZENTITY) )
WHERE P1.MBRNO IS NOT NULL
)

SELECT SRC.REFNUM, SRC.CHDRNUM, SRC.MBRNO, GMHD.CHDRNUM , GMHD.MBRNO 
,  SRC.CLNTNUM, GMHD.CLNTNUM , GMHD.CLIENT
, SRC.DTETRM, GMHD.DTETRM , GMHI.DTETRM
, SRC.PNDATE, GMHD.PNDATE, SRC.NOTSFROM, GMHI.NOTSFROM 

FROM SRC_GMHD_GMHI SRC
LEFT OUTER JOIN GMHDPF GMHD ON ( trim(SRC.CHDRNUM) = trim(GMHD.CHDRNUM) AND trim(SRC.MBRNO) = trim(GMHD.MBRNO) AND GMHD.JOBNM= 'G1ZDMBRIND'  )
LEFT OUTER JOIN GMHIPF GMHI ON ( GMHI.CHDRNUM = GMHD.CHDRNUM AND GMHI.MBRNO = GMHD.MBRNO  AND GMHI.CHDRCOY = GMHD.CHDRCOY   )

WHERE 1=1
-- and SRC.REFNUM = '00033758030'
AND (
    (GMHD.CHDRNUM IS NULL OR GMHD.MBRNO  IS NULL ) -- GMHD.GMHD = NULL means Record is not present in IG
     OR ( (TRIM(SRC.CLNTNUM)  <> TRIM(GMHD.CLNTNUM) )   )
     OR ( (TRIM(SRC.CLNTNUM)  <> TRIM(GMHD.CLIENT) )   )
  -- OR ( (TRIM(SRC.DTETRM)  <> TRIM(GMHD.DTETRM) )   ) -- Error
  -- OR ( (TRIM(SRC.DTETRM)  <> TRIM(GMHI.DTETRM) )   )  -- Error 
     OR ( (TRIM(SRC.PNDATE)  <> TRIM(GMHD.PNDATE) )   )
      OR ( (TRIM(SRC.NOTSFROM)  <> TRIM(GMHI.NOTSFROM) )   )
 
)

;

-------------------- Status -------------------

SELECT GMHD.CHDRNUM, GMHD.MBRNO, GMHD.DPNTNO, GMHD.STATCODE, GCHD.STATCODE
FROM GMHDPF GMHD
LEFT OUTER JOIN CHDRPF GCHD ON ( GMHD.CHDRNUM = GCHD.CHDRNUM)
WHERE GMHD.JOBNM = 'G1ZDMBRIND'
AND (
  (  TRIM(GMHD.STATCODE) <> TRIM( GCHD.STATCODE) )
)
;

-------------------- GMHI_WORKPLACE2_SRC -------------------
 -- Error code has null value
WITH GMHI_WORKPLACE2_SRC AS (
    SELECT * FROM (
        select GMHD.CHDRNUM, GMHD.MBRNO, GMHD.CLNTNUM
        , gchi.EFFDATE
        , ROW_NUMBER() OVER (PARTITION BY GMHD.CHDRNUM, GMHD.MBRNO,GMHD.CLNTNUM  ORDER BY Zcln.EFFDATE desc) RN
        ,  Zcln.CLNTNUM  Zcln_CLNTNUM ,  Zcln.EFFDATE  Zcln_EFFDATE
        , Zcln.ZWORKPLCE Zcln_ZWORKPLCE  , GMHI.ZWORKPLCE2 
        from GMHDPF GMHD 
        left outer join GCHIPF gchi on (gchi.CHDRNUM = GMHD.CHDRNUM AND gchi.CHDRCOY = GMHD.CHDRCOY)
        LEFT OUTER JOIN GMHIPF GMHI ON ( GMHI.CHDRNUM = GMHD.CHDRNUM AND GMHI.MBRNO = GMHD.MBRNO  AND GMHI.CHDRCOY = GMHD.CHDRCOY   )
        left outer join zclnpf Zcln on ( Zcln.CLNTNUM = GMHD.CLNTNUM AND Zcln.EFFDATE <= gchi.EFFDATE)
        where GMHD.JOBNM= 'G1ZDMBRIND'
    ) DT
WHERE RN = 1
)
SELECT * 
FROM GMHI_WORKPLACE2_SRC SRC
WHERE 1=1
and ( 
   ( TRIM(SRC.Zcln_ZWORKPLCE) <> TRIM(SRC.ZWORKPLCE2) )
   or ( ( TRIM(SRC.Zcln_ZWORKPLCE) IS NULL ) AND  (TRIM(SRC.ZWORKPLCE2) IS NOT NULL ))
or ( ( TRIM(SRC.Zcln_ZWORKPLCE) IS NOT NULL ) AND  (TRIM(SRC.ZWORKPLCE2) IS  NULL ))
)


----------------------------------------------------------------------------------
-- ================================== 04_CLRRPF_AUDIT_CLRRPF.sql  ==========================================================

------------------------- INSURED_LF ----------------------------------

WITH SRC_CLRRPF_INSURED AS (
SELECT REFNUM, SUBSTR(TRIM(REFNUM),1,8) CHDRNUM, MBRNO
	 , PAZD.ZIGVALUE IG_ZIGVALUE
	 , P1.CLIENTNO DM_CLIENT_NUMBER
FROM STAGEDBUSR.TITDMGMBRINDP1@DMSTAGEDBLINK P1
LEFT OUTER JOIN Jd1dta.PAZDCLPF PAZD ON (TRIM(P1.CLIENTNO) = TRIM(PAZD.ZENTITY) )
WHERE 1=1
AND P1.MBRNO IS NOT NULL
)
select SRC.REFNUM, SRC.CHDRNUM SRC_CHDRNUM, CLRR.FORENUM IG_FORENUM_CHDRNUM
,  SRC.MBRNO, SRC.DM_CLIENT_NUMBER 
, SRC.IG_ZIGVALUE, CLRR.CLNTNUM
, CLRR.CLRRROLE
from SRC_CLRRPF_INSURED SRC
LEFT OUTER JOIN CLRRPF CLRR ON ( TRIM (SRC.IG_ZIGVALUE) = TRIM (CLRR.CLNTNUM) 
  AND  TRIM (SRC.CHDRNUM) = TRIM (CLRR.FORENUM) 
    AND   TRIM (CLRR.CLRRROLE)  = 'LF' AND  CLRR.JOBNM = 'G1ZDMBRIND'
)
WHERE 1=1 
AND
( 
  (CLRR.CLNTNUM IS NULL )
 );




------------------------- OWNER _ OW ----------------------------------
WITH SRC_CLRRPF_OWNER_OW AS (
SELECT REFNUM, SUBSTR(TRIM(REFNUM),1,8) CHDRNUM, MBRNO
	 , PAZD.ZIGVALUE IG_ZIGVALUE
	 , P1.CLIENTNO DM_CLIENT_NUMBER
FROM STAGEDBUSR.TITDMGMBRINDP1@DMSTAGEDBLINK P1
LEFT OUTER JOIN Jd1dta.PAZDCLPF PAZD ON (TRIM(P1.CLIENTNO) = TRIM(PAZD.ZENTITY) )
WHERE 1=1
AND P1.MBRNO IS NULL
)
select SRC.REFNUM, SRC.CHDRNUM SRC_CHDRNUM, CLRR.FORENUM IG_FORENUM_CHDRNUM
,  SRC.MBRNO, SRC.DM_CLIENT_NUMBER 
, SRC.IG_ZIGVALUE, CLRR.CLNTNUM
, CLRR.CLRRROLE
from SRC_CLRRPF_OWNER_OW SRC
LEFT OUTER JOIN CLRRPF CLRR ON ( TRIM (SRC.IG_ZIGVALUE) = TRIM (CLRR.CLNTNUM) 
  AND  TRIM (SRC.CHDRNUM) = TRIM (CLRR.FORENUM)  
  AND   TRIM (CLRR.CLRRROLE)  = 'MP' AND  CLRR.JOBNM = 'G1ZDMBRIND'
)
WHERE 1=1 
AND
( 
  (CLRR.CLNTNUM IS NULL )
 )
 ;

------------------------- OWNER_MP ----------------------------------
 
 WITH SRC_CLRRPF_OWNER_MP AS (
SELECT REFNUM, SUBSTR(TRIM(REFNUM),1,8) CHDRNUM, MBRNO
	 , PAZD.ZIGVALUE IG_ZIGVALUE
	 , P1.CLIENTNO DM_CLIENT_NUMBER
FROM STAGEDBUSR.TITDMGMBRINDP1@DMSTAGEDBLINK P1
LEFT OUTER JOIN Jd1dta.PAZDCLPF PAZD ON (TRIM(P1.CLIENTNO) = TRIM(PAZD.ZENTITY) )
WHERE 1=1
AND P1.MBRNO IS NULL
)
select SRC.REFNUM, SRC.CHDRNUM SRC_CHDRNUM, CLRR.FORENUM IG_FORENUM_CHDRNUM
,  SRC.MBRNO, SRC.DM_CLIENT_NUMBER 
, SRC.IG_ZIGVALUE, CLRR.CLNTNUM
, CLRR.CLRRROLE
from SRC_CLRRPF_OWNER_MP SRC
LEFT OUTER JOIN CLRRPF CLRR ON ( TRIM (SRC.IG_ZIGVALUE) = TRIM (CLRR.CLNTNUM) 
  AND  TRIM (SRC.CHDRNUM) = TRIM (CLRR.FORENUM)  
  AND   TRIM (CLRR.CLRRROLE)  = 'MP' AND  CLRR.JOBNM = 'G1ZDMBRIND'
)
WHERE 1=1 
AND
( 
  (CLRR.CLNTNUM IS NULL )
 );



---------------------- AUDIT_CLRRPF   ----------------------------------
SELECT CLRR.CLNTNUM , AUDT.NEWCLNTNUM , CLRR.FORENUM , AUDT.NEWFORENUM , CLRR.CLRRROLE , AUDT.NEWCLRRROLE
, TRIM(CLRR.CLNTCOY) ,  TRIM(AUDT.NEWCLNTCOY)
, TRIM(CLRR.CLNTNUM) ,  TRIM(AUDT.NEWCLNTNUM)
, TRIM(CLRR.CLRRROLE) ,  TRIM(AUDT.NEWCLRRROLE)
, TRIM(CLRR.FORECOY) ,  TRIM(AUDT.NEWFORECOY)
, TRIM(CLRR.FORENUM) ,  TRIM(AUDT.NEWFORENUM)
, TRIM(CLRR.USED2B) ,  TRIM(AUDT.NEWUSED2B)
, TRIM(CLRR.CLNTPFX) ,  TRIM(AUDT.NEWCLNTPFX)
, TRIM(CLRR.FOREPFX) ,  TRIM(AUDT.NEWFOREPFX)
, TRIM(CLRR.USRPRF) ,  TRIM(AUDT.NEWUSRPRF)
, TRIM(CLRR.JOBNM) ,  TRIM(AUDT.NEWJOBNM)

FROM CLRRPF CLRR
LEFT OUTER JOIN AUDIT_CLRRPF AUDT ON ( TRIM(CLRR.CLNTNUM) = TRIM(AUDT.NEWCLNTNUM )
          AND TRIM(CLRR.FORENUM) = TRIM(AUDT.NEWFORENUM) AND TRIM(CLRR.CLRRROLE) = TRIM(AUDT.NEWCLRRROLE))
WHERE CLRR.CLNTNUM  = '50747558' AND CLRR.JOBNM= 'G1ZDMBRIND'
AND (
  ( TRIM(AUDT.NEWCLNTNUM) IS NULL )
  OR ( TRIM(CLRR.CLNTCOY) <> TRIM(AUDT.NEWCLNTCOY) )
  OR ( TRIM(CLRR.CLNTNUM) <> TRIM(AUDT.NEWCLNTNUM) )
  OR ( TRIM(CLRR.CLRRROLE) <> TRIM(AUDT.NEWCLRRROLE) )
  OR ( TRIM(CLRR.FORECOY) <> TRIM(AUDT.NEWFORECOY) )
  OR ( TRIM(CLRR.FORENUM) <> TRIM(AUDT.NEWFORENUM) )
  OR ( TRIM(CLRR.USED2B) <> TRIM(AUDT.NEWUSED2B) )
  OR ( TRIM(CLRR.CLNTPFX) <> TRIM(AUDT.NEWCLNTPFX) )
  OR ( TRIM(CLRR.FOREPFX) <> TRIM(AUDT.NEWFOREPFX) )
  OR ( TRIM(CLRR.USRPRF) <> TRIM(AUDT.NEWUSRPRF) )
  OR ( TRIM(CLRR.JOBNM) <> TRIM(AUDT.NEWJOBNM) )
)

;


----------------------------------------------------------------------------------
-- ===================================== 05_SRC_ZCLEPF.SQL  =======================================================


WITH SRC_ZCLEPF AS (
SELECT REFNUM, SUBSTR(TRIM(REFNUM),1,8) CHDRNUM, MBRNO
	 , PAZD.ZIGVALUE IG_ZIGVALUE
	 , P1.CLIENTNO DM_CLIENT_NUMBER
   , ZENDCDE , ZENSPCD01 , ZENSPCD02 , ZCIFCODE  
FROM STAGEDBUSR.TITDMGMBRINDP1@DMSTAGEDBLINK P1
LEFT OUTER JOIN Jd1dta.PAZDCLPF PAZD ON (TRIM(P1.CLIENTNO) = TRIM(PAZD.ZENTITY) )
WHERE 1=1
AND P1.MBRNO IS  NULL
)
SELECT SRC.REFNUM, SRC.CHDRNUM SRC_CHDRNUM
, SRC.IG_ZIGVALUE IG_ZIGVALUE, ZCLE.CLNTNUM IG_CLNTNUM 
, SRC.ZENDCDE , ZCLE.ZENDCDE , SRC.ZENSPCD01 , ZCLE.ZENSPCD01
, SRC.ZENSPCD02 , ZCLE.ZENSPCD02 , SRC.ZCIFCODE , ZCLE.ZCIFCODE

FROM SRC_ZCLEPF SRC
LEFT OUTER JOIN Jd1dta.ZCLEPF ZCLE ON ( TRIM (SRC.IG_ZIGVALUE) = TRIM (ZCLE.CLNTNUM)  AND ZCLE.JOBNM= 'G1ZDMBRIND')
WHERE 1=1 
AND (
  ( TRIM(ZCLE.CLNTNUM) IS NULL )
  OR ( TRIM(SRC.ZENDCDE) <> TRIM(ZCLE.ZENDCDE) )
  OR ( TRIM(SRC.ZENSPCD01) <> TRIM(ZCLE.ZENSPCD01) )
  OR ( TRIM(SRC.ZENSPCD02) <> TRIM(ZCLE.ZENSPCD02) )
  OR ( TRIM(SRC.ZCIFCODE) <> TRIM(ZCLE.ZCIFCODE) )
 
)

;



----------------------------------------------------------------------------------
-- ===================================== 06_ZCELINKPF.sql  =======================================================


WITH SRC_ZCELINKPF AS (
SELECT REFNUM, SUBSTR(TRIM(REFNUM),1,8) CHDRNUM, MBRNO
	 , PAZD.ZIGVALUE IG_ZIGVALUE
	 , P1.CLIENTNO DM_CLIENT_NUMBER
   , ZENDCDE , ZENSPCD01 , ZENSPCD02 , ZCIFCODE  
FROM STAGEDBUSR.TITDMGMBRINDP1@DMSTAGEDBLINK P1
LEFT OUTER JOIN Jd1dta.PAZDCLPF PAZD ON (TRIM(P1.CLIENTNO) = TRIM(PAZD.ZENTITY) )
WHERE 1=1
AND P1.MBRNO IS  NULL
)
SELECT SRC.REFNUM, SRC.CHDRNUM SRC_CHDRNUM
, SRC.IG_ZIGVALUE IG_ZIGVALUE, ZCELINK.CLNTNUM IG_CLNTNUM 
, SRC.ZENDCDE , ZCELINK.ZENDCDE 

FROM SRC_ZCELINKPF SRC
LEFT OUTER JOIN Jd1dta.ZCELINKPF ZCELINK ON ( TRIM (SRC.IG_ZIGVALUE) = TRIM (ZCELINK.CLNTNUM)  AND ZCELINK.JOBNM= 'G1ZDMBRIND')
WHERE 1=1 
AND (
  ( TRIM(ZCELINK.CLNTNUM) IS NULL )
  OR ( TRIM(SRC.ZENDCDE) <> TRIM(ZCELINK.ZENDCDE) )
 
)

;
