 CREATE OR REPLACE FORCE EDITIONABLE VIEW "Jd1dta"."VIEW_PAZDCLPF" ("RECSTATUS", "PREFIX", "ZENTITY", "ZIGVALUE", "JOBNUM", "JOBNAME") AS 
  SELECT  
  "RECSTATUS", 
  "PREFIX", 
  "ZENTITY",
  "ZIGVALUE", 
  "JOBNUM",
  "JOBNAME"
FROM Jd1dta.PAZDCLPF;