--Ig tables not used
TRUNCATE TABLE vm1dta.RAPA_CLIENTINFO ;
TRUNCATE TABLE vm1dta.IG_TITDMGPOLTRNH;
--TRUNCATE TABLE vm1dta.ZERRPF;--Required_masking
TRUNCATE TABLE vm1dta.CLNTPF_BEFORE_PATCH;
TRUNCATE TABLE vm1dta.AUDIT_CLNTPF_BEFORE_PATCH;
TRUNCATE table VM1DTA.POLDATATEMP;
TRUNCATE TABLE VM1DTA.MV_ZMCIPF_CRDT_BAK;
TRUNCATE TABLE VM1DTA.MV_ZMCIPF_BAK;
Truncate table VM1DTA.AGNT_CLNT3;
Truncate table VM1DTA.ZCSVAD0001;
Truncate table VM1DTA.ZCSVAD0002;
Truncate table VM1DTA.ZVCHPF;
Truncate table VM1DTA.INT_MISPOL ;
Truncate table VM1DTA.INT_MISPOL_SUMINST ;
Truncate table VM1DTA.INT_MISPOL_AGENCY_COMM ;
Truncate table VM1DTA.INT_MISPOL_COMPAIGN ;
Truncate table VM1DTA.INT_MISPOL_ZMCI ;
Truncate table VM1DTA.INT_MISPOL_ZTRA ;
Truncate table VM1DTA.INT_MISINS ;
Truncate table VM1DTA.INT_MISINS_GMHI ;
Truncate table VM1DTA.INT_MISINS_GXHI ;
Truncate table VM1DTA.INT_MISINS_RIDER ;
Truncate table VM1DTA.INT_MISINS_SUMINST ;
--Truncate table VM1DTA.TEMP_13434_PS_2;
--Truncate table VM1DTA.MEMBER_AGENT_TEMP;
--Truncate table VM1DTA.RIDER_ACUM_TEMP;
--Truncate table VM1DTA.RIDER_ACUM_TEMP_ACT;
--Truncate table VM1DTA.ASRFTYPE_ACUM_TEMP;
--Truncate table VM1DTA.TEMPINRG;
--Truncate table VM1DTA.GBIH_TEMP;
--Truncate table VM1DTA.TEMP1;
--Truncate table VM1DTA.TEMP_13434_PS;
--Truncate table VM1DTA.TEMPBILL;

---New Additional for Production 
Truncate table VM1DTA.ZUCL_PGP_PATCH_ALL;
Truncate table VM1DTA.ZUCL_FIX_XN_DEC;
Truncate table VM1DTA.ZTRA_LOGALTDT_PATCH;
Truncate table VM1DTA.ZODEPF;
Truncate table VM1DTA.ZMCI_FP_INS_15NOV;
Truncate table VM1DTA.ZEIOPF;
Truncate table VM1DTA.ZDOEPH0001;
Truncate table VM1DTA.ZDOEMB0006;
Truncate table VM1DTA.ZDOEIN0006;
Truncate table VM1DTA.ZDOECP0001;
Truncate table VM1DTA.ZDOECB0100;
Truncate table VM1DTA.ZDOECB0099;
Truncate table VM1DTA.ZDOECB0006;
Truncate table VM1DTA.ZDOEBL0025;
Truncate table VM1DTA.ZDOEBL0024;
Truncate table VM1DTA.ZDOEBL0023;
Truncate table VM1DTA.ZDOEBL0022;
Truncate table VM1DTA.ZDOEBL0021;
Truncate table VM1DTA.ZCSVCS0002;
Truncate table VM1DTA.ZCSVCS0001;
Truncate table VM1DTA.ZCSVCD0002;
Truncate table VM1DTA.ZCSVCD0001;
Truncate table VM1DTA.WRQ_UNDELI;
Truncate table VM1DTA.UNDELIVERABLE;
Truncate table VM1DTA.TMP_DMZALTPF_DLT;
Truncate table VM1DTA.TMP_DMZALTPF_2;
Truncate table VM1DTA.TMP_ALL_SHFTS_DEC18;
Truncate table VM1DTA.TEMPINRG_PS;
Truncate table VM1DTA.RIFR3A0913;
Truncate table VM1DTA.RIFR3A0912;
Truncate table VM1DTA.RIFR3A0911;
Truncate table VM1DTA.RIFR3A0910;
Truncate table VM1DTA.RIFR3A0909;
Truncate table VM1DTA.RIFR3A0908;
Truncate table VM1DTA.RIFR3A0907;
Truncate table VM1DTA.RIFR3A0906;
Truncate table VM1DTA.RIFR3A0905;
Truncate table VM1DTA.RIFR3A0904;
Truncate table VM1DTA.RIFR3A0903;
Truncate table VM1DTA.RIFR3A0902;
Truncate table VM1DTA.RIFR3A0901;
Truncate table VM1DTA.RIFR3A0900;
Truncate table VM1DTA.RIFR3A0899;
Truncate table VM1DTA.RIFR3A0898;
Truncate table VM1DTA.RIFR3A0897;
Truncate table VM1DTA.RIFR3A0896;
Truncate table VM1DTA.RIFR3A0895;
Truncate table VM1DTA.RIFR3A0894;
Truncate table VM1DTA.RIFR3A0893;
Truncate table VM1DTA.RIFR3A0892;
Truncate table VM1DTA.RIFR3A0891;
Truncate table VM1DTA.RIFR3A0890;
Truncate table VM1DTA.RIFR3A0889;
Truncate table VM1DTA.RIFR3A0888;
Truncate table VM1DTA.RIFR3A0887;
Truncate table VM1DTA.RIFR3A0886;
Truncate table VM1DTA.RIFR3A0885;
Truncate table VM1DTA.RIFR3A0884;
Truncate table VM1DTA.RIFR3A0883;
Truncate table VM1DTA.RIFR3A0882;
Truncate table VM1DTA.RIFR3A0881;
Truncate table VM1DTA.PS_ADRPF_3;
Truncate table VM1DTA.PS_ADRPF_2;
Truncate table VM1DTA.PS_ADRPF_1;
Truncate table VM1DTA.PS_ADRPF;
Truncate table VM1DTA.GMVX3A0913;
Truncate table VM1DTA.GMVX3A0912;
Truncate table VM1DTA.GMVX3A0911;
Truncate table VM1DTA.GMVX3A0910;
Truncate table VM1DTA.GMVX3A0909;
Truncate table VM1DTA.GMVX3A0908;
Truncate table VM1DTA.GMVX3A0907;
Truncate table VM1DTA.GMVX3A0906;
Truncate table VM1DTA.GMVX3A0905;
Truncate table VM1DTA.GMVX3A0904;
Truncate table VM1DTA.GMVX3A0903;
Truncate table VM1DTA.GMVX3A0902;
Truncate table VM1DTA.GMVX3A0901;
Truncate table VM1DTA.GMVX3A0900;
Truncate table VM1DTA.GMVX3A0899;
Truncate table VM1DTA.GMVX3A0898;
Truncate table VM1DTA.GMVX3A0897;
Truncate table VM1DTA.GMVX3A0896;
Truncate table VM1DTA.GMVX3A0895;
Truncate table VM1DTA.GMVX3A0894;
Truncate table VM1DTA.GMVX3A0893;
Truncate table VM1DTA.GMVX3A0892;
Truncate table VM1DTA.GMVX3A0891;
Truncate table VM1DTA.GMVX3A0890;
Truncate table VM1DTA.GMVX3A0889;
Truncate table VM1DTA.GMVX3A0888;
Truncate table VM1DTA.GMVX3A0887;
Truncate table VM1DTA.GMVX3A0886;
Truncate table VM1DTA.GMVX3A0885;
Truncate table VM1DTA.GMVX3A0884;
Truncate table VM1DTA.GMVX3A0883;
Truncate table VM1DTA.GMVX3A0882;
Truncate table VM1DTA.GMVX3A0881;
Truncate table VM1DTA.DMZEIDPF;
Truncate table VM1DTA.DM_TMP_ZTRAPF;
Truncate table VM1DTA.DM_TMP_ZDPT;
Truncate table VM1DTA.DM_TMP_ZCRHPF;
Truncate table VM1DTA.DM_TMP_ZALTPF;
Truncate table VM1DTA.DM_TMP_POLCA_2;
Truncate table VM1DTA.DM_TMP_MAX;
Truncate table VM1DTA.DM_TMP_GCHD;
Truncate table VM1DTA.DM_TMP_CLBA_2;
Truncate table VM1DTA.DM_TMP_CLBA;
Truncate table VM1DTA.DM_TMP_AGTPNUM_2;
Truncate table VM1DTA.DM_TMP_AGTPNUM;
Truncate table VM1DTA.DM_MATCH_TRANNO;
Truncate table VM1DTA.DM_GBIH_TRN;
Truncate table VM1DTA.CLNTPF_NAYOSE_AUDIT_CN;
Truncate table VM1DTA.CLNTPF_NAYOSE_AUDIT_C;
Truncate table VM1DTA.CLNTPF_NAYOSE_AUDIT;
Truncate table VM1DTA.CLNTPF_NAYOSE;
--truncate table vm1dta.clrrpf;
--truncate table vm1dta.audit_clrrpf;
Truncate table VM1DTA.titdmgcltrnhis_fp_temp;
Truncate table VM1DTA.titdmgcltrnhis_temp;
Truncate table VM1DTA.titdmgclntprsn_freeplan_temp;
Truncate table VM1DTA.titdmgclntprsn_temp;
Truncate table VM1DTA.zletcad2_a;
Truncate table VM1DTA.CLNTPF_NAYOSE;
Truncate table VM1DTA.CLNTPF_NAYOSE_AUDIT;
Truncate table VM1DTA.CLNTPF_NAYOSE_AUDIT_C;
Truncate table VM1DTA.CLNTPF_NAYOSE_AUDIT_CN;

-- Added in phase 2 PA:20211214
Truncate table ZINTMBRCAMPAIGNPF ;
Truncate table POLDATATEMP  ;
Truncate table GCHPPF_TEST  ;
Truncate table INT_MIS_POL ;
Truncate table INT_ACT_CLIENT ;
Truncate table INT_MIS_ACT_STAGE ;
Truncate table INT_MIS_ACT_POL_DTLS ;
Truncate table INT_MIS_LOGS ;
Truncate table INT_MIS_INSURED ;
Truncate table INT_MIS_ACT_INSURED ;
Truncate table ZRNWLTEMP ;
Truncate table INT_MIS_POL_TRAN ;
Truncate table INT_MIS_ACT_TRAN ;
Truncate table PRINTLNG ;
Truncate table MEMBER_AGENT_TEMP ;
Truncate table INT_MIS_ACT_COVERAGE ;
Truncate table ZRNWLMASTERTEMP ;
Truncate table INT_MIS_BILL ;
Truncate table TEMPINRG  ;
Truncate table IDENTITY_UNIQUE_NO_TMP ;
Truncate table IGNAYOSEVIEW ;
Truncate table TMP_ZALT_ZMCI_BANKKEY ;
Truncate table ZATEPF ;
Truncate table ZATWPF ;
Truncate table ZMIEPF ;
Truncate table ZMUPPF ;
Truncate table ZRNWLEROR ;
Truncate table ZRNWLSUCC ;
Truncate table ZASRFRST  ;
Truncate table CLNTQY ;
Truncate table MIOKPF ;
Truncate table ZPDAPF ;
Truncate table ZSTPPF ;
Truncate table ZBDTPF ;
Truncate table ZPODPF ;
Truncate table ZPODTPF ;
Truncate table ZRLEPF ;
Truncate table ZERRPF ;
Truncate table AGCNPF ;
Truncate table AGNXPF ;
Truncate table AGPDPF ;
Truncate table MV_CLIENT_NAYOSE ;
Truncate table DMIGTITDMGCLTRNHIS;
truncate table DMIGTITDMGAPIRNO;
truncate table DMIGTITDMGCLNTBANK;
truncate table DMIGTITDMGCLNTCORP;
truncate table DMIGTITDMGCLTRNHIS;
truncate table DMIGTITDMGLETTER;
truncate table DMIGTITDMGMBRINDP1;
truncate table DMIGTITDMGPOLTRNH;
truncate table DMIGTITDMGREF1;
truncate table DMIGTITNYCLT;
truncate table DMPANAYOSEVIEW;
truncate table DM_AUDIT_CLEXPF_BKP;
truncate table DM_AUDIT_CLNTPF_BKP;
truncate table DM_CLEXPF_BKP;
truncate table DM_CLNTPF_BKP;
truncate table DM_TEMP_POLHIST;
truncate table DM_TMP_CLBA;
truncate table DM_TMP_CLBA_2;
truncate table DM_ZCLNPF_BKP;
truncate table IG_TITDMGPOLTRNH;

----------- 20211227The below GMOVPF is truncated because OLDDATA has email address detected by Camauflage---
truncate table GMOVPF;
truncate table ZSTGPF20200312;
exec LOG_BAT_STATUS('MASK_Truncated_SomeOfVM1DTATables'); 
