OPTIONS (DIRECT=TRUE)
UNRECOVERABLE
LOAD DATA
REPLACE
INTO TABLE VM1DTA.ZCORPF
FIELDS TERMINATED BY "," ENCLOSED BY '"'
TRAILING NULLCOLS
(
UNIQUE_NUMBER,
CHDRCOY      ,
CHDRNUM      ,
TRANNO       ,
ZKANASNM     ,
ZKANAGNM     ,
LSURNAME     ,
LGIVNAME     ,
ZRCORADR     ,
CLTPCODE     ,
CLTADDR01    ,
CLTADDR02    ,
CLTADDR03    ,
CLTADDR04    ,
ZKANADDR01   ,
ZKANADDR02   ,
ZKANADDR03   ,
ZKANADDR04   ,
CLTPHONE01   ,
USRPRF       ,
JOBNM        ,
DATIME       ,
EFFDATE
)
