CREATE TABLE "ZBENFDTLSPF_EXT"
(
        "UNIQUE_NUMBER" NUMBER(18),
         "CLTADDR01"  VARCHAR2(60 CHAR),
         "CLTADDR02"  VARCHAR2(60 CHAR),
         "CLTADDR03"  VARCHAR2(60 CHAR),
         "CLTADDR04"  VARCHAR2(60 CHAR),
         "ZKNJFULNM"  VARCHAR2(120 CHAR)
                )
ORGANIZATION external
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZBENFDTLSPF_EXT.bad'
    LOGFILE 'ZBENFDTLSPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","
    REJECT ROWS WITH ALL NULL FIELDS
    (
        "UNIQUE_NUMBER"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
                "CLTADDR01"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"CLTADDR02"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"CLTADDR03"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"CLTADDR04"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"ZKNJFULNM"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
                 )
       )
location
  (
    'outputZBENFDTLSPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZBENFDTLSPF_EXT;

