CREATE TABLE "ZCLEPF_EXT"
(
         "UNIQUE_NUMBER" NUMBER(18),
         "ZENSPCD01"  VARCHAR2(70 CHAR),
         "ZENSPCD02"  VARCHAR2(70 CHAR),
         "ZCIFCODE"  VARCHAR2(15 CHAR)
                )
ORGANIZATION external
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZCLEPF_EXT.bad'
    LOGFILE 'ZCLEPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","
    REJECT ROWS WITH ALL NULL FIELDS
    (
        	"UNIQUE_NUMBER"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
                "ZENSPCD01"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
                "ZENSPCD02"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
                "ZCIFCODE"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
                 )
       )
location
  (
    'outputZCLEPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZCLEPF_EXT;

