CREATE TABLE "ZINSDTLSPF_EXT"
(
        "UNIQUE_NUMBER" NUMBER(18),
         "ZWORKPLCE2"  VARCHAR2(25 CHAR)
                )
ORGANIZATION external
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZINSDTLSPF_EXT.bad'
    LOGFILE 'ZINSDTLSPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","
    REJECT ROWS WITH ALL NULL FIELDS
    (
        "UNIQUE_NUMBER"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
                "ZWORKPLCE2"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
                 )
       )
location
  (
    'outputZINSDTLSPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZINSDTLSPF_EXT;
