CREATE TABLE "ZIRDPF_EXT"
(
         "CLNTNUM" VARCHAR2(200 CHAR),
         "CLNTNME"  VARCHAR2(200 CHAR)        
 )
ORGANIZATION external
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZIRDPF_EXT.bad'
    LOGFILE 'ZIRDPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","
    REJECT ROWS WITH ALL NULL FIELDS
    (
        "CLNTNUM"    CHAR(255)  TERMINATED BY "," ENCLOSED BY '"',
        "CLNTNME"    CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
         )
     )
location
  (
    'outputZIRDPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZIRDPF_EXT;

    

