CREATE TABLE "ZIRHPF_EXT"
(
         "BILLLNO" NUMBER(18),
         "CRDTCARD"  VARCHAR2(20 CHAR),
         "BANKACCKEY"  VARCHAR2(20 CHAR)
         )
ORGANIZATION external
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZIRHPF_EXT.bad'
    LOGFILE 'ZIRHPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","
    REJECT ROWS WITH ALL NULL FIELDS
    (
        "BILLLNO"    CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
        "CRDTCARD"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
	"BANKACCKEY"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
          )
    )
location
  (
    'outputZIRHPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZIRHPF_EXT;
