CREATE TABLE "ZRLEPF_EXT"
(
        "UNIQUE_NUMBER"      NUMBER(18,0),
         "ZKANASNM"         VARCHAR2(60 CHAR),
         "ZKANAGNM"         VARCHAR2(60 CHAR)
               
)
ORGANIZATION external
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZRLEPF_EXT.bad'
    LOGFILE 'ZRLEPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","
    REJECT ROWS WITH ALL NULL FIELDS
    (
        "UNIQUE_NUMBER"     CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
        "ZKANASNM" CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
                "ZKANAGNM"    CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
)
  )
  location
  (
    'outputZRLEPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZRLEPF_EXT;

