CREATE TABLE "TOTPAMBILDAT_EXT" 
(
        "RECIDXBILDAT"      NUMBER(38,0), 
		"CCARD"            VARCHAR2(20 CHAR),
		"BANKACCKEY"       VARCHAR2(20 CHAR),
		"MBRNAM"         VARCHAR2(60 CHAR),
		"CRDNAM"         VARCHAR2(30 CHAR)
		
		
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'TOTPAMBILDAT_EXT.bad'
    LOGFILE 'TOTPAMBILDAT_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
         "RECIDXBILDAT"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"CCARD"        CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"BANKACCKEY"     CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"MBRNAM"         CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"CRDNAM"         CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"' 
		  
    )
  )
  location 
  (
    '/opt/ig/hitoku/user/output/outputTOTPAMBILDAT.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table TOTPAMBILDAT_EXT;

--select * from TOTPAMBILDAT_EXT; 