CREATE TABLE "TOTPAMRFDPREM_EXT" 
(
 "RECIDXRFDPRM" NUMBER, 
"BANKACCKEY" VARCHAR2(20 CHAR),
"BANKACCDSC" VARCHAR2(30 CHAR)
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'TOTPAMRFDPREM_EXT.bad'
    LOGFILE 'TOTPAMRFDPREM_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
	  "RECIDXRFDPRM"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
	    "BANKACCKEY"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		  "KANJINME"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		    "BANKACCDSC"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"'
			 
	
	)
	 )
  location 
  (
    '/opt/ig/hitoku/user/output/outputTOTPAMRFDPREM.csv'
  )
)REJECT LIMIT UNLIMITED;
/
