CREATE TABLE "TOTPAMVALCHKD_EXT" 
(
 "RECIDXVALCHK" NUMBER, 
"ZMSTSNME" VARCHAR2(60 CHAR),
"KANANME" VARCHAR2(121 CHAR),
"KANJINME" VARCHAR2(121 CHAR),
"CLTPHONE01" VARCHAR2(16 CHAR),
"CLTPHONE02" VARCHAR2(16 CHAR),
"KANJICLTADDR" VARCHAR2(150 CHAR)
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'TOTPAMVALCHKD_EXT.bad'
    LOGFILE 'TOTPAMVALCHKD_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
	 "RECIDXVALCHK"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
	  "ZMSTSNME"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
	    "KANANME"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		  "KANJINME"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		    "CLTPHONE01"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
			  "CLTPHONE02"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
			  "KANJICLTADDR"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"'
	
	)
	 )
  location 
  (
    '/opt/ig/hitoku/user/output/outputTOTPAMVALCHKD.csv'
  )
)REJECT LIMIT UNLIMITED;
/
