CREATE TABLE "TOTPAMPOSTTGTD_EXT" 
(
 "RECIDXPOSTTGTD" NUMBER, 
"CCARD" VARCHAR2(20 CHAR),
"BANKACCKEY" VARCHAR2(20 CHAR)
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'DATA_DIR':'TOTPAMPOSTTGTD_EXT.bad'
    LOGFILE 'TOTPAMPOSTTGTD_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
	  "RECIDXPOSTTGTD"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
	    "CCARD"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		  "BANKACCKEY"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"'
	
	)
	 )
  location 
  (
    '/opt/ig/hitoku/user/output/outputTOTPAMPOSTTGTD.csv'
  )
)REJECT LIMIT UNLIMITED;
/
