
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZENCIPF', 'C', '',TRUE,FALSE,0,0,0,FALSE);
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZENDRPF', 'C', '',TRUE,FALSE,0,0,0,FALSE);
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZMCIPF', 'C', '',TRUE,FALSE,0,0,0,FALSE);
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZMCIPF_CRDT', 'C', '',TRUE,FALSE,0,0,0,FALSE);
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZENCIPF', 'F', '',TRUE,FALSE,0,0,0,FALSE);
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZENDRPF', 'F', '',TRUE,FALSE,0,0,0,FALSE);
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZMCIPF', 'F', '',TRUE,FALSE,0,0,0,FALSE);
execute DBMS_MVIEW.REFRESH('Jd1dta.MV_ZMCIPF_CRDT', 'F', '',TRUE,FALSE,0,0,0,FALSE);
