CREATE TABLE "ZREPPF_EXT" 
(
        "UNIQUE_NUMBER"      NUMBER(18,0), 
		"BANKACCDSC"         VARCHAR2(30 CHAR),
		"BANKACOUNT"   VARCHAR2(20 CHAR)
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZREPPF_EXT.bad'
    LOGFILE 'ZREPPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
        "UNIQUE_NUMBER"     CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"BANKACCDSC"        CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"BANKACOUNT"    CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
)
  )
  location 
  (
    'outputZREPPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZREPPF_EXT;

--select * from ZREPPF_EXT; 