CREATE TABLE "ZVCHPF_EXT" 
(
        "UNIQUE_NUMBER" NUMBER(18,0), 
		"CLTPHONE01"   VARCHAR2(16 CHAR),
		"CLTPHONE02"   VARCHAR2(16 CHAR)		
)
ORGANIZATION external 
(
  TYPE oracle_loader
  DEFAULT DIRECTORY EXT_DATA_DIR
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE CHARACTERSET JA16SJISTILDE
    BADFILE 'EXT_DATA_DIR':'ZVCHPF_EXT.bad'
    LOGFILE 'ZVCHPF_EXT.log_xt'
    READSIZE 1048576
    FIELDS TERMINATED BY ","  
    REJECT ROWS WITH ALL NULL FIELDS 
    (
        "UNIQUE_NUMBER"  CHAR(255)   TERMINATED BY "," ENCLOSED BY '"',
		"CLTPHONE01"   CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"',
		"CLTPHONE02"   CHAR(255 ) TERMINATED BY "," ENCLOSED BY '"'
		)
  )
  location 
  (
    'outputZVCHPF.csv'
  )
)REJECT LIMIT UNLIMITED;
/

--drop table ZVCHPF_EXT;

--select * from ZVCHPF_EXT; 