--CREATION OF THE TYPES FOR CLIENT BANK RECONCILIATION SET 2

DROP TYPE TYP_TBL_CB_RECON2;
/
DROP TYPE TYP_REC_CB_RECON2;
/
CREATE OR REPLACE TYPE TYP_REC_CB_RECON2 IS OBJECT (
	  V_PRD_CDE	VARCHAR2(10 BYTE),
	  V_POLICY_NO VARCHAR2(15 CHAR),
	  V_POL_STATUS	CHAR(4 BYTE),
	  D_POL_START_DT NUMBER(8,0),
	  REFNUM VARCHAR2(15 CHAR), 
      CURRTO NUMBER(8,0), 
      BANKCD VARCHAR2(10 CHAR), 
      BRANCHCD VARCHAR2(10 CHAR), 
      FACTHOUS VARCHAR2(2 CHAR),
	  CARDNO VARCHAR2(20 CHAR),
      BANKACCDSC VARCHAR2(30 CHAR), 
      BNKACTYP VARCHAR2(4 CHAR),
	  ZENTITY  VARCHAR2(15 CHAR)
      );
/
CREATE OR REPLACE TYPE  TYP_TBL_CB_RECON2 AS TABLE OF TYP_REC_CB_RECON2;
/