MERGE INTO TOTPAMDINECITI A USING TOTPAMDINECITI_EXT B
ON (A.RECIDXDINCIT = B.RECIDXDINCIT)
WHEN MATCHED THEN
    UPDATE SET
		A.CLTPHONE01  = B.CLTPHONE01 ,
		A.PHZKANASNM  = B.PHZKANASNM ,
		A.PHZKANAGNM = B.PHZKANAGNM,
		A.INSZKANASNM = B.INSZKANASNM,
		A.CLTADDR01 = B.CLTADDR01,
		A.CLTADDR02 = B.CLTADDR02,
		A.CLTADDR03 = B.CLTADDR03,
		A.CLTADDR04 = B.CLTADDR04,
		A.LSURNAME = B.LSURNAME,
		A.LGIVNAME = B.LGIVNAME,
		A.CRDTCARD  = B.CRDTCARD ;
