MERGE INTO TOTPAMVALCHKD A USING TOTPAMVALCHKD_EXT B
ON (A.RECIDXVALCHK = B.RECIDXVALCHK)
WHEN MATCHED THEN
    UPDATE SET
		A.ZMSTSNME = B.ZMSTSNME,
		A.KANANME = B.KANANME,
		A.KANJINME = B.KANJINME,
		A.CLTPHONE01 = B.CLTPHONE01,
		A.CLTPHONE02 = B.CLTPHONE02,
		A.KANJICLTADDR = B.KANJICLTADDR;
		