--Stage Tables IG  
TRUNCATE TABLE stagedbusr.TOTPAMBILDAT ;     
TRUNCATE TABLE stagedbusr.TOTPAMDINECITI ; 
TRUNCATE TABLE stagedbusr.TOTPAMENDORLET ; 
TRUNCATE TABLE stagedbusr.TOTPAMENDORLETC ; 
TRUNCATE TABLE stagedbusr.TOTPAMMISCLN ; 
TRUNCATE TABLE stagedbusr.TOTPAMMISCLN_BKP ;   
TRUNCATE TABLE stagedbusr.TOTPAMMISTRA ;    
TRUNCATE TABLE stagedbusr.TOTPAMMISTRA_BKP ; 
TRUNCATE TABLE stagedbusr.TOTPAMPOLDATA ;   
TRUNCATE TABLE stagedbusr.TOTPAMPOLDATA_BKP ;  
TRUNCATE TABLE stagedbusr.TOTPAMPOSTTGTD ;
TRUNCATE TABLE stagedbusr.TOTPAMPOSTTGTD_BKP ;
TRUNCATE TABLE stagedbusr.TOTPAMPOSTINGSM ;
TRUNCATE TABLE stagedbusr.TOTPAMRFDPREM ;  
TRUNCATE TABLE stagedbusr.TOTPAMRFDPREM_BKP ;
TRUNCATE TABLE stagedbusr.TOTPAMVALCHKD ;
Truncate table STAGEDBUSR.TOTPAMBILDAT_BK01 ;
Truncate table STAGEDBUSR.TOTPAMBILDAT_BK02 ;
Truncate table STAGEDBUSR.TOTPAMBILDAT_BK03 ;
Truncate table STAGEDBUSR.TOTPAMBILDAT_BK04 ;
Truncate table STAGEDBUSR.TOTPAMBILDAT_BK05 ;
Truncate table STAGEDBUSR.TOTPAMBILDAT_BKP ;
Truncate table STAGEDBUSR.TOTPAMRFDPREM_BK01 ;
Truncate table STAGEDBUSR.TOTPAMRFDPREM_BK02 ;
Truncate table STAGEDBUSR.TOTPAMRFDPREM_BK03 ;
Truncate table STAGEDBUSR.TOTPAMRFDPREM_BK04 ;
Truncate table STAGEDBUSR.TOTPAMRFDPREM_BK05 ;
Truncate table STAGEDBUSR.TOTPAMPOSTTGTD_BK01 ;
Truncate table STAGEDBUSR.TOTPAMPOSTTGTD_BK02 ;
Truncate table STAGEDBUSR.TOTPAMPOSTTGTD_BK03 ;
Truncate table STAGEDBUSR.TOTPAMPOSTTGTD_BK04 ;
Truncate table STAGEDBUSR.TOTPAMPOSTTGTD_BK05 ;
Truncate table STAGEDBUSR.TOTPAMPOSTINGSM_BK01 ;
Truncate table STAGEDBUSR.TOTPAMPOSTINGSM_BK02 ;
Truncate table STAGEDBUSR.TOTPAMPOSTINGSM_BK03 ;
Truncate table STAGEDBUSR.TOTPAMPOSTINGSM_BK04 ;
Truncate table STAGEDBUSR.TOTPAMPOSTINGSM_BK05 ;
Truncate table STAGEDBUSR.TITPAMCAMPAIGN_BK01 ;
Truncate table STAGEDBUSR.TITPAMCAMPAIGN_BK02 ;
Truncate table STAGEDBUSR.TITPAMCAMPAIGN_BK03 ;
Truncate table STAGEDBUSR.TITPAMCAMPAIGN_BK04 ;
Truncate table STAGEDBUSR.TITPAMCAMPAIGN_BK05 ;
Truncate table STAGEDBUSR.TITPAMVALCHKDR_BK01 ;
Truncate table STAGEDBUSR.TITPAMVALCHKDR_BK02 ;
Truncate table STAGEDBUSR.TITPAMVALCHKDR_BK03 ;
Truncate table STAGEDBUSR.TITPAMVALCHKDR_BK04 ;
Truncate table STAGEDBUSR.TITPAMVALCHKDR_BK05 ;
Truncate table STAGEDBUSR.TOTPAMDINECITI_BK01 ;
Truncate table STAGEDBUSR.TOTPAMDINECITI_BK02 ;
Truncate table STAGEDBUSR.TOTPAMDINECITI_BK03 ;
Truncate table STAGEDBUSR.TOTPAMDINECITI_BK04 ;
Truncate table STAGEDBUSR.TOTPAMDINECITI_BK05 ;
Truncate table STAGEDBUSR.TOTPAMDINECITI_BKP ;
Truncate table STAGEDBUSR.TOTPAMLETPRT ;
Truncate table STAGEDBUSR.TOTPAMLETPRT_BK01 ;
Truncate table STAGEDBUSR.TOTPAMLETPRT_BK02 ;
Truncate table STAGEDBUSR.TOTPAMLETPRT_BK03 ;
Truncate table STAGEDBUSR.TOTPAMLETPRT_BK04 ;
Truncate table STAGEDBUSR.TOTPAMLETPRT_BK05 ;
Truncate table STAGEDBUSR.TOTPAMPOLDATA_BK01 ;
Truncate table STAGEDBUSR.TOTPAMPOLDATA_BK02 ;
Truncate table STAGEDBUSR.TOTPAMPOLDATA_BK03 ;
Truncate table STAGEDBUSR.TOTPAMPOLDATA_BK04 ;
Truncate table STAGEDBUSR.TOTPAMPOLDATA_BK05 ;
Truncate table STAGEDBUSR.TOTPAMVALCHKD_BK01 ;
Truncate table STAGEDBUSR.TOTPAMVALCHKD_BK02 ;
Truncate table STAGEDBUSR.TOTPAMVALCHKD_BK03 ;
Truncate table STAGEDBUSR.TOTPAMVALCHKD_BK04 ;
Truncate table STAGEDBUSR.TOTPAMVALCHKD_BK05 ;

--Migratoin tables 
TRUNCATE TABLE stagedbusr.TITDMGAGENTPJ;
TRUNCATE TABLE stagedbusr.TITDMGBILL1;
TRUNCATE TABLE stagedbusr.TITDMGBILL2;
TRUNCATE TABLE stagedbusr.TITDMGCAMPCDE;
TRUNCATE TABLE stagedbusr.TITDMGCLNTCORP;
TRUNCATE TABLE stagedbusr.TITDMGLETTER  ;
TRUNCATE TABLE stagedbusr.TITDMGSALEPLN1;
TRUNCATE TABLE stagedbusr.TITDMGSALEPLN2;
TRUNCATE TABLE stagedbusr.TITDMGCLTRNHIS_FREE_PLANS;
TRUNCATE TABLE stagedbusr.TITDMGMBRINDP2_FREE_PLANS;
TRUNCATE TABLE stagedbusr.TITDMGCLNTPRSN_FREE_PLANS;
TRUNCATE TABLE stagedbusr.TITDMGCLNTBANK_FREE_PLANS;
TRUNCATE TABLE stagedbusr.TITDMGLETTER_FREE_PLANS;
TRUNCATE TABLE stagedbusr.TITDMGCLNTBANK_PAIDPLAN;
TRUNCATE TABLE stagedbusr.TITDMGMBRINDP1_FREE_PLANS;

---New Additional for Production 
Truncate table STAGEDBUSR.TITPAMBILLSTOP_BK01;
Truncate table STAGEDBUSR.TITPAMBILLSTOP_BK02;
Truncate table STAGEDBUSR.TITPAMBILLSTOP_BK03;
Truncate table STAGEDBUSR.TITPAMBILLSTOP_BK04;
Truncate table STAGEDBUSR.TITPAMBILLSTOP_BK05;
--TRUNCATE TABLE stagedbusr.TITDMGPOLTRNH_FREEPLAN;
TRUNCATE TABLE stagedbusr.TITDMGMBRINDP2_FREEPLAN;
TRUNCATE TABLE stagedbusr.TITDMGLETTER_FREEPLAN;


---------------No one needs it as of now-------------------------
TRUNCATE TABLE stagedbusr.TOTPAMSTADUTCOT;
TRUNCATE TABLE stagedbusr.TOTPAMRFDPREM;
--TRUNCATE TABLE stagedbusr.TOTPAMPROPHET;
TRUNCATE TABLE stagedbusr.TOTPAMPOSTTGTD;
TRUNCATE TABLE stagedbusr.TOTPAMPOSTINGSM;
TRUNCATE TABLE stagedbusr.TOTPAMPOLDATA;
TRUNCATE TABLE stagedbusr.TOTPAMMISTRA;
TRUNCATE TABLE stagedbusr.TOTPAMMISQUOT;
TRUNCATE TABLE stagedbusr.TOTPAMMISPOL;
TRUNCATE TABLE stagedbusr.TOTPAMMISINS;
TRUNCATE TABLE stagedbusr.TOTPAMMISCLN;
TRUNCATE TABLE stagedbusr.TOTPAMMISCAMP;
TRUNCATE TABLE stagedbusr.TOTPAMMISBILL;
TRUNCATE TABLE stagedbusr.TOTPAMLETPRT;
TRUNCATE TABLE stagedbusr.TOTPAMLETBPO;
TRUNCATE TABLE stagedbusr.TOTPAMENDORLETC;
TRUNCATE TABLE stagedbusr.TOTPAMENDORLET;
TRUNCATE TABLE stagedbusr.TOTPAMDINECITI;
TRUNCATE TABLE stagedbusr.TOTPAMBILDAT;
TRUNCATE TABLE stagedbusr.TITPAMRFDSLP;
TRUNCATE TABLE stagedbusr.TITPAMREFCRED;
TRUNCATE TABLE stagedbusr.TITPAMBKACTCH;
TRUNCATE TABLE stagedbusr.TITIPAMRFDSLP;
TRUNCATE TABLE stagedbusr.TITDMGSALEPLN2;
TRUNCATE TABLE stagedbusr.TITDMGSALEPLN1;
TRUNCATE TABLE stagedbusr.TEMP_MISPOL_GXHI;
TRUNCATE TABLE stagedbusr.TCTSTGJOBEXE;
TRUNCATE TABLE stagedbusr.TCDSTGJOBCFG;
---------------------------------------------
------------------ToBeMasked Till then it will be truncated-------------------
TRUNCATE TABLE stagedbusr.TOTPAMVALCHKD;
TRUNCATE TABLE stagedbusr.TOTPAMMISPOL;
TRUNCATE TABLE stagedbusr.TOTPAMMISCLN;

-------------------DM------------
--TRUNCATE TABLE stagedbusr.TITDMGMBRINDP1_FREEPLAN;
--TRUNCATE TABLE stagedbusr.TITDMGCLTRNHIS_FREEPLAN;
--TRUNCATE TABLE stagedbusr.TITDMGCLTRNHIS;
--TRUNCATE TABLE stagedbusr.TITDMGCLNTPRSN_FREEPLAN;
--TRUNCATE TABLE stagedbusr.TITDMGCLNTPRSN;
--TRUNCATE TABLE stagedbusr.TITDMGCLNTBANK_FREEPLAN;
--TRUNCATE TABLE stagedbusr.TITDMGCLNTBANK;
------------------IG----------
--TRUNCATE TABLE stagedbusr.TITPAMVALCHKDR;
--TRUNCATE TABLE stagedbusr.TITPAMBILLSTOP;


-------------------------------------------------------------------------------------

