-- Reference Queries Start
--CLRRPF.FORENUM
SELECT CLRR.CLNTNUM ,TRIM(CLRR.FORENUM) AS CLRRPF_FORNUM, CLBA.CLNTNUM, TRIM(CONCAT(CLBA.BANKKEY , CLBA.BANKACCKEY)) AS CLBAPF_FORENUM
FROM Jd1dta.CLRRPF CLRR 
INNER JOIN Jd1dta.CLBAPF CLBA
ON CLRR.CLNTNUM = CLBA.CLNTNUM
AND SUBSTR(FORENUM,1,4) = SUBSTR(BANKKEY,1,4) --bankcd
AND SUBSTR(FORENUM,8,3) = SUBSTR(BANKKEY,8,10) --branchcd
AND SUBSTR(FORENUM,11) = NVL(BANKACCKEY,0) --cardno
AND CLRR.CLRRROLE IN ('CB','CC')
WHERE RTRIM(CLRR.FORENUM) <> RTRIM(CONCAT(CLBA.BANKKEY , CLBA.BANKACCKEY));

--AUDIT_CLRRPF.OLDCLNTNUM
SELECT TRIM(AC.OLDCLNTNUM) AS AUDIT_CLRRPF_OLDCLNTNUM, TRIM(CLRR.CLNTNUM) AS CLRRPF_CLNTNUM 
FROM Jd1dta.AUDIT_CLRRPF AC 
INNER JOIN Jd1dta.CLRRPF CLRR
ON TRIM(AC.OLDCLNTNUM) = TRIM(CLRR.CLNTNUM)
WHERE TRIM(AC.OLDCLNTNUM) <> TRIM(CLRR.CLNTNUM);

--AUDIT_CLRRPF.NEWCLNTNUM
SELECT TRIM(AC.NEWCLNTNUM) AS AUDIT_CLRRPF_NEWCLNTNUM, TRIM(CLRR.CLNTNUM) AS CLRRPF_CLNTNUM 
FROM Jd1dta.AUDIT_CLRRPF AC 
INNER JOIN Jd1dta.CLRRPF CLRR
ON TRIM(AC.NEWCLNTNUM) = TRIM(CLRR.CLNTNUM)
WHERE TRIM(AC.NEWCLNTNUM) <> TRIM(CLRR.CLNTNUM);

--AUDIT_CLRRPF.NEWFORENUM
SELECT TRIM(AC.NEWFORENUM) AS AUDIT_CLRRPF_NEWFORENUM , CLRR.FORENUM AS CLRRPF_FORENUM 
FROM Jd1dta.AUDIT_CLRRPF AC 
INNER JOIN Jd1dta.CLRRPF CLRR
ON TRIM(AC.OLDCLNTNUM) = TRIM(CLRR.CLNTNUM)
AND SUBSTR(CLRR.FORENUM,1,4) = SUBSTR(AC.NEWFORENUM,1,4) --bankcd
AND SUBSTR(CLRR.FORENUM,8,3) = SUBSTR(AC.NEWFORENUM,8,3) --branchcd
AND SUBSTR(CLRR.FORENUM,11) = SUBSTR(AC.NEWFORENUM,11) --cardno
AND CLRR.CLRRROLE IN ('CB','CC')
WHERE TRIM(AC.NEWFORENUM) <> TRIM(CLRR.FORENUM);
-- Reference Queries End


-- Transformation Queries Start
--CLBAPF.CLNTNUM
SELECT SRC.REFNUM AS SRC_REFNUM, PAZ.ZENTITY AS IG_REFNUM  
FROM TITDMGCLNTBANK@DMSTGUSR2DBLINK SRC
INNER JOIN Jd1dta.PAZDCLPF PAZ 
ON RTRIM(SRC.REFNUM) = RTRIM(PAZ.ZENTITY)
INNER JOIN Jd1dta.CLBAPF CLBA 
ON RTRIM(CLBA.CLNTNUM) = RTRIM(PAZ.ZIGVALUE)
WHERE RTRIM(CLBA.CLNTNUM) <> RTRIM(PAZ.ZIGVALUE);

--CLBAPF.CLNTREL
--When SRC.SRC.BANKACCKEY IS NULL CLNTREL = 'CC' ELSE CLNTREL = 'CB'
SELECT SRC.REFNUM AS SRC_REFNUM, SRC.BANKACCKEY AS SRC_BANKACCKEY
,PAZ.ZENTITY AS IG_REFNUM, CLBA.CLNTREL AS IG_CLNTNUM
FROM TITDMGCLNTBANK@DMSTGUSR2DBLINK SRC
LEFT JOIN Jd1dta.PAZDCLPF PAZ 
ON RTRIM(SRC.REFNUM) = RTRIM(PAZ.ZENTITY)
LEFT JOIN Jd1dta.CLBAPF CLBA 
ON RTRIM(CLBA.CLNTNUM) = RTRIM(PAZ.ZIGVALUE)
AND RTRIM(SRC.BANKCD) = RTRIM(SUBSTR(CLBA.BANKKEY,1,4))
AND RTRIM(SRC.BRANCHCD) = RTRIM(SUBSTR(CLBA.BANKKEY,8,10))
AND RTRIM(SRC.CRDTCARD) = RTRIM(CLBA.BANKACCKEY)
WHERE (CASE WHEN RTRIM(SRC.BANKACCKEY) IS NULL THEN 'CC' ELSE 'CB' END) <> RTRIM(CLBA.CLNTREL);

--CLBAPF.BANKKEY
SELECT SRC.REFNUM ,RTRIM(CONCAT(SRC.BANKCD, '   ' || SRC.BRANCHCD)) AS SRC_BANKEY
,PAZ.ZENTITY AS IG_REFNUM, RTRIM(CLBA.BANKKEY) AS IG_BANKKEY
FROM TITDMGCLNTBANK@DMSTGUSR2DBLINK SRC
LEFT JOIN Jd1dta.PAZDCLPF PAZ 
ON RTRIM(SRC.REFNUM) = RTRIM(PAZ.ZENTITY)
LEFT JOIN Jd1dta.CLBAPF CLBA 
ON RTRIM(CLBA.CLNTNUM) = RTRIM(PAZ.ZIGVALUE)
AND RTRIM(SRC.BANKCD) = RTRIM(SUBSTR(CLBA.BANKKEY,1,4))
AND RTRIM(SRC.BRANCHCD) = RTRIM(SUBSTR(CLBA.BANKKEY,8,10))
AND RTRIM(SRC.CRDTCARD) = RTRIM(CLBA.BANKACCKEY)
WHERE RTRIM(CONCAT(SRC.BANKCD, '   ' || SRC.BRANCHCD)) <> RTRIM(CLBA.BANKKEY);

--CLBAPF.BANKACCKEY
SELECT SRC.REFNUM AS SRC_REFNUM, NVL(RTRIM(SRC.BANKACCKEY) , RTRIM(SRC.CRDTCARD)) AS SRC_BANKACCKEY_OR_CRDTCARD
,PAZ.ZENTITY AS IG_REFNUM, RTRIM(CLBA.BANKACCKEY) AS IG_BANKACCKEY
FROM TITDMGCLNTBANK@DMSTGUSR2DBLINK SRC
LEFT JOIN Jd1dta.PAZDCLPF PAZ
ON SRC.REFNUM = PAZ.ZENTITY
LEFT JOIN Jd1dta.CLBAPF CLBA
ON PAZ.ZIGVALUE = CLBA.CLNTNUM
AND RTRIM(SRC.BANKCD) = RTRIM(SUBSTR(CLBA.BANKKEY,1,4))
AND RTRIM(SRC.BRANCHCD) = RTRIM(SUBSTR(CLBA.BANKKEY,8,10))
AND RTRIM(SRC.CRDTCARD) = RTRIM(CLBA.BANKACCKEY)
WHERE NVL(RTRIM(SRC.BANKACCKEY) , RTRIM(SRC.CRDTCARD)) <> RTRIM(CLBA.BANKACCKEY);

--CLBAPF.MTHTO, CLBAPF.YEARTO
SELECT SRC.REFNUM AS SRC_REFNUM, SRC.CURRTO AS SRC_CURRTO
,PAZ.ZENTITY AS IG_REFNUM, CLBA.MTHTO AS IG_MTHTO, CLBA.YEARTO AS IG_YEARTO
FROM TITDMGCLNTBANK@DMSTGUSR2DBLINK SRC
LEFT JOIN Jd1dta.PAZDCLPF PAZ
ON SRC.REFNUM = PAZ.ZENTITY
LEFT JOIN Jd1dta.CLBAPF CLBA
ON PAZ.ZIGVALUE = CLBA.CLNTNUM
AND RTRIM(SRC.BANKCD) = RTRIM(SUBSTR(CLBA.BANKKEY,1,4))
AND RTRIM(SRC.BRANCHCD) = RTRIM(SUBSTR(CLBA.BANKKEY,8,10))
AND RTRIM(SRC.CRDTCARD) = RTRIM(CLBA.BANKACCKEY)
WHERE (CASE WHEN RTRIM(SRC.CURRTO) <> '99999999' THEN SUBSTR(SRC.CURRTO, 5, 2) 
            WHEN RTRIM(SRC.CURRTO) = '99999999'  THEN '0' END) <> CLBA.MTHTO
OR (CASE WHEN RTRIM(SRC.CURRTO) <> '99999999' THEN SUBSTR(SRC.CURRTO, 3, 2) 
          WHEN RTRIM(SRC.CURRTO) = '99999999' THEN '0' END) <> CLBA.YEARTO;
		  

--CLRRPF.CLNTNUM
SELECT SRC.REFNUM AS SRC_REFNO, PAZ.ZENTITY AS IG_REFNO
FROM TITDMGCLNTBANK@DMSTGUSR2DBLINK SRC
LEFT JOIN Jd1dta.PAZDCLPF PAZ
ON RTRIM(SRC.REFNUM) = RTRIM(PAZ.ZENTITY)
LEFT JOIN Jd1dta.CLRRPF CLRR
ON RTRIM(PAZ.ZIGVALUE) = RTRIM(CLRR.CLNTNUM)
WHERE PAZ.ZIGVALUE <> CLRR.CLNTNUM;

-- Transformation Queries End