--STAGEDBUSR user setup
---Step1: All required DDL Setup

create table  SHI_TITDMGAGENTPJ	As select * from	TITDMGAGENTPJ;
create table  SHI_TITDMGBILL1	As select * from	TITDMGBILL1;
create table  SHI_TITDMGBILL1_PAIDPLAN	As select * from	TITDMGBILL1_PAIDPLAN;
create table  SHI_TITDMGBILL2	As select * from	TITDMGBILL2;
create table  SHI_TITDMGBILL2_PAIDPLAN	As select * from	TITDMGBILL2_PAIDPLAN;
create table  SHI_TITDMGCAMPCDE	As select * from	TITDMGCAMPCDE;
create table  SHI_TITDMGCLNTBANK	As select * from	TITDMGCLNTBANK;
create table  SHI_TITDMGCLNTBANK_FREEPLAN	As select * from	TITDMGCLNTBANK_FREEPLAN;
create table  SHI_TITDMGCLNTCORP	As select * from	TITDMGCLNTCORP;
create table  SHI_TITDMGCLNTPRSN	As select * from	TITDMGCLNTPRSN;
create table  SHI_TITDMGCLNTPRSN_FREEPLAN	As select * from	TITDMGCLNTPRSN_FREEPLAN;
create table  SHI_TITDMGCLTRNHIS	As select * from	TITDMGCLTRNHIS;
create table  SHI_TITDMGCLTRNHIS_FREEPLAN	As select * from	TITDMGCLTRNHIS_FREEPLAN;
create table  SHI_TITDMGCOLRES	As select * from	TITDMGCOLRES;
create table  SHI_TITDMGLETTER	As select * from	TITDMGLETTER;
create table  SHI_TITDMGLETTER_FREEPLAN	As select * from	TITDMGLETTER_FREEPLAN;
create table  SHI_TITDMGMBRINDP1	As select * from	TITDMGMBRINDP1;
create table  SHI_TITDMGMBRINDP1_FREEPLAN	As select * from	TITDMGMBRINDP1_FREEPLAN;
create table  SHI_TITDMGMBRINDP2	As select * from	TITDMGMBRINDP2;
create table  SHI_TITDMGMBRINDP2_FREEPLAN	As select * from	TITDMGMBRINDP2_FREEPLAN;
create table  SHI_TITDMGMBRINDP3	As select * from	TITDMGMBRINDP3;
create table  SHI_TITDMGPOLTRNH	As select * from	TITDMGPOLTRNH;
create table  SHI_TITDMGPOLTRNH_FREEPLAN	As select * from	TITDMGPOLTRNH_FREEPLAN;
create table  SHI_TITDMGREF1	As select * from	TITDMGREF1;
create table  SHI_TITDMGREF2	As select * from	TITDMGREF2;
create table  SHI_TITDMGSALEPLN1	As select * from	TITDMGSALEPLN1;
create table  SHI_TITDMGSALEPLN2	As select * from	TITDMGSALEPLN2;



@C:\D_Drive\Zurich_Product\PA_Data_Migration\integral-CustomerZurichJpnDM\Documentation\DataChange\Oracle\Phase-2\ITR3\Staging_To_IG\Source_Code\STAGINGDB_DDL\DM_STAGE_TABLES.sql;

grant ALL on STAGEDBUSR.TITDMGCLNTBANK to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGAGENTPJ   to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGENDSPCFC  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGCLTRNHIS  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGMBRINDP1  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGLETTER    to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGPOLTRNH   to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGCLNTPRSN  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGMBRINDP3  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGZCSLPF    to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGCAMPCDE   to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGENDCTPF   to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGBILL1     to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGINSSTPL   to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGSALEPLN1  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGCOLRES    to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGMBRINDP2  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGAPIRNO    to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGREF1      to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGBILL2     to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGCLNTCORP  to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGMASPOL    to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGREF2      to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGRNWDT1   to STAGEDBUSR2;
grant ALL on STAGEDBUSR.TITDMGRNWDT2   to STAGEDBUSR2;
grant all on stagedbusr.titdmgcoraddr to STAGEDBUSR2;
