OPTIONS (DIRECT=TRUE)
UNRECOVERABLE
LOAD DATA
REPLACE
INTO TABLE VM1DTA.CLNTQY
FIELDS TERMINATED BY "," ENCLOSED BY '"'
TRAILING NULLCOLS
(
UNIQUE_NUMBER,
CLNTCOY      ,
CLNTNUM      ,
CLRRROLE     ,
SURNAME      ,
GIVNAME      ,
CLTADDR01    ,
CLTADDR02    ,
CLTADDR03    ,
CLTADDR04    ,
CLTADDR05    ,
CLTPCODE     ,
CLTSEX       ,
CLTDOB       
)
