OPTIONS (DIRECT=TRUE)
UNRECOVERABLE
LOAD DATA
REPLACE
INTO TABLE VM1DTA.MV_ZMCIPF_CRDT
FIELDS TERMINATED BY "," ENCLOSED BY '"'
TRAILING NULLCOLS
(
UNIQUE_NUMBER,
CHDRNUM      ,
ZENDCDE      ,
ZENSPCD01    ,
ZENSPCD02    ,
ZCIFCODE     ,
CRDTCARD     ,
BANKACCKEY01
)
