
--  DDL for Table PAZDCHPF
--------------------------------------------------------
  
create table  SHI_TITDMGCLNTBANK_TEMP	As select * from	TITDMGCLNTBANK_TEMP			;
create table  SHI_TITDMGREF1_TEMP	As select * from	TITDMGREF1_TEMP			;
create table  SHI_TITDMGPOLTRNH_TEMP	As select * from	TITDMGPOLTRNH_TEMP			;
create table  SHI_TITDMGMBRINDP1_FREEPLAN_TEMP	As select * from	TITDMGMBRINDP1_FREEPLAN_TEMP			;
create table  SHI_TITDMGMBRINDP1_TEMP	As select * from	TITDMGMBRINDP1_TEMP			;
create table  SHI_TITDMGCLNTBANK_FREEPLAN_TEMP	As select * from	TITDMGCLNTBANK_FREEPLAN_TEMP			;
create table  SHI_TITDMGPOLTRNH_FREE_PLANS_TEMP	As select * from	TITDMGPOLTRNH_FREE_PLANS_TEMP			;
create table  SHI_TITDMGCLNTPRSN_FREEPLAN_TEMP	As select * from	TITDMGCLNTPRSN_FREEPLAN_TEMP			;
create table  SHI_TITDMGCLTRNHIS_TEMP	As select * from	TITDMGCLTRNHIS_TEMP			;
create table  SHI_TITDMGCLTRNHIS_FP_TEMP	As select * from	TITDMGCLTRNHIS_FP_TEMP			;
create table  SHI_TITDMGCLNTPRSN_TEMP	As select * from	TITDMGCLNTPRSN_TEMP			;
create table  SHI_IG_TITDMGPOLTRNH	As select * from	IG_TITDMGPOLTRNH			;


drop table TITDMGCLNTBANK_TEMP;
drop table TITDMGREF1_TEMP;
drop table TITDMGPOLTRNH_TEMP;
drop table TITDMGMBRINDP1_FREEPLAN_TEMP;
drop table TITDMGMBRINDP1_TEMP;
drop table TITDMGCLNTBANK_FREEPLAN_TEMP;
drop table TITDMGPOLTRNH_FREE_PLANS_TEMP;
drop table TITDMGCLNTPRSN_FREEPLAN_TEMP;
drop table TITDMGCLTRNHIS_TEMP;
drop table TITDMGCLTRNHIS_FP_TEMP;
drop table TITDMGCLNTPRSN_TEMP;
drop table IG_TITDMGPOLTRNH;
  
  
  
  Drop table "Jd1dta"."PAZDCHPF" ;
  CREATE TABLE "Jd1dta"."PAZDCHPF" 
   (	"RECIDXCLNTHIS" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ,
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZENTITY" VARCHAR2(30 CHAR), 
	"ZIGVALUE" VARCHAR2(30 CHAR), 
	"EFFDATE" NUMBER(8,0), 
	"ZSEQNO" NUMBER(3,0),
	"ZCLNUNINO"	NUMBER(18,0),
	"ZCLREL" VARCHAR2(2 CHAR),
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table PAZDCLPF
--------------------------------------------------------
  Drop table "Jd1dta"."PAZDCLPF" ;

  CREATE TABLE "Jd1dta"."PAZDCLPF" 
   (	"RECIDXCLIENT" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"PREFIX" VARCHAR2(2 CHAR), 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"ZIGVALUE" VARCHAR2(50 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   )  ;
   CREATE UNIQUE INDEX "Jd1dta"."PAZDCL_UNI_IDX1" ON "Jd1dta"."PAZDCLPF" ("PREFIX", "ZENTITY") ;

--------------------------------------------------------
--  DDL for Table PAZDCRPF
--------------------------------------------------------
  Drop table "Jd1dta"."PAZDCRPF" ;

  CREATE TABLE "Jd1dta"."PAZDCRPF" 
   (	"RECIDXCOLRES" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"ZIGVALUE" VARCHAR2(8 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   ) ;
--  DDL for Table PAZDLTPF
--------------------------------------------------------
  Drop table "Jd1dta"."PAZDLTPF" ;

  CREATE TABLE "Jd1dta"."PAZDLTPF" 
   (	"RECIDXLETTERS" NUMBER(8,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"HLETTYPE" VARCHAR2(8 CHAR), 
	"LREQDATE" NUMBER(8,0), 
	"ZLETVERN" VARCHAR2(3 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table ZDOEPF
--------------------------------------------------------
  Drop table "Jd1dta"."ZDOEPF" ;

  CREATE TABLE "Jd1dta"."ZDOEPF" 
   (	"RECIDXOKEROR" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZREFKEY" VARCHAR2(100 CHAR), 
	"ZFILENME" VARCHAR2(20 CHAR), 
	"EROR01" VARCHAR2(4 CHAR), 
	"ERRMESS01" VARCHAR2(250 CHAR), 
	"ERORFLD01" VARCHAR2(10 CHAR), 
	"FLDVALU01" VARCHAR2(100 CHAR), 
	"ERORPROG01" VARCHAR2(10 CHAR), 
	"EROR02" VARCHAR2(4 CHAR), 
	"ERRMESS02" VARCHAR2(250 CHAR), 
	"ERORFLD02" VARCHAR2(10 CHAR), 
	"FLDVALU02" VARCHAR2(100 CHAR), 
	"ERORPROG02" VARCHAR2(10 CHAR), 
	"EROR03" VARCHAR2(4 CHAR), 
	"ERRMESS03" VARCHAR2(250 CHAR), 
	"ERORFLD03" VARCHAR2(10 CHAR), 
	"FLDVALU03" VARCHAR2(100 CHAR), 
	"ERORPROG03" VARCHAR2(10 CHAR), 
	"EROR04" VARCHAR2(4 CHAR), 
	"ERRMESS04" VARCHAR2(250 CHAR), 
	"ERORFLD04" VARCHAR2(10 CHAR), 
	"FLDVALU04" VARCHAR2(100 CHAR), 
	"ERORPROG04" VARCHAR2(10 CHAR), 
	"EROR05" VARCHAR2(4 CHAR), 
	"ERRMESS05" VARCHAR2(250 CHAR), 
	"ERORFLD05" VARCHAR2(10 CHAR), 
	"FLDVALU05" VARCHAR2(100 CHAR), 
	"ERORPROG05" VARCHAR2(10 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"INDIC" VARCHAR2(1 CHAR)
   )  ;

--------------------------------------------------------
--  DDL for Table PAZDRBPF
--------------------------------------------------------
  Drop table "Jd1dta"."PAZDRBPF" ;

  CREATE TABLE "Jd1dta"."PAZDRBPF" 
   (	"RECIDXBILLING" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"ZIGVALUE" VARCHAR2(9 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR), 
	"PREFIX" VARCHAR2(2 BYTE), 
	"PRBILFDT" NUMBER(8,0), 
	"PRBILTDT" NUMBER(8,0), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR)
   ) ;
  
   CREATE INDEX "Jd1dta"."DM_PAZDRBPF" ON "Jd1dta"."PAZDRBPF" ("CHDRNUM", "ZENTITY", "PRBILFDT") ;
--------------------------------------------------------
--  DDL for Table PAZDRFPF
--------------------------------------------------------
  Drop table "Jd1dta"."PAZDRFPF" ;

  CREATE TABLE "Jd1dta"."PAZDRFPF" 
   (	"RECIDXBILLING" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"ZIGVALUE" VARCHAR2(8 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR), 
	"ZREFMTCD" VARCHAR2(8 CHAR), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table PAZDROPF
--------------------------------------------------------
  Drop table "Jd1dta"."PAZDROPF" ;

  CREATE TABLE "Jd1dta"."PAZDROPF" 
   (	"RECIDXOTHERS" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"PREFIX" VARCHAR2(2 CHAR), 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"ZIGVALUE" VARCHAR2(50 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   )  ;
--------------------------------------------------------
--  DDL for Table PAZDRPPF
--------------------------------------------------------
  Drop table "Jd1dta"."PAZDRPPF" ;

 CREATE TABLE "Jd1dta"."PAZDRPPF" 
   (	"RECIDXPOLICY" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"CHDRNUM" VARCHAR2(11 CHAR), 
    "ZINSROLE"	VARCHAR2(1 CHAR),
	"PREFIX" VARCHAR2(2 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR) , 
	"POLNUM" VARCHAR2(8 BYTE) 
   );


--------------------------------------------------------
--  DDL for Table CONV_POL_HIST
--------------------------------------------------------
  Drop table "Jd1dta"."CONV_POL_HIST" ;

  CREATE TABLE "Jd1dta"."CONV_POL_HIST" 
   (	"PH_CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"GC_CHDRNUM" CHAR(8 CHAR), 
	"ZPRVCHDR" VARCHAR2(8 CHAR)
   )  ;
--------------------------------------------------------
--  DDL for Table MB01_POLHIST_RANGE
--------------------------------------------------------
  Drop table "Jd1dta"."MB01_POLHIST_RANGE" ;

  CREATE TABLE "Jd1dta"."MB01_POLHIST_RANGE" 
   (	"CHDRNUM_FROM" VARCHAR2(8 CHAR), 
	"CHDRNUM_TO" VARCHAR2(8 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table IG_TITDMGPOLTRNH
--------------------------------------------------------
  Drop table "Jd1dta"."IG_TITDMGPOLTRNH" ;

  CREATE TABLE "Jd1dta"."IG_TITDMGPOLTRNH" 
   (	"RECIDXPHIST" NUMBER(*,0), 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"ZSEQNO" VARCHAR2(3 CHAR), 
	"EFFDATE" NUMBER(8,0), 
	"ZALTREGDAT" NUMBER(8,0), 
	"ZALTRCDE01" VARCHAR2(4 CHAR), 
	"ZINHDSCLM" VARCHAR2(1 CHAR), 
	"ZUWREJFLG" VARCHAR2(1 CHAR), 
	"ZSTOPBPJ" VARCHAR2(1 CHAR), 
	"ZTRXSTAT" VARCHAR2(2 CHAR), 
	"ZSTATRESN" VARCHAR2(4 CHAR), 
	"ZACLSDAT" NUMBER(8,0), 
	"APPRDTE" VARCHAR2(8 CHAR), 
	"ZPDATATXDTE" NUMBER(8,0), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR), 
	"ZREFUNDAM" NUMBER(17,2), 
	"ZPAYINREQ" VARCHAR2(1 CHAR), 
	"CRDTCARD" VARCHAR2(16 CHAR), 
	"PREAUTNO" VARCHAR2(8 CHAR), 
	"BNKACCKEY01" VARCHAR2(20 CHAR), 
	"ZENSPCD01" VARCHAR2(70 CHAR), 
	"ZENSPCD02" VARCHAR2(70 CHAR), 
	"ZCIFCODE" VARCHAR2(15 CHAR), 
	"ZPGPFRDT" NUMBER(8,0), 
	"ZPGPTODT" NUMBER(8,0), 
	"ZDDREQNO" VARCHAR2(8 CHAR)
   ) ;

  
--------------------------------------------------------
--  Constraints for Table PAZDCLPF
--------------------------------------------------------

 -- ALTER TABLE "Jd1dta"."PAZDCLPF" ADD CONSTRAINT "PK_PAZDCLPF" PRIMARY KEY ("RECIDXCLIENT");
 -- ALTER TABLE "Jd1dta"."PAZDCLPF" MODIFY ("RECSTATUS" NOT NULL ENABLE);
--------------------------------------------------------
--------------------------------------------------------


--------------------------------------------------------
--  Constraints for Table CONV_POL_HIST
--------------------------------------------------------

 -- ALTER TABLE "Jd1dta"."CONV_POL_HIST" MODIFY ("PH_CHDRNUM" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table IG_DM_MASTERPOL
--------------------------------------------------------
  Drop table "Jd1dta"."IG_DM_MASTERPOL" ;

  CREATE TABLE "Jd1dta"."IG_DM_MASTERPOL" 
   (	"CHDRNUM" CHAR(8 CHAR), 
	"ZPLANCLS" CHAR(2 CHAR), 
	"ZCOLMCLS" CHAR(2 CHAR), 
	"POLANV" NUMBER(8,0), 
	"ZAGPTNUM" NCHAR(8),
	"ZGRPCLS" CHAR(8)
   )  ;
   
   
---------------------------------------------------------------
--   DDL for table DMBARGSPF
--------------------------------------------------------------------
  Drop table "Jd1dta"."DMBARGSPF" ;
   
  CREATE TABLE "Jd1dta"."DMBARGSPF" 
   (	"UNIQUE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE NOT NULL ENABLE, 
	"SCHEDULE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"FSUCOCOMPANY" VARCHAR2(2 BYTE), 
	"USRPRF" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BRANCH" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"TRANSCODE" VARCHAR2(4 BYTE), 
	"VRCMTIME" NUMBER, 
	"VRCMUSER" NUMBER, 
	"TRDT1" NUMBER, 
	"ACCTYEAR" NUMBER, 
	"ACCTMONTH" NUMBER, 
	"VRCMTERMID" VARCHAR2(50 BYTE), 
	"USER_T"  NUMBER(6)    ,
	"ARRAY_SIZE" NUMBER(6)    ,
	"CHUNK_SIZE" NUMBER NOT NULL ENABLE, 
	"DEGREE_PARALLEL" NUMBER NOT NULL ENABLE
   ) ;

  CREATE UNIQUE INDEX "Jd1dta"."DMBARGS_I1" ON "Jd1dta"."DMBARGSPF" ("SCHEDULE_NAME") ;
  
  ---------------------------------------------------------------
--   DDL for table DMBERPF
--------------------------------------------------------------------   
  Drop table "Jd1dta"."DMBERPF" ;

CREATE TABLE "Jd1dta"."DMBERPF" 
   (	
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
   "SCHEDULE_NAME" VARCHAR2(50 char) NOT NULL ENABLE,
    "JOB_NUM" VARCHAR2(6 CHAR),    
	"ERROR_CODE" NUMBER NOT NULL ENABLE, 
	"ERROR_TEXT" VARCHAR2(1000 char) NOT NULL ENABLE,
	"DATIME" TIMESTAMP (6)
   );

---------------------------------------------------------------
--   DDL for table DMBMONPF
--------------------------------------------------------------------   
--  
--'01' Aborted
--'90' Completed
--'50' Available
--'10' Runing


  Drop table "Jd1dta"."DMBMONPF" ;

  CREATE TABLE "Jd1dta"."DMBMONPF" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"BATCH_NAME" VARCHAR2(100 CHAR), 
	"JOB_NUM" VARCHAR2(6 CHAR), 
	"ZPRVALDYN" VARCHAR2(1 CHAR),
	"START_TIME" NUMBER, 
	"END_TIME" NUMBER, 
	"TOTAL_TIME" NUMBER, 
	 "SCHD_STATUS" CHAR(2 CHAR) default 50,
     "USRPRF"     	CHAR(10 CHAR),
	"DATIME" TIMESTAMP (6), 
	"REMARKS" VARCHAR2(500 CHAR),
	"START_TIMESTAMP" VARCHAR2(200 BYTE), 
	"END_TIMESTAMP" VARCHAR2(200 BYTE)
   );

  /
CREATE OR REPLACE TRIGGER Jd1dta.DMTRBMONPF
before INSERT OR UPDATE OF END_TIME ON DMBMONPF  for each row
BEGIN
  :New.TOTAL_TIME := (:New.END_TIME - :OLD.Start_Time)/100;
END;
/

ALTER TRIGGER "Jd1dta"."DMTRBMONPF" ENABLE;
/
create unique index UN_SCHNAM_NUM on DMBMONPF (JOB_NUM, BATCH_NAME);
/
---------------------------------------------------------------
--   DDL for table DMDEFVALPF
--------------------------------------------------------------------  
  Drop table "Jd1dta"."DMDEFVALPF" ;
 
  CREATE TABLE "Jd1dta"."DMDEFVALPF" 
   (	"MODULEID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"MODULEDESC" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"KEYCOL" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"VALCOL" VARCHAR2(100 CHAR)
   ) ;

    CREATE UNIQUE INDEX "Jd1dta"."UNI_DEFVAL_I" ON "Jd1dta"."DMDEFVALPF" ("MODULEID", "KEYCOL") ;
---------------------------------------------------------------
--   DDL for table DMPRFXPF
--------------------------------------------------------------------   
  Drop table "Jd1dta"."DMPRFXPF" ;

CREATE TABLE "Jd1dta"."DMPRFXPF" 
   (          
    
     "MODULEID" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
      "MODPREFIX" VARCHAR2(2 CHAR) NOT NULL ENABLE,
              "MODULEDESC" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) ;
   
   CREATE UNIQUE INDEX "Jd1dta"."UNI_PRFX_I" ON "Jd1dta"."DMPRFXPF" ("MODULEID") ;




---------------------------------------------------------------
--   DDL for table DMPVALPF
--------------------------------------------------------------------   
  Drop table "Jd1dta"."DMPVALPF" ;

  CREATE TABLE "Jd1dta"."DMPVALPF" 
   (	
	"UNIQUE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"SCHEDULE_NAME" VARCHAR2(100 CHAR), 
	"SCHEDULE_NUM" VARCHAR2(4 CHAR), 
	"REFKEY" VARCHAR2(100 CHAR), 
	"REFTAB" VARCHAR2(20 CHAR), 
	"ERRMESS01" VARCHAR2(500 CHAR), 
	"ERORFLD" VARCHAR2(10 CHAR), 
	"FLDVALUE" VARCHAR2(100 CHAR), 
	"VALDNO" VARCHAR2(100 CHAR), 
	"DATIME" TIMESTAMP (6)
   );
   
   
 

----------------------------
--DM stage table replica in IG for parallel use
drop table Jd1dta.DMIGTITDMGAGENTPJ;
create table  Jd1dta.DMIGTITDMGAGENTPJ as (select * from stagedbusr.TITDMGAGENTPJ@DMSTAGEDBLINK where 1=2);


drop table Jd1dta.DMIGTITDMGCLTRNHIS;
create table  Jd1dta.DMIGTITDMGCLTRNHIS as (select * from stagedbusr.TITDMGCLTRNHIS@DMSTAGEDBLINK where 1=2);

ALTER TABLE Jd1dta.DMIGTITDMGCLTRNHIS 
ADD REFNUMCHUNK NUMBER(*,0) ;

CREATE INDEX "Jd1dta"."NOUNI_CL_IDX1" ON "Jd1dta"."DMIGTITDMGCLTRNHIS" ("REFNUMCHUNK");
CREATE INDEX "Jd1dta"."NOUNI_CL_IDX2" ON "Jd1dta"."DMIGTITDMGCLTRNHIS" ("REFNUM");



drop table Jd1dta.DMIGTITDMGCLNTBANK;
CREATE TABLE "Jd1dta"."DMIGTITDMGCLNTBANK" 
   (	"RECIDXCLBK" NUMBER(*,0) NOT NULL ENABLE, 
	"REFNUM" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"SEQNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"CURRTO" NUMBER(8,0), 
	"BANKCD" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"BRANCHCD" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"FACTHOUS" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"BANKACCKEY" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CRDTCARD" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"BANKACCDSC" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"BNKACTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"TRANSHIST" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"BANKKEY" VARCHAR2(10 CHAR), 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"ZIGVALUE" VARCHAR2(50 CHAR), 
	"CLB_CLNTNUM" VARCHAR2(50 CHAR)
   ) NOCOMPRESS NOLOGGING;

   

drop table Jd1dta.DMIGTITDMGMBRINDP1;
create table Jd1dta.DMIGTITDMGMBRINDP1 as (select * from stagedbusr.titdmgmbrindp1@DMSTAGEDBLINK where 1=2);

ALTER TABLE Jd1dta.DMIGTITDMGMBRINDP1 
ADD REFNUMCHUNK NUMBER(*,0) ;

ALTER TABLE DMIGTITDMGMBRINDP1 
ADD POLNUM varchar2(8);

CREATE INDEX "Jd1dta"."NOUNI_IDX1" ON "Jd1dta"."DMIGTITDMGMBRINDP1" ("REFNUMCHUNK");
CREATE INDEX "Jd1dta"."NOUNI_IDX2" ON "Jd1dta"."DMIGTITDMGMBRINDP1" ("REFNUM");

--Billing Instalment Start--
drop table Jd1dta.DMIGTITDMGBILL1;
create table Jd1dta.DMIGTITDMGBILL1 as (select * from stagedbusr.TITDMGBILL1@DMSTAGEDBLINK where 1=2);

ALTER TABLE Jd1dta.DMIGTITDMGBILL1 
ADD REFNUMCHUNK NUMBER(*,0) ;

CREATE INDEX "Jd1dta"."DMIGTITDMGBILL1_IDX1" ON "Jd1dta"."DMIGTITDMGBILL1" ("REFNUMCHUNK");

drop table Jd1dta.DMIGTITDMGBILL2;
create table Jd1dta.DMIGTITDMGBILL2 as (select * from stagedbusr.TITDMGBILL2@DMSTAGEDBLINK where 1=2);

CREATE INDEX "Jd1dta"."DMIGTITDMGBILL2_IDX1" ON "Jd1dta"."DMIGTITDMGBILL2" ("CHDRNUM", "TRREFNUM", "PRBILFDT", "PRODTYP", "MBRNO", "DPNTNO");

--- Below index to improve performance ZJNPG-6619
DROP INDEX Jd1dta.bill_chr_bilto_po;
create index Jd1dta.bill_chr_bilto_po on dmigtitdmgbill1 (CHDRNUM,PRBILTDT,premout);

--Billing Instalment End--

   
----------------------------------
--ZDMBKPZCLN
--------------------------------------
  Drop table "Jd1dta"."ZDMBKPZCLN" ;

 CREATE TABLE "Jd1dta"."ZDMBKPZCLN" 
   (	"CLNTNUM" CHAR(8 CHAR), 
	"EFFDATE" NUMBER(8,0)
   )  ;

  CREATE UNIQUE INDEX "Jd1dta"."UNI_ZCLNUM" ON "Jd1dta"."ZDMBKPZCLN" ("CLNTNUM");   
  
  ---------------------------------
--ZDMBKPCLNT
--------------------------------------
  Drop table "Jd1dta"."ZDMBKPCLNT" ;

 CREATE TABLE "Jd1dta"."ZDMBKPCLNT" 
   (	"CLNTNUM" CHAR(8 CHAR), 
	"SRDATE" NUMBER(8,0)
   )  ;

  CREATE UNIQUE INDEX "Jd1dta"."UNI_CLNUM" ON "Jd1dta"."ZDMBKPCLNT" ("CLNTNUM");   
  
 ---------------------------------
--ZDMBKPAUDCLNT
--------------------------------------
  Drop table "Jd1dta"."ZDMBKPAUDCLNT" ;

 CREATE TABLE "Jd1dta"."ZDMBKPAUDCLNT" 
   (	"OLDCLNTNUM" CHAR(8 CHAR), 
	"NEWSRDATE" NUMBER(8,0)
   )  ;

  CREATE UNIQUE INDEX "Jd1dta"."UNI_AUDCLNUM" ON "Jd1dta"."ZDMBKPAUDCLNT" ("OLDCLNTNUM");   
 
 ----------------------------------
--ZDMBKPZTRA
--------------------------------------
DROP TABLE "Jd1dta"."ZDMBKPZTRA" ;
 CREATE TABLE "Jd1dta"."ZDMBKPZTRA" 
   (
	"ZTRA_UNIQUE_NUMBER"  NUMBER,
    "UNIQUE_NUMBER_01"  NUMBER
   )  ;

  CREATE UNIQUE INDEX "Jd1dta"."UNI_DMZTRA" ON "Jd1dta"."ZDMBKPZTRA" ("ZTRA_UNIQUE_NUMBER");   
  
  ----------------------------------
--ZDMBKPZINS
--------------------------------------
 DROP TABLE "Jd1dta"."ZDMBKPZINS"; 

 CREATE TABLE "Jd1dta"."ZDMBKPZINS" 
   (	
    "ZINS_UNIQUE_NUMBER"  NUMBER,
    "UNIQUE_NUMBER_01"  NUMBER
   )  ;

  CREATE UNIQUE INDEX "Jd1dta"."UNI_DMZINS" ON "Jd1dta"."ZDMBKPZINS" ("ZINS_UNIQUE_NUMBER");   
----------------------------------
--DMIGTITDMGCOLRES
--------------------------------------
drop table Jd1dta.DMIGTITDMGCOLRES;
  CREATE TABLE "Jd1dta"."DMIGTITDMGCOLRES" 
   (	"RECIDXCAMP" NUMBER(*,0) NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"TRREFNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"TFRDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"DSHCDE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PRBILFDT" NUMBER(8,0) NOT NULL ENABLE, 
	"CHUNKSNUM" NUMBER(*,0),
    "PAZ_REC" VARCHAR2(8 CHAR)
   ) 
 NOCOMPRESS NOLOGGING;

 ----------------------------------
--DMIGTITDMGMASPOL
--------------------------------------
drop table Jd1dta.DMIGTITDMGMASPOL;

CREATE TABLE "Jd1dta"."DMIGTITDMGMASPOL"
(
"RECIDXMPMSPOL" NUMBER(*,0) ,
"CHDRNUM" CHAR(11 CHAR) ,
"CNTTYPE" CHAR(3 CHAR) ,
"STATCODE" CHAR(2 CHAR) ,
"ZAGPTNUM" VARCHAR2(8 BYTE) ,
"CCDATE" NUMBER(8,0) ,
"CRDATE" NUMBER(8,0) ,
"RPTFPST" VARCHAR2(1 CHAR) ,
"ZENDCDE" VARCHAR2(10 CHAR) ,
"RRA2IG" VARCHAR2(40 CHAR) ,
"B8TJIG" VARCHAR2(30 CHAR) ,
"ZBLNKPOL" VARCHAR2(1 CHAR) ,
"B8O9NB" NUMBER(6,0) ,
"B8GPST" CHAR(1 BYTE) ,
"B8GOST" CHAR(1 BYTE) ,
"ZNBALTPR" CHAR(8 CHAR) ,
"CANCELDT" NUMBER(8,0) ,
"EFFDATE" NUMBER(8,0) ,
"PNDATE" NUMBER(8,0) ,
"OCCDATE" NUMBER(8,0) ,
"INSENDTE" NUMBER(8,0) ,
"ZPENDDT" NUMBER(8,0) ,
"ZCCDE" VARCHAR2(15 CHAR) ,
"ZCONSGNM" VARCHAR2(60 CHAR) ,
"ZBLADCD" VARCHAR2(15 CHAR) ,
"CLNTNUM" CHAR(12 CHAR) ,
"IND" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  

 ----------------------------------
--PAZDMPPF
--------------------------------------
drop table Jd1dta.PAZDMPPF;
CREATE TABLE "Jd1dta"."PAZDMPPF" 
   (	"RECIDXCLIENT" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"PREFIX" VARCHAR2(2 CHAR), 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"ZIGVALUE" VARCHAR2(50 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 ----------------------------------
--DMIGTITDMGCLNTCORP
--------------------------------------
  drop table Jd1dta.DMIGTITDMGCLNTCORP;

  
  CREATE TABLE "Jd1dta"."DMIGTITDMGCLNTCORP" 
   (	"RECIDXCLCORP" NUMBER(*,0) NOT NULL ENABLE, 
	"CLTTYPE" VARCHAR2(1 CHAR), 
	"CLTADDR01" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CLTADDR02" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CLTADDR03" VARCHAR2(30 CHAR), 
	"CLTADDR04" VARCHAR2(30 CHAR), 
	"ZKANADDR01" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ZKANADDR02" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ZKANADDR03" VARCHAR2(30 CHAR), 
	"ZKANADDR04" VARCHAR2(30 CHAR), 
	"CLTPCODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CLTPHONE01" VARCHAR2(16 CHAR), 
	"CLTPHONE02" VARCHAR2(16 CHAR), 
	"CLTDOBX" NUMBER(8,0), 
	"CLTSTAT" VARCHAR2(2 CHAR), 
	"FAXNO" VARCHAR2(16 CHAR), 
	"LSURNAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ZKANASNM" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CLNTKEY" VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	"AGNTNUM" CHAR(8 BYTE), 
	"MPLNUM" CHAR(8 BYTE), 
	"CLNTNUM" CHAR(8 BYTE), 
	"IND" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  
 ----------------------------------
--DMIGTITDMGLETTER
--------------------------------------

Drop table Jd1dta.DMIGTITDMGLETTER;
CREATE TABLE  Jd1dta.DMIGTITDMGLETTER AS SELECT * FROM TITDMGLETTER@DMSTAGEDBLINK where 1=2;

ALTER TABLE Jd1dta.DMIGTITDMGLETTER 
ADD REFNUMCHUNK NUMBER(*,0) ;

CREATE INDEX "Jd1dta"."NOUNI_IDX1_LET" ON "Jd1dta"."DMIGTITDMGLETTER" ("REFNUMCHUNK");

-----------------------------
--Creating all ZDOE0000 table
-------
create table Jd1dta.ZDOEAG0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOEBL0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOECM0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOECB0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOECH0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOECR0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOECC0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOEIN0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOELT0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOEMB0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOECP0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOEPD0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOEPH0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOERF0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOESP0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOENY0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOEMP0000 as (select * from Jd1dta.zdoepf);
create table Jd1dta.ZDOERD0000 as (select * from Jd1dta.zdoepf);


--
--------------------------------------
--PAZDPDPF
--------------------------------------
  drop table Jd1dta.PAZDPDPF;

CREATE TABLE "Jd1dta"."PAZDPDPF" 
   (	"RECIDXPOLDSH" NUMBER(38,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"OLDCHDRNUM" VARCHAR2(8 CHAR), 
	"NEWCHDRNUM" VARCHAR2(8 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR),
  "USRPRF" VARCHAR2(10 CHAR),
  "DATIME" TIMESTAMP (6)
   );
 
--------------------------------------
--DMIGTITDMGMBRINDP3
-------------------------------------- 
   
drop table Jd1dta.DMIGTITDMGMBRINDP3;
create table  Jd1dta.DMIGTITDMGMBRINDP3 as (select * from stagedbusr.TITDMGMBRINDP3@DMSTAGEDBLINK where 1=2);


--------------------------------------
--DMIGTITDMGREF1
-------------------------------------- 
drop table Jd1dta.DMIGTITDMGREF1;
create table Jd1dta.DMIGTITDMGREF1 as (select * from stagedbusr.TITDMGREF1@DMSTAGEDBLINK where 1=2);

ALTER TABLE Jd1dta.DMIGTITDMGREF1 
ADD REFNUMCHUNK NUMBER(*,0) ;

CREATE INDEX "Jd1dta"."DMIGTITDMGREF1_IDX1" ON "Jd1dta"."DMIGTITDMGREF1" ("REFNUMCHUNK");

--------------------------------------
--DMIGTITDMGREF2
-------------------------------------- 
drop table Jd1dta.DMIGTITDMGREF2;
create table Jd1dta.DMIGTITDMGREF2 as (select * from stagedbusr.TITDMGREF2@DMSTAGEDBLINK where 1=2);


--------------------------------------
--RECON_MASTER
-------------------------------------- 
drop table recon_master cascade constraints purge;

CREATE TABLE Jd1dta.RECON_MASTER (
    SCHEDULE_ID NUMBER(5) NOT NULL,
    RECON_QUERY_ID VARCHAR2(20) NOT NULL,
    MODULE_NAME VARCHAR2(50),
    GROUP_CLAUSE VARCHAR2(255 CHAR),
    WHERE_CLAUSE VARCHAR2(255 CHAR),
    VALIDATION_TYPE VARCHAR2(255 CHAR),
    SOURCE_VALUE NUMBER NOT NULL,
    STAGING_VALUE NUMBER NOT NULL,
    IG_VALUE NUMBER NOT NULL,
    STATUS VARCHAR2(5),
    RUNDATE TIMESTAMP DEFAULT SYSDATE,
	QUERY_DESC VARCHAR2(500 CHAR)
);

--------------------------------------------------------
--  DDL for Table PAZDPTPF
--------------------------------------------------------
  drop table Jd1dta.PAZDPTPF;

  CREATE TABLE "Jd1dta"."PAZDPTPF" 
   (	"RECIDXPOLTRNH" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"ZSEQNO" VARCHAR2(3 CHAR),  
	"TRANNO" NUMBER(5,0), 
	"EFFDATE" NUMBER(8), 
	"MBRNO" VARCHAR2(6 CHAR), 
	"ZINSROLE" VARCHAR2(1 CHAR),
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   );	

--------------------------------------------------------
--  DDL for Table PAZDPCPF
--------------------------------------------------------
  drop table Jd1dta.PAZDPCPF;

  CREATE TABLE "Jd1dta"."PAZDPCPF" 
   (	"RECIDXMBRINDP2" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"MBRNO" VARCHAR2(6 CHAR), 
	"DPNTNO" VARCHAR2(2 CHAR),
	"PRODTYP" VARCHAR2(4 CHAR),
	"EFFDATE" NUMBER(8),
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   ) ;	  

--------------------------------------------------------
--  DDL for Table PAZDRNPF
--------------------------------------------------------
  drop table Jd1dta.PAZDRNPF;

  CREATE TABLE "Jd1dta"."PAZDRNPF" 
   (	"RECIDXAPIRNO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RECSTATUS" VARCHAR2(10 CHAR) DEFAULT 'New', 
	"ZENTITY" VARCHAR2(50 CHAR), 
	"MBRNO" VARCHAR2(6 CHAR), 
	"ZINSTYPE" VARCHAR2(3 CHAR),
	"ZAPIRNO" VARCHAR2(3 CHAR),
	"FULLKANJINAME" VARCHAR2(120 CHAR),
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   );	   

--------------------------------------------------------
--  DDL for Table DM_TEMP_POLHIST
--------------------------------------------------------

DROP TABLE Jd1dta.DM_TEMP_POLHIST;
 CREATE TABLE "Jd1dta"."DM_TEMP_POLHIST" 
   (	"RECIDXPHIST" NUMBER(*,0) NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZSEQNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"CLIENT_CATEGORY" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"CLTRELN" VARCHAR2(2 CHAR), 
	"ZINSROLE" VARCHAR2(1 CHAR), 
	"CLIENTNO" VARCHAR2(10 CHAR), 
	"ZALTREGDAT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZALTRCDE01" VARCHAR2(4 CHAR), 
	"ZINHDSCLM" VARCHAR2(1 CHAR), 
	"ZUWREJFLG" VARCHAR2(1 CHAR), 
	"ZSTOPBPJ" VARCHAR2(1 CHAR), 
	"ZTRXSTAT" VARCHAR2(2 CHAR), 
	"ZSTATRESN" VARCHAR2(4 CHAR), 
	"ZACLSDAT" NUMBER(8,0), 
	"APPRDTE" NUMBER(8,0), 
	"ZPDATATXDTE" NUMBER(8,0), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR), 
	"ZREFUNDAM" NUMBER(17,2), 
	"ZPAYINREQ" VARCHAR2(1 CHAR), 
	"CRDTCARD" VARCHAR2(16 CHAR), 
	"PREAUTNO" VARCHAR2(8 CHAR), 
	"BNKACCKEY01" VARCHAR2(20 CHAR), 
	"ZENSPCD01" VARCHAR2(70 CHAR), 
	"ZENSPCD02" VARCHAR2(70 CHAR), 
	"ZCIFCODE" VARCHAR2(15 CHAR), 
	"ZDDREQNO" VARCHAR2(8 CHAR), 
	"ZWORKPLCE2" VARCHAR2(25 CHAR), 
	"BANKACCDSC01" VARCHAR2(30 CHAR), 
	"BANKKEY" VARCHAR2(10 CHAR), 
	"BNKACTYP01" VARCHAR2(4 CHAR), 
	"CURRTO" NUMBER(8,0), 
	"B1_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B2_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B3_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B4_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B5_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B1_CLTADDR01" VARCHAR2(60 CHAR), 
	"B2_CLTADDR01" VARCHAR2(60 CHAR), 
	"B3_CLTADDR01" VARCHAR2(60 CHAR), 
	"B4_CLTADDR01" VARCHAR2(60 CHAR), 
	"B5_CLTADDR01" VARCHAR2(60 CHAR), 
	"B1_BNYPC" NUMBER(5,2), 
	"B2_BNYPC" NUMBER(5,2), 
	"B3_BNYPC" NUMBER(5,2), 
	"B4_BNYPC" NUMBER(5,2), 
	"B5_BNYPC" NUMBER(5,2), 
	"B1_BNYRLN" VARCHAR2(8 CHAR), 
	"B2_BNYRLN" VARCHAR2(8 CHAR), 
	"B3_BNYRLN" VARCHAR2(8 CHAR), 
	"B4_BNYRLN" VARCHAR2(8 CHAR), 
	"B5_BNYRLN" VARCHAR2(8 CHAR), 
	"ZSOLCTFLG" VARCHAR2(1 CHAR), 
	"ZPLANCDE" VARCHAR2(30 CHAR), 
	"ZCMPCODE" VARCHAR2(6 CHAR), 
	"ZCPNSCDE" VARCHAR2(6 CHAR), 
	"ZSALECHNL" VARCHAR2(2 CHAR), 
	"TRANCDE" VARCHAR2(4 CHAR), 
	"TRANNO" NUMBER(5,0) NOT NULL ENABLE, 
	"MINTRANNO" NUMBER(5,0) NOT NULL ENABLE, 
	"BTDATE" NUMBER(8,0) , 
	"INTREFUND" NUMBER(17,2), 
	"RECCHUNKSNUM" NUMBER(*,0) NOT NULL ENABLE, 
	"CCDATE" NUMBER(8,0), 
	"CRDATE" NUMBER(8,0), 
	"ZPOLPERD" NUMBER(38,0), 
	"AGNTNUM" CHAR(8 CHAR), 
	"STATCODE" CHAR(2 CHAR), 
	"COWNNUM" CHAR(8 CHAR), 
	"TRANLUSED" NUMBER(5,0), 
	"BTDATE_GCHD" NUMBER(8,0), 
	"EFFDCLDT" NUMBER(8,0), 
	"OCCDATE" NUMBER(8,0), 
	"UNIQDATE" NUMBER(8,0), 
	"MPLNUM" CHAR(8 CHAR),
	"ZCPMCPNCDE" VARCHAR2(6 CHAR),
	"ZCPMPLANCD" VARCHAR2(30 CHAR),
	"ZTRGTFLG" VARCHAR2(1 CHAR), 
	"ZENDCDE" VARCHAR2(20 CHAR), 
	"ZPGPFRDT" NUMBER(8,0), 
	"ZPGPTODT" NUMBER(8,0), 
	"ZPOLTDATE" NUMBER(8,0), 
	"ZPLANCLS" CHAR(2 CHAR), 
	"CLNTNUM" VARCHAR2(50 CHAR), 
	"ZBNKFLAG" CHAR(1 CHAR), 
	"ZCCFLAG" CHAR(1 CHAR), 
	"ZENDSCID" VARCHAR2(8 CHAR), 
	"ZSLPTYP" VARCHAR2(1 CHAR),
    	"SEQNUMB"	NUMBER(3,0),
	"ZRCALTTY" VARCHAR2(4 CHAR),  
	CONSTRAINT "PK_DM_TEMP_POLHIST" PRIMARY KEY ("CHDRNUM", "ZSEQNO", "EFFDATE", "MBRNO")
   ) NOCOMPRESS NOLOGGING;
   CREATE INDEX "Jd1dta"."INDX_DM_TEMP_POLHIST" ON "Jd1dta"."DM_TEMP_POLHIST" ("CHDRNUM", "MBRNO", "TRANNO"); 
--------------------------------------------------------
--  DDL for Table DMIGTITDMGPOLTRNH
--------------------------------------------------------
DROP TABLE Jd1dta.DMIGTITDMGPOLTRNH;
  CREATE TABLE "Jd1dta"."DMIGTITDMGPOLTRNH" 
   (	"RECIDXPHIST" NUMBER(*,0) NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZSEQNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"CLIENT_CATEGORY" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"CLTRELN" VARCHAR2(2 CHAR), 
	"ZINSROLE" VARCHAR2(1 CHAR), 
	"CLIENTNO" VARCHAR2(10 CHAR), 
	"ZALTREGDAT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZALTRCDE01" VARCHAR2(4 CHAR), 
	"ZINHDSCLM" VARCHAR2(1 CHAR), 
	"ZUWREJFLG" VARCHAR2(1 CHAR), 
	"ZSTOPBPJ" VARCHAR2(1 CHAR), 
	"ZTRXSTAT" VARCHAR2(2 CHAR), 
	"ZSTATRESN" VARCHAR2(4 CHAR), 
	"ZACLSDAT" NUMBER(8,0), 
	"APPRDTE" NUMBER(8,0), 
	"ZPDATATXDTE" NUMBER(8,0), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR), 
	"ZREFUNDAM" NUMBER(17,2), 
	"ZPAYINREQ" VARCHAR2(1 CHAR), 
	"CRDTCARD" VARCHAR2(16 CHAR), 
	"PREAUTNO" VARCHAR2(8 CHAR), 
	"BNKACCKEY01" VARCHAR2(20 CHAR), 
	"ZENSPCD01" VARCHAR2(70 CHAR), 
	"ZENSPCD02" VARCHAR2(70 CHAR), 
	"ZCIFCODE" VARCHAR2(15 CHAR), 
	"ZDDREQNO" VARCHAR2(8 CHAR), 
	"ZWORKPLCE2" VARCHAR2(25 CHAR), 
	"BANKACCDSC01" VARCHAR2(30 CHAR), 
	"BANKKEY" VARCHAR2(10 CHAR), 
	"BNKACTYP01" VARCHAR2(4 CHAR), 
	"CURRTO" NUMBER(8,0), 
	"B1_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B2_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B3_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B4_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B5_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B1_CLTADDR01" VARCHAR2(60 CHAR), 
	"B2_CLTADDR01" VARCHAR2(60 CHAR), 
	"B3_CLTADDR01" VARCHAR2(60 CHAR), 
	"B4_CLTADDR01" VARCHAR2(60 CHAR), 
	"B5_CLTADDR01" VARCHAR2(60 CHAR), 
	"B1_BNYPC" NUMBER(5,2), 
	"B2_BNYPC" NUMBER(5,2), 
	"B3_BNYPC" NUMBER(5,2), 
	"B4_BNYPC" NUMBER(5,2), 
	"B5_BNYPC" NUMBER(5,2), 
	"B1_BNYRLN" VARCHAR2(8 CHAR), 
	"B2_BNYRLN" VARCHAR2(8 CHAR), 
	"B3_BNYRLN" VARCHAR2(8 CHAR), 
	"B4_BNYRLN" VARCHAR2(8 CHAR), 
	"B5_BNYRLN" VARCHAR2(8 CHAR), 
	"ZSOLCTFLG" VARCHAR2(1 CHAR), 
	"ZPLANCDE" VARCHAR2(30 CHAR), 
	"ZCMPCODE" VARCHAR2(6 CHAR), 
	"ZCPNSCDE" VARCHAR2(6 CHAR), 
	"ZSALECHNL" VARCHAR2(2 CHAR), 
	"TRANCDE" VARCHAR2(4 CHAR), 
	"TRANNO" NUMBER(5,0) NOT NULL ENABLE, 
	"MINTRANNO" NUMBER(5,0) NOT NULL ENABLE, 
	"BTDATE" NUMBER(8,0), 
	"INTREFUND" NUMBER(17,2), 
	"RECCHUNKSNUM" NUMBER(*,0) NOT NULL ENABLE, 
	"CCDATE" NUMBER(8,0), 
	"CRDATE" NUMBER(8,0), 
	"ZPOLPERD" NUMBER(38,0), 
	"AGNTNUM" CHAR(8 CHAR), 
	"STATCODE" CHAR(2 CHAR), 
	"COWNNUM" CHAR(8 CHAR), 
	"TRANLUSED" NUMBER(5,0), 
	"BTDATE_GCHD" NUMBER(8,0), 
	"EFFDCLDT" NUMBER(8,0), 
	"OCCDATE" NUMBER(8,0), 
	"UNIQDATE" NUMBER(8,0), 
	"MPLNUM" CHAR(8 CHAR), 
	"ZCPMCPNCDE" VARCHAR2(6 CHAR), 
	"ZCPMPLANCD" VARCHAR2(30 CHAR), 
	"ZTRGTFLG" VARCHAR2(1 CHAR), 
	"ZENDCDE" VARCHAR2(20 CHAR), 
	"ZPGPFRDT" NUMBER(8,0), 
	"ZPGPTODT" NUMBER(8,0), 
	"ZPOLTDATE" NUMBER(8,0), 
	"ZPLANCLS" CHAR(2 CHAR), 
	"CLNTNUM" VARCHAR2(50 CHAR), 
	"ZBNKFLAG" CHAR(1 CHAR), 
	"ZCCFLAG" CHAR(1 CHAR), 
	"ZENDSCID" VARCHAR2(8 CHAR), 
	"ZSLPTYP" VARCHAR2(1 CHAR), 
	"UNIQUE_NUMBER01" NUMBER(18,0), 
	"ZWORKPLCE" VARCHAR2(25 CHAR), 
	"UNIQUE_NUMBER02" NUMBER(18,0), 
	"OCCPCODE" VARCHAR2(4 CHAR), 
	"SEQNUMB" NUMBER(3,0), 
	"ZACMCLDT" NUMBER(8,0), 
	"ZCN_ZCMPCODE" VARCHAR2(6 CHAR), --Ticket #ZJNPG-9739
	"CLB_BANKKEY" VARCHAR2(10 CHAR), --Ticket #ZJNPG-9739
    "PAZ_REC" VARCHAR2(50 CHAR),     --Ticket #ZJNPG-9739
	"ZRCALTTY" VARCHAR2(4 CHAR), 
	CONSTRAINT "PK_TITDMGPOLTRNH" PRIMARY KEY ("CHDRNUM", "ZSEQNO", "EFFDATE", "MBRNO")
   ) NOCOMPRESS NOLOGGING;
   CREATE INDEX "Jd1dta"."INDX_DMIGTITDMGPOLTRNH" ON "Jd1dta"."DMIGTITDMGPOLTRNH" ("CHDRNUM", "MBRNO", "TRANNO"); 

--------------------------------------------------------
--  DDL for Table DMIGTITDMGMBRINDP2
--------------------------------------------------------
DROP TABLE Jd1dta.DMIGTITDMGMBRINDP2;
  CREATE TABLE "Jd1dta"."DMIGTITDMGMBRINDP2" 
   (	"RECIDXMBINDP2" NUMBER(*,0) NOT NULL ENABLE, 
	"REFNUM" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"ZSEQNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"DPNTNO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PRODTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"APREM" NUMBER(15,2) NOT NULL ENABLE, 
	"HSUMINSU" NUMBER(13,0) NOT NULL ENABLE, 
	"ZTAXFLG" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"NDRPREM" NUMBER(15,2), 
	"PRODTYP02" VARCHAR2(4 CHAR), 
	"TRANNO" NUMBER(8,0) NOT NULL ENABLE, 
	"ZPLANCDE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CCDATE" NUMBER(8,0), 
	"CRDATE" NUMBER(8,0), 
	"ZSLPTYP" VARCHAR2(1 CHAR), 
	"ZINSROLE" VARCHAR2(2 CHAR), 
	"EFFDCLDT" NUMBER(8,0), 
	"STATCODE" VARCHAR2(2 CHAR), 
	"ZPOLTDATE" NUMBER(8,0),
    "PAZ_REC" VARCHAR2(50 CHAR), --Ticket #ZJNPG-9739
	"PERIODNO" NUMBER(2,0), 
	"PERIODCNT" NUMBER(2,0), 
	"RECCHUNCKBINDP2" NUMBER(*,0)
   ) NOCOMPRESS NOLOGGING;
   CREATE INDEX "Jd1dta"."IDX_DMIGTITDMGMBRINDP2" ON "Jd1dta"."DMIGTITDMGMBRINDP2" ("REFNUM", "MBRNO", "DPNTNO", "TRANNO") ;

--------------------------------------------------------
--  DDL for Table DMIGTITDMGAPIRNO
--------------------------------------------------------
DROP TABLE Jd1dta.DMIGTITDMGAPIRNO;

 CREATE TABLE "Jd1dta"."DMIGTITDMGAPIRNO" 
   (	"RECIDXAPIRNO" NUMBER(*,0) NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"ZAPIRNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"FULLKANJINAME" VARCHAR2(120 CHAR) NOT NULL ENABLE, 
	"TRANNO" NUMBER(8,0) NOT NULL ENABLE, 
	"DTEATT" NUMBER(8,0),
    "GC_CHDRNUM" VARCHAR2(8 CHAR),  --#ZJNPG-9739: added new column
    "PAZ_REC" VARCHAR2(50 CHAR)     --#ZJNPG-9739: added new column
   ) 
 NOCOMPRESS NOLOGGING;


--CREATE TABLE Jd1dta.DMIGTITDMGAPIRNO AS ( SELECT * FROM TITDMGAPIRNO@DMSTAGEDBLINK WHERE 1=2);

--------------------------------------------------------------------------------------------------
--- Added for ZJNPG-8428 , DDL for Attributes, Summary & detail recon, module level staging tables
--------------------------------------------------------------------------------------------------

drop table Jd1dta.dm_data_validation_attrib;
create table Jd1dta.dm_data_validation_attrib
(n_attrib_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_module_name varchar2(50),
v_attrib_name varchar2(40),
v_attrib_desc varchar2(1000),
c_status_flg char(1),
d_created_on date,
v_created_by varchar2(100)
);


drop table Jd1dta.dm_dv_recon_summary;

create table Jd1dta.dm_dv_recon_summary
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id varchar2(20),
v_module_name  varchar2(50),
v_attrib_name varchar2(40),
n_src_pol_cnt number,
n_stg_pol_cnt number,
n_ig_pol_cnt number,
n_src_stg_mis number,
n_stg_ig_mis  number,
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));



drop table Jd1dta.dm_dv_recon_detail;

create table Jd1dta.dm_dv_recon_detail
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));

drop table Jd1dta.dm_billinst_recon_det;

create table Jd1dta.dm_billinst_recon_det
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));

drop table Jd1dta.dm_mem_ind_recon_det;

create table Jd1dta.dm_mem_ind_recon_det
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));

drop table Jd1dta.dm_master_pol_recon_det;

create table Jd1dta.dm_master_pol_recon_det
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));

drop table Jd1dta.dm_pol_dishnr_recon_det;

create table Jd1dta.dm_pol_dishnr_recon_det
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));

drop table Jd1dta.dm_pol_collres_recon_det;

create table Jd1dta.dm_pol_collres_recon_det
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));

-- Member and Individual Policy History
drop table Jd1dta.dm_pol_mihis_recon_det;

create table Jd1dta.dm_pol_mihis_recon_det
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));


drop table Jd1dta.dm_pol_billref_recon_det;

create table Jd1dta.dm_pol_billref_recon_det
(n_seq_id number GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 not null,
v_batch_id   varchar2(20),
v_policy_no  varchar2(100),
v_prod_cde   varchar2(50),
v_pol_commdt  varchar2(50),
v_attrib_name varchar2(40),
v_pol_status  varchar2(10),
v_module_name  varchar2(50),
v_eff_date    varchar2(50),
v_eff_desc    varchar2(100),
v_src_val     varchar2(1000),
v_stg_val     varchar2(1000),
v_ig_val      varchar2(1000),
v_summary_batch_id varchar2(100),
d_created_on date,
v_created_by varchar2(50),
v_job_name varchar2(50));

drop table Jd1dta.error_log;

create table Jd1dta.error_log
(v_err_seq number,
v_error_code number,
v_error_message varchar2(4000),
v_error_stack varchar2(4000),
v_call_stack varchar2(4000),
v_error_backtrace varchar2(4000),
v_created_by varchar2(30),
v_prog varchar2(30),
d_created_on date
);


Drop table "Jd1dta"."IGNAYOSEVIEW" ;
	CREATE TABLE "Jd1dta"."IGNAYOSEVIEW" 
   (	
    "UNIQUEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ZENDCDE" VARCHAR2(20 CHAR), 
    "CLNTNUM"	CHAR(8 CHAR),
	"ZKANASNMNOR"	VARCHAR2(60 CHAR),
	"ZKANAGNMNOR"	VARCHAR2(60 CHAR),
	"CLTSEX"	CHAR(1 CHAR),
	"CLTDOB"	NUMBER(8,0),
	"CLTPCODE"	CHAR(10 CHAR),
	"RMBLPHONE"	VARCHAR2(16 CHAR),
    "CHDRNUM"  CHAR(8 CHAR) ,
	"STATCODE" VARCHAR2(2 CHAR),
	"ZPLANCLS" VARCHAR2(2 CHAR),
	"PRIORITY"  VARCHAR2(1 CHAR),
    "ROW_NUM" number
   );
     CREATE UNIQUE INDEX "Jd1dta"."UNI_NY_IGNAYO" ON "Jd1dta"."IGNAYOSEVIEW" ("CLNTNUM") ;
	 
	Drop table "Jd1dta"."DMPANAYOSEVIEW" ;
	CREATE TABLE "Jd1dta"."DMPANAYOSEVIEW" 
   (	
    "UNIQUEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ZENDCDE" VARCHAR2(20 CHAR), 
    "CLNTNUM"	CHAR(8 CHAR),
	"ZKANASNMNOR"	VARCHAR2(60 CHAR),
	"ZKANAGNMNOR"	VARCHAR2(60 CHAR),
	"CLTSEX"	CHAR(1 CHAR),
	"CLTDOB"	NUMBER(8,0),
	"CLTPCODE"	CHAR(10 CHAR),
	"RMBLPHONE"	VARCHAR2(16 CHAR),
    "CHDRNUM"  CHAR(8 CHAR) ,
	"STATCODE" VARCHAR2(2 CHAR),
	"ZPLANCLS" VARCHAR2(2 CHAR),
	"PRIORITY"  VARCHAR2(1 CHAR),
    "ROW_NUM" number
   );
     CREATE UNIQUE INDEX "Jd1dta"."UNI_NY_DMPANAYO" ON "Jd1dta"."DMPANAYOSEVIEW" ("CLNTNUM") ;
	 
	 
	 
	Drop table "Jd1dta"."PAZDNYPF" ;
  CREATE TABLE "Jd1dta"."PAZDNYPF" 
   (	
    "UNIQUEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"PREFIX" VARCHAR2(2 CHAR), 
	"DM_OR_IG" VARCHAR2(4 CHAR),
    "CLNTSTAS" VARCHAR2(2 CHAR),
	"IS_UPDATE_REQ" VARCHAR2(2 CHAR),
	"ZENTITY" VARCHAR2(50 CHAR), 
	"ZIGVALUE" VARCHAR2(50 CHAR), 
	"JOBNUM" NUMBER(8,0), 
	"JOBNAME" VARCHAR2(10 CHAR)
   );
     CREATE UNIQUE INDEX "Jd1dta"."UNI_NY_ZENT" ON "Jd1dta"."PAZDNYPF" ("ZENTITY") ;

drop table "Jd1dta"."DMIGTITNYCLT" ;
CREATE TABLE "Jd1dta"."DMIGTITNYCLT" 
   (	
   "UNIQUEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE NOT NULL ENABLE, 
	"REFNUM" VARCHAR2(10 CHAR), 
    "DM_OR_IG" VARCHAR2(4 CHAR),
    "CLNTSTAS" VARCHAR2(2 CHAR),
	"IS_UPDATE_REQ" VARCHAR2(2 CHAR),
	"IG_CLNTNUM" VARCHAR2(8 CHAR), 
	"DCH_ZENDCDE" VARCHAR2(20 CHAR), 
	"DCH_ZKANASNMNOR" VARCHAR2(60 CHAR), 
	"DCH_ZKANAGNMNOR" VARCHAR2(60 CHAR), 
	"DCH_CLTDOB" VARCHAR2(40 BYTE), 
	"DCH_CLTPCODE" VARCHAR2(10 CHAR), 
	"DCH_CLTSEX" VARCHAR2(1 CHAR), 
	"DCH_CLTPHONE01" VARCHAR2(64 BYTE),
    DCH_PRIORITY VARCHAR2(1 CHAR), 
    NV_PRIORITY VARCHAR2(1 CHAR)
   ) ;

  CREATE UNIQUE INDEX "Jd1dta"."UNI_NY_REFNUM" ON "Jd1dta"."DMIGTITNYCLT" ("REFNUM") ;


DROP TABLE "Jd1dta"."DMUNIQUENOUPDT" ;

  CREATE TABLE "Jd1dta"."DMUNIQUENOUPDT" 
   (	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"CLNTNUM" CHAR(8 CHAR) NOT NULL ENABLE, 
	"TRANNO" NUMBER(5,0) NOT NULL ENABLE, 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TAB_UNIQUE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ZCLN_UNIQUE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "IS_UPDATED" VARCHAR2(1 CHAR) DEFAULT 'N' , 
	 CONSTRAINT "DMUNIQUENOUPDT_UK1" UNIQUE ("TABLE_NAME", "TAB_UNIQUE", "IS_UPDATED")
   );

  CREATE INDEX "Jd1dta"."DMUNIQUENOUPDT_INDEX1" ON "Jd1dta"."DMUNIQUENOUPDT" ("TAB_UNIQUE") ;

  CREATE INDEX "Jd1dta"."DMUNIQUENOUPDT_INDEX2" ON "Jd1dta"."DMUNIQUENOUPDT" ("TABLE_NAME");


DROP TABLE "Jd1dta"."DM2_DMIG_DATA_CNT" ; 
  CREATE TABLE "Jd1dta"."DM2_DMIG_DATA_CNT" 
   (	
   "UNI_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ,
	"TAB_NAME" VARCHAR2(35 BYTE) NOT NULL ENABLE, 
	"ROW_COUNT" NUMBER
   ) ;
  CREATE INDEX "Jd1dta"."DM2_DMIG_DATA_CNT_INDEX1" ON "Jd1dta"."DM2_DMIG_DATA_CNT" ("TAB_NAME") ;
  
  
  
-- =========================== Renewal Determination Table : START ===============================================================
-- ====  DMIGTITDMGRNWDT1 =========
	DROP TABLE  "Jd1dta"."DMIGTITDMGRNWDT1" ;

	CREATE TABLE "Jd1dta"."DMIGTITDMGRNWDT1" 
	(          "CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
			  "MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
			  "ZRNDTFRM" NUMBER(8,0) NOT NULL ENABLE, 
			  "ZRNDTTO" NUMBER(8,0) NOT NULL ENABLE, 
			  "ZALTRCDE" VARCHAR2(3 CHAR), 
			  "ZRNDTREG" NUMBER(8,0), 
			  "ZRNDTAPP" NUMBER(8,0), 
			  "ZINSROLE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
			  "STAGECLNTNO" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
			  "ZTERMFLG" VARCHAR2(1 CHAR), 
			  "ZSALPLAN" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
			  "ZRNDTRCD" VARCHAR2(3 CHAR), 
			  "ZINSRNWAGE" NUMBER(3,0), 
			  "INPUT_SOURCE_TABLE" VARCHAR2(15 CHAR) NOT NULL ENABLE
			 
	);
	ALTER TABLE  "Jd1dta"."DMIGTITDMGRNWDT1" ADD CONSTRAINT "DMIGTITDMGRNWDT1_PK" PRIMARY KEY ("CHDRNUM", "MBRNO");

	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."CHDRNUM" IS 'Contract Number';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."MBRNO" IS 'Member Number';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZRNDTFRM" IS 'Renewal Date from';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZRNDTTO" IS 'Renewal Date to';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZALTRCDE" IS 'Alteration Reason Code';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZRNDTREG" IS 'Renewal Determination Registration Date';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZRNDTAPP" IS 'Renewal Determination Approval Date';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZINSROLE" IS 'Insured Role';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."STAGECLNTNO" IS 'Staging Clinet Number';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZTERMFLG" IS 'Termination Flag';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZSALPLAN" IS 'Sales Plan';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZRNDTRCD" IS 'Renewal Determination Result code';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."ZINSRNWAGE" IS 'Insured Age at Renewal';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1"."INPUT_SOURCE_TABLE" IS 'Source of the Information';


-- =================================  DMIGTITDMGRNWDT2 ==========================================
   DROP TABLE  "Jd1dta"."DMIGTITDMGRNWDT2" ;
	CREATE TABLE "Jd1dta"."DMIGTITDMGRNWDT2" 
	   (         
		"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
		"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
		"DPNTNO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
		"PRODTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
		"SUMINS" NUMBER(17,2) NOT NULL ENABLE, 
		"DPREM" NUMBER(15,2) NOT NULL ENABLE, 
		"ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
		"PRODTYP02" VARCHAR2(4 CHAR), 
		"NDR_DPREM" NUMBER(15,2), 
		"INPUT_SOURCE_TABLE" VARCHAR2(15 BYTE) NOT NULL ENABLE
	)
		NOCOMPRESS NOLOGGING PARALLEL 
		;
	ALTER TABLE  "Jd1dta"."DMIGTITDMGRNWDT2" ADD CONSTRAINT "DMIGTITDMGRNWDT2_PK" PRIMARY KEY ("CHDRNUM", "MBRNO", "DPNTNO", "PRODTYP");

	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."CHDRNUM" IS 'Contract Number';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."MBRNO" IS 'Member Number';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."DPNTNO" IS 'Dependent Number';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."PRODTYP" IS 'Product type';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."SUMINS" IS 'Sum Insured';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."DPREM" IS 'Premium Amount';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."ZINSTYPE" IS 'Insurance type';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."PRODTYP02" IS 'NDR Rider code';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."NDR_DPREM" IS 'NDR Premium';
	COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2"."INPUT_SOURCE_TABLE" IS 'Source of the Information';

-- ================================= Registery Table :  PAZDRDPF ======================

	DROP TABLE "Jd1dta"."PAZDRDPF" ;

	CREATE TABLE "Jd1dta"."PAZDRDPF" 
	(	   
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZRNDTFRM" NUMBER(8,0) NOT NULL ENABLE, 
	"ZINSROLE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"INPUT_SOURCE_TABLE" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"ZSALPLAN" VARCHAR2(30 CHAR), 
	"ZRNDTNUM"	VARCHAR2(8 CHAR),
	"JOBNAME" VARCHAR2(10 CHAR),
	"JOBNUM" NUMBER(8,0),  
	"USRPRF"	CHAR(10 CHAR),
	"DATIME" TIMESTAMP (6) DEFAULT systimestamp

	)  
	NOCOMPRESS NOLOGGING PARALLEL 
	;

	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."CHDRNUM" IS 'Contract Number';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."ZRNDTFRM" IS 'Renewal Date from';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."ZINSROLE" IS 'Insured Role';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."MBRNO" IS 'Member Number';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."INPUT_SOURCE_TABLE" IS 'Input Source File';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."ZSALPLAN" IS 'Sales Plan';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."ZRNDTNUM" IS 'Renewal Determination Numer';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."JOBNAME" IS 'Job Name';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."JOBNUM" IS 'Job number';
	COMMENT ON COLUMN "Jd1dta"."PAZDRDPF"."USRPRF" IS 'User Profile';

-- ================================= Registery Table :  PAZDRCPF =========================

	DROP TABLE "Jd1dta"."PAZDRCPF" ;

	CREATE TABLE "Jd1dta"."PAZDRCPF" 
	(	   
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZRNDTFRM" NUMBER(8,0) NOT NULL ENABLE, 
	"ZINSROLE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"DPNTNO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PRODTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"INPUT_SOURCE_TABLE" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"ZSALPLAN" VARCHAR2(30 CHAR), 
	"ZRNDTNUM"	VARCHAR2(8 CHAR),
	"JOBNAME" VARCHAR2(10 CHAR),
	"JOBNUM" NUMBER(8,0),  
	"USRPRF"	CHAR(10 CHAR),
	"DATIME" TIMESTAMP (6) DEFAULT systimestamp

	)  
	NOCOMPRESS NOLOGGING PARALLEL 
	;

	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."CHDRNUM" IS 'Contract Number';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."ZRNDTFRM" IS 'Renewal Date from';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."ZINSROLE" IS 'Insured Role';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."MBRNO" IS 'Member Number';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."PRODTYP" IS 'Product type';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."DPNTNO" IS 'Dependent Number';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."INPUT_SOURCE_TABLE" IS 'Input Source File';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."ZSALPLAN" IS 'Sales Plan';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."ZRNDTNUM" IS 'Renewal Determination Numer';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."JOBNAME" IS 'Job Name';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."JOBNUM" IS 'Job number';
	COMMENT ON COLUMN "Jd1dta"."PAZDRCPF"."USRPRF" IS 'User Profile';



-- ========= DMIGTITDMGRNWDT1_INT ================

	DROP TABLE "Jd1dta"."DMIGTITDMGRNWDT1_INT" ;

	CREATE TABLE "Jd1dta"."DMIGTITDMGRNWDT1_INT" 
   (	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZRNDTFRM" NUMBER(8,0) NOT NULL ENABLE, 
	"ZRNDTTO" NUMBER(8,0) NOT NULL ENABLE, 
	"ZALTRCDE" VARCHAR2(3 CHAR), 
	"ZRNDTREG" NUMBER(8,0), 
	"ZRNDTAPP" NUMBER(8,0), 
	"ZRNDTRCD" VARCHAR2(3 CHAR), 
	"STATCODE" VARCHAR2(3 CHAR), 
	"ZPOLTDATE" NUMBER(8,0), 
	"INPUT_SOURCE_TABLE" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"HEADER_RECORD" NUMBER(1,0) DEFAULT 0, 
	"ZINSROLE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"STAGECLNTNO" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"ZTERMFLG" VARCHAR2(1 CHAR), 
	"ZSALPLAN" VARCHAR2(30 CHAR), 
	"CLNTNUM" VARCHAR2(8 CHAR), 
	"MBR_DTETRM" NUMBER(8,0), 
	"CLNTDOB" NUMBER(8,0), 
	"ZINSRNWAGE" NUMBER(3,0), 
	"ZACCMFLG" VARCHAR2(1 CHAR), 
	"ZASRFFLG" VARCHAR2(1 CHAR), 
	"ZRNDTNUM" VARCHAR2(8 CHAR), 
	"ZREFKEY" VARCHAR2(100 CHAR), 
	"ERRINSCNT" NUMBER(2,0) DEFAULT 0, 
	"ISCOVERR" NUMBER(2,0) DEFAULT 0, 
	"ERRCHDR" NUMBER(2,0) DEFAULT 0, 
	"INDIC" VARCHAR2(1 CHAR), 
	"DATIME" TIMESTAMP (6) DEFAULT systimestamp
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 5 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL ;

   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."CHDRNUM" IS 'Contract Number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZRNDTFRM" IS 'Renewal Date from';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZRNDTTO" IS 'Renewal Date to';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZALTRCDE" IS 'Alteration Reason Code';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZRNDTREG" IS 'Renewal Determination Registration Date';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZRNDTAPP" IS 'Renewal Determination Approval Date';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZRNDTRCD" IS 'Renewal Determination Result code';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."STATCODE" IS 'GCHD Status Code ';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZPOLTDATE" IS 'Policy Termination Date ';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."HEADER_RECORD" IS '1- Header Record Main insured Record 0 - Others';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZINSROLE" IS 'Insured Role';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."MBRNO" IS 'Member Number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."STAGECLNTNO" IS 'Staging Clinet Number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZTERMFLG" IS 'Termination Flag';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZSALPLAN" IS 'Sales Plan';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."CLNTNUM" IS 'Insured client number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."MBR_DTETRM" IS 'Insured Termination Date GMHDPF.DTETRM';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."CLNTDOB" IS 'Insured DOB';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZINSRNWAGE" IS 'Insured Age at Renewal';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZACCMFLG" IS 'Accumulation Fail Flag';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZASRFFLG" IS 'ASRF applicable flag';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZRNDTNUM" IS 'Renewal Determination Numer';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ZREFKEY" IS 'Referecne Key for Error Records';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ERRINSCNT" IS 'Inusred level error count';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ISCOVERR" IS '1 when any coverage has error in DMIGTITDMGRNWDT2_INT';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."ERRCHDR" IS 'Policy level error count';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT1_INT"."INDIC" IS 'S - Successful,  E-Error record';




-- =========== DMIGTITDMGRNWDT2_INT =============
	DROP TABLE  "Jd1dta"."DMIGTITDMGRNWDT2_INT" ;

	
  CREATE TABLE "Jd1dta"."DMIGTITDMGRNWDT2_INT" 
   (	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"DPNTNO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PRODTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"SUMINS" NUMBER(17,2) NOT NULL ENABLE, 
	"DPREM" NUMBER(15,0) NOT NULL ENABLE, 
	"ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"PRODTYP02" VARCHAR2(4 CHAR), 
	"NDR_DPREM" NUMBER(15,2), 
	"INPUT_SOURCE_TABLE" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"ZSALPLAN" VARCHAR2(30 CHAR), 
	"ZRNDTNUM" VARCHAR2(8 CHAR), 
	"ZINSROLE" VARCHAR2(1 CHAR), 
	"ZRNDTFRM" NUMBER(8,0), 
	"ZRNDTTO" NUMBER(8,0), 
	"ZODMPRMVER" VARCHAR2(4 CHAR), 
	"ZREFKEY" VARCHAR2(100 CHAR), 
	"ERRCOVCNT" NUMBER(2,0) DEFAULT 0, 
	"ISHDRERR" NUMBER(2,0) DEFAULT 0, 
	"ERRCHDR" NUMBER(2,0) DEFAULT 0, 
	"INDIC" VARCHAR2(1 CHAR), 
	"DATIME" TIMESTAMP (6) DEFAULT systimestamp, 
	 CONSTRAINT "DMIGTITDMGRNWDT2_INT_PK" PRIMARY KEY ("CHDRNUM", "MBRNO", "DPNTNO", "PRODTYP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 5 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL ;

   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."CHDRNUM" IS 'Contract Number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."MBRNO" IS 'Member Number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."DPNTNO" IS 'Dependent Number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."PRODTYP" IS 'Product type';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."SUMINS" IS 'Sum Insured';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."DPREM" IS 'Premium Amount';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ZINSTYPE" IS 'Insurance type';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."PRODTYP02" IS 'NDR Rider code';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."NDR_DPREM" IS 'NDR Premium';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."INPUT_SOURCE_TABLE" IS 'Source of the Information';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ZRNDTNUM" IS 'Renewal Determination Number';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ZINSROLE" IS 'Insured Role';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ZRNDTFRM" IS 'ZRNDTFRM Of Policy';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ZRNDTTO" IS 'ZRNDTTO Of Policy';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ZODMPRMVER" IS 'ODM Premium Version';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ZREFKEY" IS 'Referecne Key for Error Records';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ERRCOVCNT" IS 'Count of error for a coverage';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ISHDRERR" IS '1 when Policy has any error in DMIGTITDMGRNWDT1';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."ERRCHDR" IS '1 when Policy has any error in DMIGTITDMGRNWDT1_INT or DMIGTITDMGRNWDT2_INT';
   COMMENT ON COLUMN "Jd1dta"."DMIGTITDMGRNWDT2_INT"."INDIC" IS 'S - Successful,  E-Error record';


-- ==============  ZDOERC_INT ================
	DROP TABLE "Jd1dta"."ZDOERC_INT" ;

	CREATE TABLE "Jd1dta"."ZDOERC_INT"
	(
	"CHDRNUM" VARCHAR2(8 CHAR),
	"MBRNO" VARCHAR2(5 CHAR),
	"DPNTNO" VARCHAR2(2 CHAR) ,
	"PRODTYP" VARCHAR2(4 CHAR) ,
	"ZREFKEY"	VARCHAR2(100 CHAR),
	"ERRFLD" VARCHAR2(30 CHAR),
	"FLDVALU" VARCHAR2(100 CHAR),
	"ERRCD" VARCHAR2(4 CHAR),
	"ERRMSG" VARCHAR2(250 CHAR),
	"ZFILENME" VARCHAR2(20 CHAR),
	"COV_ERR_CNT" NUMBER(2,0),

	"JOBNAME" VARCHAR2(10 CHAR),
	"JOBNUM" NUMBER(8,0),
	"DATIME" TIMESTAMP (6) DEFAULT systimestamp
	)
	NOCOMPRESS NOLOGGING PARALLEL
	;

	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."CHDRNUM" IS 'Contract Number';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."MBRNO" IS 'Member Number';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."DPNTNO" IS 'Dependent Number';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."PRODTYP" IS 'Product type';

	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."ZREFKEY" IS 'Referecne Key for Error Records';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."ERRFLD" IS 'Error Field Name';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."FLDVALU" IS 'Error Field Value';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."ERRCD" IS 'Error Code';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."ERRMSG" IS 'Error Message';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."ZFILENME" IS ' INPUT_SOURCE_TABLE Source of the Information';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."COV_ERR_CNT" IS 'Count of error for a coverage';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."JOBNAME" IS ' Schedule Name ';
	COMMENT ON COLUMN "Jd1dta"."ZDOERC_INT"."JOBNUM" IS 'Schedule Number ';



-- =============== ZDOERD_INT ============
	DROP TABLE "Jd1dta"."ZDOERD_INT" ;

	CREATE TABLE "Jd1dta"."ZDOERD_INT" 
	(	
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"MBRNO" VARCHAR2(5 CHAR), 
	"ZREFKEY"	VARCHAR2(100 CHAR),
	"ERRFLD" VARCHAR2(30 CHAR), 
	"FLDVALU" VARCHAR2(100 CHAR), 
	"ERRCD" VARCHAR2(4 CHAR), 
	"ERRMSG" VARCHAR2(250 CHAR), 
	"ZFILENME" VARCHAR2(20 CHAR), 
	"MBR_ERR_CNT" NUMBER(2,0), 

	"JOBNAME" VARCHAR2(10 CHAR),
	"JOBNUM" NUMBER(8,0),  
	"DATIME" TIMESTAMP (6) DEFAULT systimestamp
	) 
	NOCOMPRESS NOLOGGING PARALLEL
	;


	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."CHDRNUM" IS 'Contract Number';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."MBRNO" IS 'Member Number';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."ZREFKEY" IS 'Referecne Key for Error Records';

	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."ERRFLD" IS 'Error Field Name';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."FLDVALU" IS 'Error Field Value';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."ERRCD" IS 'Error Code';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."ERRMSG" IS 'Error Message';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."ZFILENME" IS 'INPUT_SOURCE_TABLE Source of the Information';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."MBR_ERR_CNT" IS 'Error recrod rank at member level';

	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."JOBNAME" IS 'Schedule Name ';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."JOBNUM" IS 'Schedule Number ';
	COMMENT ON COLUMN "Jd1dta"."ZDOERD_INT"."DATIME" IS 'TimeStamp';

-- =============== RECON_MASTER_RD : Renewal Determination Recon Set 1 Table  ============

	DROP TABLE "Jd1dta"."RECON_MASTER_RD" ;
	CREATE TABLE "Jd1dta"."RECON_MASTER_RD" 
	(	
		"SCHEDULE_ID" NUMBER(5,0) NOT NULL ENABLE, 
		"RECON_QUERY_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
		"MODULE_NAME" VARCHAR2(50 CHAR), 
		"GROUP_CLAUSE" VARCHAR2(255 CHAR), 
		"VALIDATION_TYPE" VARCHAR2(255 CHAR), 
		"SOURCE_VALUE" NUMBER  DEFAULT 0 NOT NULL ENABLE, 
		"STAGING_VALUE" NUMBER  DEFAULT 0 NOT NULL ENABLE, 
		"IG_VALUE" NUMBER DEFAULT 0  NOT NULL ENABLE , 
		"IG_ERROR_VALUE" NUMBER  DEFAULT 0 NOT NULL ENABLE, 
		"STATUS" VARCHAR2(5 CHAR), 
		"CHDRNUM" VARCHAR2(8 CHAR), 
		"ZINSROLE" VARCHAR2(1 CHAR), 
		"MBRNO" VARCHAR2(5 CHAR) ,
		"ZRNDTFRM" NUMBER(8,0) , 
		"ZRNDTTO" NUMBER(8,0) ,
		"DPNTNO" VARCHAR2(2 CHAR) , 
		"PRODTYP" VARCHAR2(4 CHAR) ,
		"ZINSTYPE" VARCHAR2(3 CHAR),
		"PRODTYP02" VARCHAR2(4 CHAR), 
		"NDR_DPREM" NUMBER(15,2), 
		"ZREFKEY"	VARCHAR2(100 CHAR) NOT NULL ENABLE,
		"WHERE_CLAUSE" VARCHAR2(255 CHAR),
		"QUERY_DESC" VARCHAR2(500 CHAR),
		"RUNDATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
	) 
	NOCOMPRESS NOLOGGING PARALLEL
	;



--=========================== Renewal Determination Table : END ===============================================================

-- Client Bank Start
DROP TABLE Jd1dta.DM_CLIENT_BANK_RECON_DET;

CREATE TABLE Jd1dta.DM_CLIENT_BANK_RECON_DET
   (	
	N_SEQ_ID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY, 
	V_BATCH_ID VARCHAR2(20 BYTE), 
	V_POLICY_NO VARCHAR2(100 BYTE), 
	V_PROD_CDE VARCHAR2(50 BYTE), 
	V_POL_COMMDT VARCHAR2(50 BYTE), 
	V_ATTRIB_NAME VARCHAR2(40 BYTE), 
	V_POL_STATUS VARCHAR2(10 BYTE), 
	V_MODULE_NAME VARCHAR2(50 BYTE), 
	V_EFF_DATE VARCHAR2(50 BYTE), 
	V_EFF_DESC VARCHAR2(100 BYTE), 
	V_SRC_VAL VARCHAR2(1000 BYTE), 
	V_STG_VAL VARCHAR2(1000 BYTE), 
	V_IG_VAL VARCHAR2(1000 BYTE), 
	V_SUMMARY_BATCH_ID VARCHAR2(100 BYTE), 
	D_CREATED_ON DATE, 
	V_CREATED_BY VARCHAR2(50 BYTE), 
	V_Job_Name Varchar2(50 Byte)
  );


  drop table Jd1dta.DMIGODMVERSIONHIS;

-- ODM PREMIUM TABLE 
  CREATE TABLE "Jd1dta"."DMIGODMVERSIONHIS" 
   (           "VERNO" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
               "ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
               "CATEGORY" VARCHAR2(50 CHAR), 
               "FRMDTE" NUMBER(8,0) NOT NULL ENABLE, 
               "TODTE" NUMBER(8,0) NOT NULL ENABLE, 
               "DESCRIPTION" VARCHAR2(100 CHAR), 
               "DATETIME" TIMESTAMP (6) DEFAULT systimestamp
   ) 
 NOCOMPRESS NOLOGGING
;

   COMMENT ON COLUMN "Jd1dta"."DMIGODMVERSIONHIS"."VERNO" IS 'ODM Version';
   COMMENT ON COLUMN "Jd1dta"."DMIGODMVERSIONHIS"."ZINSTYPE" IS 'Insurance Type';
   COMMENT ON COLUMN "Jd1dta"."DMIGODMVERSIONHIS"."CATEGORY" IS 'Category';
   COMMENT ON COLUMN "Jd1dta"."DMIGODMVERSIONHIS"."FRMDTE" IS 'From Date';
   COMMENT ON COLUMN "Jd1dta"."DMIGODMVERSIONHIS"."TODTE" IS 'To Date';
   COMMENT ON COLUMN "Jd1dta"."DMIGODMVERSIONHIS"."DESCRIPTION" IS 'Description';
   COMMENT ON COLUMN "Jd1dta"."DMIGODMVERSIONHIS"."DATETIME" IS 'Date Time';


DROP TABLE "Jd1dta"."DM_POL_RNWL_DET_RECON_DET" CASCADE CONSTRAINTS;

CREATE TABLE "Jd1dta"."DM_POL_RNWL_DET_RECON_DET"
   (    "N_SEQ_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOT NULL,
    "V_BATCH_ID" VARCHAR2(20 BYTE),
    "V_POLICY_NO" VARCHAR2(100 BYTE),
    "V_PROD_CDE" VARCHAR2(50 BYTE),
    "V_POL_COMMDT" VARCHAR2(50 BYTE),
    "V_ATTRIB_NAME" VARCHAR2(40 BYTE),
    "V_POL_STATUS" VARCHAR2(10 BYTE),
    "V_MODULE_NAME" VARCHAR2(50 BYTE),
    "V_EFF_DATE" VARCHAR2(50 BYTE),
    "V_EFF_DESC" VARCHAR2(100 BYTE),
    "V_SRC_VAL" VARCHAR2(1000 BYTE),
    "V_STG_VAL" VARCHAR2(1000 BYTE),
    "V_IG_VAL" VARCHAR2(1000 BYTE),
    "V_SUMMARY_BATCH_ID" VARCHAR2(100 BYTE),
    "D_CREATED_ON" DATE,
    "V_CREATED_BY" VARCHAR2(50 BYTE),
    "V_JOB_NAME" VARCHAR2(50 BYTE)
   );
 
 -----
 DROP index DM_zclepf_idx;
 CREATE INDEX DM_zclepf_idx ON Jd1dta.zclepf ( RTRIM(clntnum));
--EXEC DBMS_STATS.gather_table_stats('Jd1dta', 'ZCLEPF', cascade => TRUE);
---

---------------------Campcode------------------
DROP TABLE "Jd1dta"."DMIGTITDMGCAMPCDE";
  CREATE TABLE "Jd1dta"."DMIGTITDMGCAMPCDE" 
   (	
    "RECIDXCAMP" NUMBER(*,0) NOT NULL ENABLE, 
	"ZCMPCODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"ZPETNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"ZPOLCLS" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"ZENDCODE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"GPOLTYP" VARCHAR2(3 CHAR), 
	"ZAGPTID" VARCHAR2(8 CHAR), 
	"RCDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"ZCMPFRM" NUMBER(8,0) NOT NULL ENABLE, 
	"ZCMPTO" NUMBER(8,0) NOT NULL ENABLE, 
	"ZMAILDAT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZACLSDAT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZDLVCDDT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZVEHICLE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"ZSTAGE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"ZSCHEME01" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZSCHEME02" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZCRTUSR" VARCHAR2(10 CHAR), 
	"ZAPPDATE" NUMBER(8,0), 
	"ZCCODIND" VARCHAR2(1 CHAR), 
	"EFFDATE" NUMBER(8,0), 
	"STATUS" VARCHAR2(2 CHAR), 
	"GC_CHDRNUM" VARCHAR2(8 CHAR),
	"ZEN_ZENDCDE" VARCHAR2(20 CHAR),
	"ZAGPTNUM" VARCHAR2(8 CHAR),
	 CONSTRAINT "COND_TITDMGCAMPCDE" CHECK ((zpolcls = 'G' and CHDRNUM is not null) or (zpolcls = 'I' and ZAGPTID is not null and GPOLTYP is not NULL)) ENABLE, 
	 CONSTRAINT "PK1_TITDMGCAMPCDE" PRIMARY KEY ("ZCMPCODE")
   ) NOCOMPRESS NOLOGGING;
-----------------------------------------------------   
DROP TABLE "Jd1dta"."DMIGTITDMGZCSLPF";
 CREATE TABLE "Jd1dta"."DMIGTITDMGZCSLPF" 
  (	
  "RECIDXSLPL2" NUMBER(*,0) NOT NULL ENABLE, 
  "ZCMPCODE" VARCHAR2(6 CHAR), 
  "OLD_ZSALPLAN" VARCHAR2(30 CHAR), 
  "ZSALPLAN" VARCHAR2(30 CHAR),
  "ZSL_ZSALPLAN"  VARCHAR2(30 CHAR),
  "RECCHUNKNUM" NUMBER(*,0) NOT NULL ENABLE
   ) NOCOMPRESS NOLOGGING;
   
   ----------------------------

  Drop table  "Jd1dta"."DM_TARGET_TABLES" ;
 CREATE TABLE "Jd1dta"."DM_TARGET_TABLES" 
   (	"MODULE_NAME" VARCHAR2(20 CHAR), 
	"JOBNAME" VARCHAR2(20 CHAR), 
	"TARGET_TABLE" VARCHAR2(20 CHAR),
    "INDEX_NAME" VARCHAR2(100 CHAR),
    "VALID_FLG" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
 NOCOMPRESS NOLOGGING;

-------------------
Drop table  "Jd1dta"."DM_INDEX_SCRIPTS" ;
 CREATE TABLE "Jd1dta"."DM_INDEX_SCRIPTS" 
   (	"MODULE_NAME" VARCHAR2(20 CHAR), 
	"JOBNAME" VARCHAR2(20 CHAR),
    "TABLE_NAME" VARCHAR2(50 CHAR), 
	"INDEX_NAME" VARCHAR2(50 CHAR), 
	"INDX_SCRIPT" VARCHAR2(1000 CHAR), 
	"DTIME" TIMESTAMP (6) DEFAULT systimestamp
   ) NOCOMPRESS NOLOGGING;
------------------------
Drop table  "Jd1dta"."DM_MAIL_ALERT" ;
  CREATE TABLE "Jd1dta"."DM_MAIL_ALERT" 
   (	"BATCH_NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) NOCOMPRESS NOLOGGING;

------------------------------------
create index DM_gchd_I_1 on CHDRPF(chdrnum);

-----------------------------------------
-- Below changes to improve performance -- ZJNPG-6619
drop index gch_colm;
Create index gch_colm on gchppf (zcolmcls);

--------------------------------------
--JobCode patching
   drop table DMPACLJOBPRTY;

	CREATE TABLE Jd1dta."DMPACLJOBPRTY" 
   (	
    "UNIQUEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"STAGECLNTNO" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"ZIGVALUE" VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "EFFDATE" NUMBER(8,0) NOT NULL ENABLE,	
	"OCCPCODE" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"ZOCCDSC" VARCHAR2(50 CHAR) ,
	"OCCPCLAS" VARCHAR2(2 CHAR), 
	"ZWORKPLCE" VARCHAR2(25 CHAR), 
	"ZENDCDE" VARCHAR2(20 CHAR)  NOT NULL ENABLE, 
	"POLICYSTATUS" VARCHAR2(2 CHAR)  NOT NULL ENABLE, 
	"POLICYTYPE" VARCHAR2(2 CHAR)  NOT NULL ENABLE, 
	"PRIORTY" VARCHAR2(1 CHAR)  NOT NULL ENABLE, 
	"ZINSTYP" VARCHAR2(3 CHAR)  NOT NULL ENABLE, 
	"VALIDFLG" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"DATIME" TIMESTAMP (6)
   );
   
   CREATE INDEX DMPACLJOBPRTY_1 ON DMPACLJOBPRTY(STAGECLNTNO,ZIGVALUE);
   CREATE INDEX DMPACLJOBPRTY_2 ON DMPACLJOBPRTY(OCCPCODE);
 -------------------------------

-----No Logging ALTER:START
alter table DM_BILLINST_RECON_DET nologging;
alter table DM_CLIENT_BANK_RECON_DET nologging;
alter table DM_DATA_VALIDATION_ATTRIB nologging;
alter table DM_DV_RECON_DETAIL nologging;
alter table DM_DV_RECON_SUMMARY nologging;
alter table DM_MASTER_POL_RECON_DET nologging;
alter table DM_MEM_IND_RECON_DET nologging;
alter table DM_POL_BILLREF_RECON_DET nologging;
alter table DM_POL_COLLRES_RECON_DET nologging;
alter table DM_POL_DISHNR_RECON_DET nologging;
alter table DM_POL_MIHIS_RECON_DET nologging;
alter table DM_POL_RNWL_DET_RECON_DET nologging;
alter table DM_TEMP_POLHIST nologging;
alter table DM2_DMIG_DATA_CNT nologging;
alter table DMBARGSPF nologging;
alter table DMBERPF nologging;
alter table DMBMONPF nologging;
alter table DMDEFVALPF nologging;
alter table DMIGODMVERSIONHIS nologging;
alter table DMIGTITDMGAGENTPJ nologging;
alter table DMIGTITDMGAPIRNO nologging;
alter table DMIGTITDMGBILL1 nologging;
alter table DMIGTITDMGBILL2 nologging;
alter table DMIGTITDMGCLNTBANK nologging;
alter table DMIGTITDMGCLNTCORP nologging;
alter table DMIGTITDMGCLTRNHIS nologging;
alter table DMIGTITDMGCOLRES nologging;
alter table DMIGTITDMGLETTER nologging;
alter table DMIGTITDMGMASPOL nologging;
alter table DMIGTITDMGMBRINDP1 nologging;
alter table DMIGTITDMGMBRINDP2 nologging;
alter table DMIGTITDMGMBRINDP3 nologging;
alter table DMIGTITDMGPOLTRNH nologging;
alter table DMIGTITDMGREF1 nologging;
alter table DMIGTITDMGREF2 nologging;
alter table DMIGTITDMGRNWDT1 nologging;
alter table DMIGTITDMGRNWDT1_INT nologging;
alter table DMIGTITDMGRNWDT2 nologging;
alter table DMIGTITDMGRNWDT2_INT nologging;
alter table DMIGTITNYCLT nologging;
alter table DMPANAYOSEVIEW nologging;
alter table DMPRFXPF nologging;
alter table DMPVALPF nologging;
alter table DMUNIQUENOUPDT nologging;
alter table IG_DM_MASTERPOL nologging;
alter table IG_TITDMGPOLTRNH nologging;
alter table PAZDMPPF nologging;
alter table ZDMBKPAUDCLNT nologging;
alter table ZDMBKPCLNT nologging;
alter table ZDMBKPZCLN nologging;
alter table ZDMBKPZINS nologging;
alter table ZDMBKPZTRA nologging;


-----No Logging ALTER:END

----Init Trans 5 :START---
alter table DM_BILLINST_RECON_DET  MOVE INITRANS 5;
alter table DM_CLIENT_BANK_RECON_DET  MOVE INITRANS 5;
alter table DM_DATA_VALIDATION_ATTRIB  MOVE INITRANS 5;
alter table DM_DV_RECON_DETAIL  MOVE INITRANS 5;
alter table DM_DV_RECON_SUMMARY  MOVE INITRANS 5;
alter table DM_MASTER_POL_RECON_DET  MOVE INITRANS 5;
alter table DM_MEM_IND_RECON_DET  MOVE INITRANS 5;
alter table DM_POL_BILLREF_RECON_DET  MOVE INITRANS 5;
alter table DM_POL_COLLRES_RECON_DET  MOVE INITRANS 5;
alter table DM_POL_DISHNR_RECON_DET  MOVE INITRANS 5;
alter table DM_POL_MIHIS_RECON_DET  MOVE INITRANS 5;
alter table DM_POL_RNWL_DET_RECON_DET  MOVE INITRANS 5;
alter table DM_TEMP_POLHIST  MOVE INITRANS 5;
alter table DM2_DMIG_DATA_CNT  MOVE INITRANS 5;
alter table DMBARGSPF  MOVE INITRANS 5;
alter table DMBERPF  MOVE INITRANS 5;
alter table DMBMONPF  MOVE INITRANS 5;
alter table DMDEFVALPF  MOVE INITRANS 5;
alter table DMIGODMVERSIONHIS  MOVE INITRANS 5;
alter table DMIGTITDMGAGENTPJ  MOVE INITRANS 5;
alter table DMIGTITDMGAPIRNO  MOVE INITRANS 5;
alter table DMIGTITDMGBILL1  MOVE INITRANS 5;
alter table DMIGTITDMGBILL2  MOVE INITRANS 5;
alter table DMIGTITDMGCLNTBANK  MOVE INITRANS 5;
alter table DMIGTITDMGCLNTCORP  MOVE INITRANS 5;
alter table DMIGTITDMGCLTRNHIS  MOVE INITRANS 5;
alter table DMIGTITDMGCOLRES  MOVE INITRANS 5;
alter table DMIGTITDMGLETTER  MOVE INITRANS 5;
alter table DMIGTITDMGMASPOL  MOVE INITRANS 5;
alter table DMIGTITDMGMBRINDP1  MOVE INITRANS 5;
alter table DMIGTITDMGMBRINDP2  MOVE INITRANS 5;
alter table DMIGTITDMGMBRINDP3  MOVE INITRANS 5;
alter table DMIGTITDMGPOLTRNH  MOVE INITRANS 5;
alter table DMIGTITDMGREF1  MOVE INITRANS 5;
alter table DMIGTITDMGREF2  MOVE INITRANS 5;
alter table DMIGTITDMGRNWDT1  MOVE INITRANS 5;
alter table DMIGTITDMGRNWDT1_INT  MOVE INITRANS 5;
alter table DMIGTITDMGRNWDT2  MOVE INITRANS 5;
alter table DMIGTITDMGRNWDT2_INT  MOVE INITRANS 5;
alter table DMIGTITNYCLT  MOVE INITRANS 5;
alter table DMPANAYOSEVIEW  MOVE INITRANS 5;
alter table DMPRFXPF  MOVE INITRANS 5;
alter table DMPVALPF  MOVE INITRANS 5;
alter table DMUNIQUENOUPDT  MOVE INITRANS 5;
alter table IG_DM_MASTERPOL  MOVE INITRANS 5;
alter table IG_TITDMGPOLTRNH  MOVE INITRANS 5;
alter table PAZDMPPF  MOVE INITRANS 5;
alter table ZDMBKPAUDCLNT  MOVE INITRANS 5;
alter table ZDMBKPCLNT  MOVE INITRANS 5;
alter table ZDMBKPZCLN  MOVE INITRANS 5;
alter table ZDMBKPZINS  MOVE INITRANS 5;
alter table ZDMBKPZTRA  MOVE INITRANS 5;
alter table AGNTPF MOVE INITRANS 5;
alter table AGPLPF MOVE INITRANS 5;
alter table AUDIT_CLEXPF MOVE INITRANS 5;
alter table AUDIT_CLNT MOVE INITRANS 5;
alter table AUDIT_CLNTPF MOVE INITRANS 5;
alter table AUDIT_CLRRPF MOVE INITRANS 5;
alter table CLBAPF MOVE INITRANS 5;
alter table CLEXPF MOVE INITRANS 5;
alter table CLNTPF MOVE INITRANS 5;
alter table CLRRPF MOVE INITRANS 5;
alter table GBIDPF MOVE INITRANS 5;
alter table GBIHPF MOVE INITRANS 5;
alter table CHDRPF MOVE INITRANS 5;
alter table GCHIPF MOVE INITRANS 5;
alter table GCHPPF MOVE INITRANS 5;
alter table GMHDPF MOVE INITRANS 5;
alter table GMHIPF MOVE INITRANS 5;
alter table GPMDPF MOVE INITRANS 5;
alter table GXHIPF MOVE INITRANS 5;
alter table LETCPF MOVE INITRANS 5;
alter table VERSIONPF MOVE INITRANS 5;
alter table ZACRPF MOVE INITRANS 5;
alter table ZALTPF MOVE INITRANS 5;
alter table ZAPIRNOPF MOVE INITRANS 5;
alter table ZBENFDTLSPF MOVE INITRANS 5;
alter table ZCELINKPF MOVE INITRANS 5;
alter table ZCLEPF MOVE INITRANS 5;
alter table ZCLNPF MOVE INITRANS 5;
alter table ZCPNPF MOVE INITRANS 5;
alter table ZCRHPF MOVE INITRANS 5;
alter table ZCSLPF MOVE INITRANS 5;
alter table ZENCTPF MOVE INITRANS 5;
alter table ZINSDTLSPF MOVE INITRANS 5;
alter table ZMCIPF MOVE INITRANS 5;
alter table ZODMPRMVERPF MOVE INITRANS 5;
alter table ZREPPF MOVE INITRANS 5;
alter table ZRFDPF MOVE INITRANS 5;
alter table ZRNDTCOVPF MOVE INITRANS 5;
alter table ZRNDTDPF MOVE INITRANS 5;
alter table ZRNDTHPF MOVE INITRANS 5;
alter table ZRNDTSUBCOVPF MOVE INITRANS 5;
alter table ZRNWPERDPF MOVE INITRANS 5;
alter table ZSUBCOVDTLS MOVE INITRANS 5;
alter table ZTEMPCOVPF MOVE INITRANS 5;
alter table ZTGMPF MOVE INITRANS 5;
alter table ZTRAPF MOVE INITRANS 5;
alter table ZUCLPF MOVE INITRANS 5;
-----Init Trasn 5 : END-----

create index DM_gchd_I_1 on chdrpf(chdrnum);
create index DM_clntpf_I_1 on Jd1dta.clntpf(validflag,clttype);
create index dm_pazdrrpf_I_1 on Jd1dta.pazdrppf(polnum);
create index dm_dmigtitdmgcltrnhis_I_1 on Jd1dta.dmigtitdmgcltrnhis(transhist);
create index dm_dmigtitdmgcltrnhis_I_2 on Jd1dta.dmigtitdmgcltrnhis(rtrim(zendcde),zkanasnmnor,zkanagnmnor, cltdob,cltsex,cltpcode,cltphone01);
create index dm_ignayoseview_I_1 on Jd1dta.ignayoseview(rtrim(zendcde),zkanasnmnor,zkanagnmnor, cltdob,cltsex,cltpcode,rmblphone);
create index dm_dmpanayoseview_I_1 on Jd1dta.dmpanayoseview(rtrim(zendcde),zkanasnmnor,zkanagnmnor, cltdob,cltsex,cltpcode,rmblphone);
create index Dm_DMIGTITDMGMBRINDP1_I1 on DMIGTITDMGMBRINDP1(polnum);
create index DM_PAZDCHPF_I1 on PAZDCHPF(ZENTITY);
create index DM_PAZDCRPF_I1 on PAZDCRPF(ZENTITY);
create index DM_PAZDLTPF_I1 on PAZDLTPF(CHDRNUM, HLETTYPE, LREQDATE, ZLETVERN);
create index DM_PAZDMPPF_I1 on PAZDMPPF(ZENTITY);
create index DM_PAZDPCPF_I1 on PAZDPCPF(ZENTITY, MBRNO, DPNTNO, PRODTYP, EFFDATE);
create index DM_PAZDPDPF_I1 on PAZDPDPF(OLDCHDRNUM);
create index DM_PAZDPTPF_I1 on PAZDPTPF(ZENTITY, ZSEQNO, TRANNO, EFFDATE, MBRNO, ZINSROLE);
create index DM_PAZDRFPF_I1 on PAZDRFPF(ZENTITY,CHDRNUM );
create index DM_PAZDRNPF_I1 on PAZDRNPF(ZENTITY, MBRNO, ZINSTYPE, ZAPIRNO);
create index DM_PAZDROPF_I1 on PAZDROPF(ZENTITY);
create index DM_PAZDROPF_I2 on PAZDROPF(PREFIX);
create index DM_PAZDROPF_I3 on PAZDROPF(ZIGVALUE);
create index DM_pazdclpf_I1 on pazdclpf(ZIGVALUE);




