create or replace type APM_DBMASK_AUDIT_CLNTPF_obj as object(
	   UNIQUE_NUMBER	   NUMBER(18,0)				,
       OLDSURNAME			VARCHAR2(30 CHAR)            ,
       OLDGIVNAME			VARCHAR2(20 CHAR)            ,
       OLDCLTPHONE01		VARCHAR2(16 CHAR)            ,
       OLDCLTPHONE02		VARCHAR2(16 CHAR)            ,
       OLDFAXNO				VARCHAR2(16 CHAR)            ,
       OLDLGIVNAME			VARCHAR2(60 CHAR)    ,
       OLDKANJISURNAME			VARCHAR2(60 CHAR)    ,
       OLDKANJIGIVNAME			VARCHAR2(60 CHAR)    ,
       OLDKANJICLTADDR01	VARCHAR2(30 CHAR)            ,
       OLDKANJICLTADDR02	VARCHAR2(30 CHAR)            ,
       OLDKANJICLTADDR03	VARCHAR2(30 CHAR)            ,
       OLDKANJICLTADDR04	VARCHAR2(30 CHAR)            ,
       OLDKANJICLTADDR05	VARCHAR2(30 CHAR)            ,
       OLDZKANASNM			VARCHAR2(60 CHAR)    ,
       OLDZKANAGNM			VARCHAR2(60 CHAR)    ,
       OLDZKANADDR01		VARCHAR2(60 CHAR)        ,
       OLDZKANADDR02		VARCHAR2(60 CHAR)        ,
       OLDZKANADDR03		VARCHAR2(60 CHAR)        ,
       OLDZKANADDR04		VARCHAR2(60 CHAR)        ,
       OLDZKANADDR05		VARCHAR2(60 CHAR)        ,
       OLDZADDRCD			VARCHAR2(11 CHAR)        ,
       OLDZKANASNMNOR		VARCHAR2(60 CHAR)        ,
       OLDZKANAGNMNOR		VARCHAR2(60 CHAR)        ,
       NEWSURNAME			VARCHAR2(30 CHAR)            ,
       NEWGIVNAME			VARCHAR2(20 CHAR)            ,
       NEWCLTPHONE01		VARCHAR2(16 CHAR)            ,
       NEWCLTPHONE02		VARCHAR2(16 CHAR)            ,
       NEWFAXNO				VARCHAR2(16 CHAR)            ,
       NEWLSURNAME			VARCHAR2(60 CHAR)    ,
       NEWLGIVNAME			VARCHAR2(60 CHAR)    ,
       NEWKANJISURNAME			VARCHAR2(60 CHAR)    ,
       NEWKANJIGIVNAME			VARCHAR2(60 CHAR)    ,
       NEWKANJICLTADDR01	VARCHAR2(30 CHAR)            ,
       NEWKANJICLTADDR02	VARCHAR2(30 CHAR)            ,
       NEWKANJICLTADDR03	VARCHAR2(30 CHAR)            ,
       NEWKANJICLTADDR04	VARCHAR2(30 CHAR)            ,
       NEWKANJICLTADDR05	VARCHAR2(30 CHAR)            ,
       NEWZKANASNM			VARCHAR2(60 CHAR)    ,
       NEWZKANAGNM			VARCHAR2(60 CHAR)    ,
       NEWZKANADDR01		VARCHAR2(60 CHAR)        ,
       NEWZKANADDR02		VARCHAR2(60 CHAR)        ,
       NEWZKANADDR03		VARCHAR2(60 CHAR)        ,
       NEWZKANADDR04		VARCHAR2(60 CHAR)        ,
       NEWZKANADDR05		VARCHAR2(60 CHAR)        ,
       NEWZADDRCD			VARCHAR2(11 CHAR)        ,
       NEWZKANASNMNOR		VARCHAR2(60 CHAR)        ,
       NEWZKANAGNMNOR		VARCHAR2(60 CHAR)     ,
	  OLDLSURNAME            VARCHAR2(60 CHAR)
);
/  
create or replace type APM_DBMASK_AUDIT_CLNTPF_tab as table of APM_DBMASK_AUDIT_CLNTPF_obj;
/
/***************** Pipeline approach*******************************************/
create or replace function APM_DBMASK_AUDIT_CLNTPF_pip return  APM_DBMASK_AUDIT_CLNTPF_tab pipelined
PARALLEL_ENABLE
as
  begin
  for idx in (
  select
 UNIQUE_NUMBER	,
 OLDSURNAME		,
 OLDGIVNAME		,
 OLDCLTPHONE01	,
 OLDCLTPHONE02	,
 OLDFAXNO		,
 OLDLGIVNAME	,
 OLDKANJISURNAME,
 OLDKANJIGIVNAME,
 OLDKANJICLTADDR01,
 OLDKANJICLTADDR02,
 OLDKANJICLTADDR03,
 OLDKANJICLTADDR04,
 OLDKANJICLTADDR05,
 OLDZKANASNM	,
 OLDZKANAGNM	,
 OLDZKANADDR01	,
 OLDZKANADDR02	,
 OLDZKANADDR03	,
 OLDZKANADDR04	,
 OLDZKANADDR05	,
 OLDZADDRCD		,
 OLDZKANASNMNOR	,
 OLDZKANAGNMNOR	,
 NEWSURNAME		,
 NEWGIVNAME		,
 NEWCLTPHONE01	,
 NEWCLTPHONE02	,
 NEWFAXNO		,
 NEWLSURNAME	,
 NEWLGIVNAME	,
 NEWKANJISURNAME,
 NEWKANJIGIVNAME,
 NEWKANJICLTADDR01,
 NEWKANJICLTADDR02,
 NEWKANJICLTADDR03,
 NEWKANJICLTADDR04,
 NEWKANJICLTADDR05,
 NEWZKANASNM	,
 NEWZKANAGNM	,
 NEWZKANADDR01	,
 NEWZKANADDR02	,
 NEWZKANADDR03	,
 NEWZKANADDR04	,
 NEWZKANADDR05	,
 NEWZADDRCD		,
 NEWZKANASNMNOR	,
 NEWZKANAGNMNOR	,
 OLDLSURNAME
 
  from AUDIT_CLNTPF fetch first 100 percent rows only 
  
 
 )loop
    pipe row(
      APM_DBMASK_AUDIT_CLNTPF_obj( 
 
  idx.UNIQUE_NUMBER	,
 idx.OLDSURNAME		,
 idx.OLDGIVNAME		,
 idx.OLDCLTPHONE01	,
 idx.OLDCLTPHONE02	,
 idx.OLDFAXNO		,
 idx.OLDLGIVNAME	,
 idx.OLDKANJISURNAME,
 idx.OLDKANJIGIVNAME,
 idx.OLDKANJICLTADDR01,
 idx.OLDKANJICLTADDR02,
 idx.OLDKANJICLTADDR03,
 idx.OLDKANJICLTADDR04,
 idx.OLDKANJICLTADDR05,
 idx.OLDZKANASNM	,
 idx.OLDZKANAGNM	,
 idx.OLDZKANADDR01	,
 idx.OLDZKANADDR02	,
 idx.OLDZKANADDR03	,
 idx.OLDZKANADDR04	,
 idx.OLDZKANADDR05	,
 idx.OLDZADDRCD		,
 idx.OLDZKANASNMNOR	,
 idx.OLDZKANAGNMNOR	,
 idx.NEWSURNAME		,
 idx.NEWGIVNAME		,
 idx.NEWCLTPHONE01	,
 idx.NEWCLTPHONE02	,
 idx.NEWFAXNO		,
 idx.NEWLSURNAME	,
 idx.NEWLGIVNAME	,
 idx.NEWKANJISURNAME,
 idx.NEWKANJIGIVNAME,
 idx.NEWKANJICLTADDR01,
 idx.NEWKANJICLTADDR02,
 idx.NEWKANJICLTADDR03,
 idx.NEWKANJICLTADDR04,
 idx.NEWKANJICLTADDR05,
 idx.NEWZKANASNM	,
 idx.NEWZKANAGNM	,
 idx.NEWZKANADDR01	,
 idx.NEWZKANADDR02	,
 idx.NEWZKANADDR03	,
 idx.NEWZKANADDR04	,
 idx.NEWZKANADDR05	,
 idx.NEWZADDRCD		,
 idx.NEWZKANASNMNOR	,
 idx.NEWZKANAGNMNOR	,
 idx.OLDLSURNAME
 )
    );
  end loop;
  return;
end;
/

/*******************************************************************************
*A METHOD TO CALL TableFunction CALL with PARALLEL HINT.
*******************************************************************************/
create or replace procedure APM_DBMASK_writetoAUDIT_CLNTPF(p_dir in VARCHAR2, p_fn in varchar2 )  as
  v_file  UTL_FILE.FILE_TYPE;
  v_sql_res   VARCHAR2(4000);
begin
  v_file := UTL_FILE.FOPEN(p_dir, p_fn, 'w',32767);
  for i in (select/*+parallel(4)*/ * from table(APM_DBMASK_AUDIT_CLNTPF_pip)) loop
    v_sql_res := '"'
	||i.UNIQUE_NUMBER	||'","'
	||i.OLDSURNAME		||'","'
	||i.OLDGIVNAME		||'","'
	||i.OLDCLTPHONE01	||'","'
	||i.OLDCLTPHONE02	||'","'
	||i.OLDFAXNO		||'","'
	||i.OLDLGIVNAME	||'","'
	||i.OLDKANJISURNAME||'","'
	||i.OLDKANJIGIVNAME||'","'
	||i.OLDKANJICLTADDR01||'","'
	||i.OLDKANJICLTADDR02||'","'
	||i.OLDKANJICLTADDR03||'","'
	||i.OLDKANJICLTADDR04||'","'
	||i.OLDKANJICLTADDR05||'","'
	||i.OLDZKANASNM	||'","'
	||i.OLDZKANAGNM	||'","'
	||i.OLDZKANADDR01	||'","'
	||i.OLDZKANADDR02	||'","'
	||i.OLDZKANADDR03	||'","'
	||i.OLDZKANADDR04	||'","'
	||i.OLDZKANADDR05	||'","'
	||i.OLDZADDRCD		||'","'
	||i.OLDZKANASNMNOR	||'","'
	||i.OLDZKANAGNMNOR	||'","'
	||i.NEWSURNAME		||'","'
	||i.NEWGIVNAME		||'","'
	||i.NEWCLTPHONE01	||'","'
	||i.NEWCLTPHONE02	||'","'
	||i.NEWFAXNO		||'","'
	||i.NEWLSURNAME	||'","'
	||i.NEWLGIVNAME	||'","'
	||i.NEWKANJISURNAME||'","'
	||i.NEWKANJIGIVNAME||'","'
	||i.NEWKANJICLTADDR01||'","'
	||i.NEWKANJICLTADDR02||'","'
	||i.NEWKANJICLTADDR03||'","'
	||i.NEWKANJICLTADDR04||'","'
	||i.NEWKANJICLTADDR05||'","'
	||i.NEWZKANASNM	||'","'
	||i.NEWZKANAGNM	||'","'
	||i.NEWZKANADDR01	||'","'
	||i.NEWZKANADDR02	||'","'
	||i.NEWZKANADDR03	||'","'
	||i.NEWZKANADDR04	||'","'
	||i.NEWZKANADDR05	||'","'
	||i.NEWZADDRCD		||'","'
	||i.NEWZKANASNMNOR	||'","'
	||i.NEWZKANAGNMNOR	||'","'
	||i.OLDLSURNAME|| '"';
	
    --UTL_FILE.PUT_LINE(v_file, v_sql_res );
UTL_FILE.put_line(v_file,convert(v_sql_res,'JA16SJIS','AL32UTF8'));
  end loop;
  UTL_FILE.FCLOSE(v_file);
end;
/



