drop table AUDIT_CLNTPF_TEMP;
/
CREATE TABLE "AUDIT_CLNTPF_TEMP" 
(
       "UNIQUE_NUMBER"    NUMBER(18,0),
       "OLDSURNAME" VARCHAR2(30 CHAR)            ,
       "OLDGIVNAME" VARCHAR2(20 CHAR)            ,
       "OLDCLTPHONE01" VARCHAR2(16 CHAR)            ,
       "OLDCLTPHONE02" VARCHAR2(16 CHAR)            ,
       "OLDFAXNO" VARCHAR2(16 CHAR)            ,
       "OLDLGIVNAME" VARCHAR2(60 CHAR)    ,
       "OLDKANJISURNAME" VARCHAR2(60 CHAR)    ,
       "OLDKANJIGIVNAME" VARCHAR2(60 CHAR)    ,
       "OLDKANJICLTADDR01" VARCHAR2(30 CHAR)            ,
       "OLDKANJICLTADDR02" VARCHAR2(30 CHAR)            ,
       "OLDKANJICLTADDR03" VARCHAR2(30 CHAR)            ,
       "OLDKANJICLTADDR04" VARCHAR2(30 CHAR)            ,
       "OLDKANJICLTADDR05" VARCHAR2(30 CHAR)            ,
       "OLDZKANASNM" VARCHAR2(60 CHAR)    ,
       "OLDZKANAGNM" VARCHAR2(60 CHAR)    ,
       "OLDZKANADDR01" VARCHAR2(60 CHAR)        ,
       "OLDZKANADDR02" VARCHAR2(60 CHAR)        ,
       "OLDZKANADDR03" VARCHAR2(60 CHAR)        ,
       "OLDZKANADDR04" VARCHAR2(60 CHAR)        ,
       "OLDZKANADDR05" VARCHAR2(60 CHAR)        ,
       "OLDZADDRCD" VARCHAR2(11 CHAR)        ,
       "OLDZKANASNMNOR" VARCHAR2(60 CHAR)        ,
       "OLDZKANAGNMNOR" VARCHAR2(60 CHAR)        ,
       "NEWSURNAME" VARCHAR2(30 CHAR)            ,
       "NEWGIVNAME" VARCHAR2(20 CHAR)            ,
       "NEWCLTPHONE01" VARCHAR2(16 CHAR)            ,
       "NEWCLTPHONE02" VARCHAR2(16 CHAR)            ,
       "NEWFAXNO" VARCHAR2(16 CHAR)            ,
       "NEWLSURNAME" VARCHAR2(60 CHAR)    ,
       "NEWLGIVNAME" VARCHAR2(60 CHAR)    ,
       "NEWKANJISURNAME" VARCHAR2(60 CHAR)    ,
       "NEWKANJIGIVNAME" VARCHAR2(60 CHAR)    ,
       "NEWKANJICLTADDR01" VARCHAR2(30 CHAR)            ,
       "NEWKANJICLTADDR02" VARCHAR2(30 CHAR)            ,
       "NEWKANJICLTADDR03" VARCHAR2(30 CHAR)            ,
       "NEWKANJICLTADDR04" VARCHAR2(30 CHAR)            ,
       "NEWKANJICLTADDR05" VARCHAR2(30 CHAR)            ,
       "NEWZKANASNM" VARCHAR2(60 CHAR)    ,
       "NEWZKANAGNM" VARCHAR2(60 CHAR)    ,
       "NEWZKANADDR01" VARCHAR2(60 CHAR)        ,
       "NEWZKANADDR02" VARCHAR2(60 CHAR)        ,
       "NEWZKANADDR03" VARCHAR2(60 CHAR)        ,
       "NEWZKANADDR04" VARCHAR2(60 CHAR)        ,
       "NEWZKANADDR05" VARCHAR2(60 CHAR)        ,
       "NEWZADDRCD" VARCHAR2(11 CHAR)        ,
       "NEWZKANASNMNOR" VARCHAR2(60 CHAR)        ,
       "NEWZKANAGNMNOR" VARCHAR2(60 CHAR)  ,
	   "OLDLSURNAME"	   VARCHAR2(60 CHAR)
              );
/
			  
 create index audit_clntpf_tempIDX on audit_clntpf_temp(unique_number); 
create or replace procedure  APM_DBMASK_MERG_AUDIT_CLNTPF
authid current_user
as 

l_sql_stmt varchar2(4000 char);
l_status NUMBER;
l_chunk_stmt varchar2(2000 char);
cont number;
cont1 number;

begin

select count(*) into cont1 from AUDIT_CLNTPF_TEMP;
if(cont1 >0)then

Delete from audit_clntpf_temp a where rowid not in (select max(rowid) from audit_clntpf_temp b where b.unique_number=a.unique_number);

SELECT COUNT(*)
INTO cont
FROM user_parallel_execute_tasks
WHERE task_name = 'UPDATE_AUDIT_CLNTPF_MERGE';

IF cont > 0 THEN
  DBMS_PARALLEL_EXECUTE.DROP_TASK('UPDATE_AUDIT_CLNTPF_MERGE');
END  IF;

    DBMS_PARALLEL_EXECUTE.CREATE_TASK('UPDATE_AUDIT_CLNTPF_MERGE');
    DBMS_PARALLEL_EXECUTE.CREATE_CHUNKS_BY_NUMBER_COL ('UPDATE_AUDIT_CLNTPF_MERGE','VM1DTA','AUDIT_CLNTPF_TEMP','UNIQUE_NUMBER',42000);
        
    /*l_chunk_stmt:= 'SELECT start_id, end_id FROM AUDIT_CLNTPF_CHUNKS';
    DBMS_PARALLEL_EXECUTE.CREATE_CHUNKS_BY_SQL (
    task_name => 'UPDATE_AUDIT_CLNTPF_MERGE'
   , sql_stmt        => l_chunk_stmt
   , by_rowid       => FALSE
                      ); */
        
    l_sql_stmt := 'MERGE  INTO AUDIT_CLNTPF a USING 
    (select * from AUDIT_CLNTPF_TEMP where unique_number between :start_id and :end_id) b
    ON (a.UNIQUE_NUMBER = b.UNIQUE_NUMBER)
    WHEN MATCHED THEN UPDATE SET					
    	A.OLDSURNAME=B.OLDSURNAME,
        A.OLDGIVNAME=B.OLDGIVNAME,
        A.OLDCLTPHONE01=B.OLDCLTPHONE01,
        A.OLDCLTPHONE02=B.OLDCLTPHONE02,
        A.OLDFAXNO=B.OLDFAXNO,       
        A.OLDLGIVNAME=B.OLDLGIVNAME,
        A.OLDKANJISURNAME=B.OLDKANJISURNAME,
        A.OLDKANJIGIVNAME=B.OLDKANJIGIVNAME,
        A.OLDKANJICLTADDR01=B.OLDKANJICLTADDR01,
        A.OLDKANJICLTADDR02=B.OLDKANJICLTADDR02,
        A.OLDKANJICLTADDR03=B.OLDKANJICLTADDR03,
        A.OLDKANJICLTADDR04=B.OLDKANJICLTADDR04,
        A.OLDKANJICLTADDR05=B.OLDKANJICLTADDR05,
        A.OLDZKANASNM=B.OLDZKANASNM,
        A.OLDZKANAGNM=B.OLDZKANAGNM,
        A.OLDZKANADDR01=B.OLDZKANADDR01,
        A.OLDZKANADDR02=B.OLDZKANADDR02,
        A.OLDZKANADDR03=B.OLDZKANADDR03,
        A.OLDZKANADDR04=B.OLDZKANADDR04,
        A.OLDZKANADDR05=B.OLDZKANADDR05,
        A.OLDZADDRCD=B.OLDZADDRCD,
        A.OLDZKANASNMNOR=B.OLDZKANASNMNOR,
        A.OLDZKANAGNMNOR=B.OLDZKANAGNMNOR,
        A.NEWSURNAME=B.NEWSURNAME,
        A.NEWGIVNAME=B.NEWGIVNAME,
        A.NEWCLTPHONE01=B.NEWCLTPHONE01,
        A.NEWCLTPHONE02=B.NEWCLTPHONE02,
        A.NEWFAXNO=B.NEWFAXNO,
        A.NEWLSURNAME=B.NEWLSURNAME,
        A.NEWLGIVNAME=B.NEWLGIVNAME,
        A.NEWKANJISURNAME=B.NEWKANJISURNAME,
        A.NEWKANJIGIVNAME=B.NEWKANJIGIVNAME,
        A.NEWKANJICLTADDR01=B.NEWKANJICLTADDR01,
        A.NEWKANJICLTADDR02=B.NEWKANJICLTADDR02,
        A.NEWKANJICLTADDR03=B.NEWKANJICLTADDR03,
        A.NEWKANJICLTADDR04=B.NEWKANJICLTADDR04,
        A.NEWKANJICLTADDR05=B.NEWKANJICLTADDR05,
        A.NEWZKANASNM=B.NEWZKANASNM,
        A.NEWZKANAGNM=B.NEWZKANAGNM,
        A.NEWZKANADDR01=B.NEWZKANADDR01,
        A.NEWZKANADDR02=B.NEWZKANADDR02,
        A.NEWZKANADDR03=B.NEWZKANADDR03,
        A.NEWZKANADDR04=B.NEWZKANADDR04,
        A.NEWZKANADDR05=B.NEWZKANADDR05,
        A.NEWZADDRCD=B.NEWZADDRCD,
        A.NEWZKANASNMNOR=B.NEWZKANASNMNOR,
        A.NEWZKANAGNMNOR=B.NEWZKANASNMNOR,
	A.OLDLSURNAME = B.OLDLSURNAME';
    
    dbms_parallel_execute.run_task(
        task_name        =>'UPDATE_AUDIT_CLNTPF_MERGE',
        sql_stmt         => l_sql_stmt,
        language_flag    => dbms_sql.native,
        parallel_level   => 24); ---Keep this number low may be 2 or max 5.
    
    l_status := dbms_parallel_execute.task_status('UPDATE_AUDIT_CLNTPF_MERGE');
    DBMS_OUTPUT.PUT_LINE('UPDATE_AUDIT_CLNTPF_MERGE completed! Status:'||l_status);
    DBMS_PARALLEL_EXECUTE.DROP_TASK('UPDATE_AUDIT_CLNTPF_MERGE');
    commit;
end if;
end;
/