CREATE OR REPLACE PROCEDURE REFERESH_MV
IS
BEGIN
     DBMS_MVIEW.REFRESH('VM1DTA.MV_ZENCIPF', 'C', '',TRUE,FALSE,0,0,0,FALSE);
     DBMS_MVIEW.REFRESH('VM1DTA.MV_ZENDRPF', 'C', '',TRUE,FALSE,0,0,0,FALSE);
     DBMS_MVIEW.REFRESH('VM1DTA.MV_ZMCIPF', 'C', '',TRUE,FALSE,0,0,0,FALSE);
     DBMS_MVIEW.REFRESH('VM1DTA.MV_ZENCIPF', 'F', '',TRUE,FALSE,0,0,0,FALSE);
     DBMS_MVIEW.REFRESH('VM1DTA.MV_ZENDRPF', 'F', '',TRUE,FALSE,0,0,0,FALSE);
     DBMS_MVIEW.REFRESH('VM1DTA.MV_ZMCIPF', 'F', '',TRUE,FALSE,0,0,0,FALSE);

END REFERESH_MV ;
/