sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/AUDIT_ASRDPF.ctl' data='/opt/ig/hitoku/user/output/AUDIT_ASRDPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/AUDIT_CLEXPF.ctl' data='/opt/ig/hitoku/user/output/AUDIT_CLEXPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/AUDIT_CLNT.ctl' data='/opt/ig/hitoku/user/output/AUDIT_CLNT.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/AUDIT_CLNTPF.ctl' data='/opt/ig/hitoku/user/output/AUDIT_CLNTPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/BABRPF.ctl' data='/opt/ig/hitoku/user/output/BABRPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/CLBAPF.ctl' data='/opt/ig/hitoku/user/output/CLBAPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/CLEXPF.ctl' data='/opt/ig/hitoku/user/output/CLEXPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/CLNTPF.ctl' data='/opt/ig/hitoku/user/output/CLNTPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/CLNTQY.ctl' data='/opt/ig/hitoku/user/output/CLNTQY.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/GMHIPF.ctl' data='/opt/ig/hitoku/user/output/GMHIPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/MIOKPF.ctl' data='/opt/ig/hitoku/user/output/MIOKPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/MV_ZMCIPF.ctl' data='/opt/ig/hitoku/user/output/MV_ZMCIPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/MV_ZMCIPF_CRDT.ctl' data='/opt/ig/hitoku/user/output/MV_ZMCIPF_CRDT.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/NAME.ctl' data='/opt/ig/hitoku/user/output/NAME.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/POLDATATEMP.ctl' data='/opt/ig/hitoku/user/output/POLDATATEMP.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZALTPF.ctl' data='/opt/ig/hitoku/user/output/ZALTPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZCLNPF.ctl' data='/opt/ig/hitoku/user/output/ZCLNPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZCORPF.ctl' data='/opt/ig/hitoku/user/output/ZCORPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZMCIPF.ctl' data='/opt/ig/hitoku/user/output/ZMCIPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZMIEPF.ctl' data='/opt/ig/hitoku/user/output/ZMIEPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZMUPPF.ctl' data='/opt/ig/hitoku/user/output/ZMUPPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZPDAPF.ctl' data='/opt/ig/hitoku/user/output/ZPDAPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZREPPF.ctl' data='/opt/ig/hitoku/user/output/ZREPPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZSTGPF.ctl' data='/opt/ig/hitoku/user/output/ZSTGPF.csv'
sqlldr VM1DTA/XqTEJc9p@jpaigdbp02:1521/IGPRD22 control='/opt/ig/dbmasking/ctl/core/ZVCHPF.ctl' data='/opt/ig/hitoku/user/output/ZVCHPF.csv'
 
exit 0
