
--  DDL for Table TITDMGAGENTPJ
--------------------------------------------------------

 drop table "STAGEDBUSR"."TITDMGAGENTPJ" ;
  CREATE TABLE "STAGEDBUSR"."TITDMGAGENTPJ" 
   (	
   "RECIDXAGENT" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
"ZAREFNUM"   CHAR(8 CHAR)   NOT NULL   ENABLE, 
"AGTYPE"   CHAR(2 CHAR)   NOT NULL   ENABLE, 
"AGNTBR"   CHAR(2 CHAR)   NOT NULL   ENABLE, 
"SRDATE"   NUMBER(8,0)   NOT NULL   ENABLE, 
"DATEEND"   NUMBER(8,0)  ,    
"STCA"      CHAR(3 CHAR) ,     
"RIDESC"   CHAR(30 CHAR)   NOT NULL   ENABLE, 
"AGCLSD"   VARCHAR2(30 CHAR)   NOT NULL   ENABLE, 
"ZREPSTNM"   VARCHAR2(30 CHAR)  , 
"ZAGREGNO"   VARCHAR2(20 CHAR) ,     
"CPYNAME"   VARCHAR2(30 CHAR),      
"ZTRGTFLG"   VARCHAR2(1 CHAR) ,     
"COUNT"       NUMBER(4,0)    ,  
"DCONSIGNEN"    VARCHAR2(30 CHAR)   ,   
"ZCONSIDT"   NUMBER(8,0)     , 
"ZINSTYP01"   CHAR(3 CHAR)   NOT NULL   ENABLE, 
"CMRATE01"   NUMBER(5,2)    default 0 NOT NULL   ENABLE CONSTRAINT CMRATE01_1_to_100 CHECK(CMRATE01  between 0 and  100), 
"ZINSTYP02"   CHAR(3 CHAR)  default ' ',    
"CMRATE02"   NUMBER(5,2)     default 0  CONSTRAINT CMRATE02_1_to_100 CHECK(CMRATE02 between 0 and  100), 
"ZINSTYP03"   CHAR(3 CHAR)   default ' ', 
"CMRATE03"   NUMBER(5,2)     default 0 CONSTRAINT CMRATE03_1_to_100 CHECK(CMRATE03 between 0 and  100), 
"ZINSTYP04"   CHAR(3 CHAR)   default ' ',   
"CMRATE04"   NUMBER(5,2)     default 0 CONSTRAINT CMRATE04_1_to_100 CHECK(CMRATE04  between 0 and  100), 
"ZINSTYP05"   CHAR(3 CHAR)   default ' ',   
"CMRATE05"   NUMBER(5,2)     default 0 CONSTRAINT CMRATE05_1_to_100 CHECK(CMRATE05 between 0 and  100), 
"ZINSTYP06"   CHAR(3 CHAR)  default ' ', 
"CMRATE06"   NUMBER(5,2)     default 0 CONSTRAINT CMRATE06_1_to_100 CHECK(CMRATE06 between 0 and  100), 
"ZINSTYP07"   CHAR(3 CHAR)   default ' ',  
"CMRATE07"   NUMBER(5,2)     default 0 CONSTRAINT CMRATE07_1_to_100 CHECK(CMRATE07 between 0 and  100), 
"ZINSTYP08"   CHAR(3 CHAR)   default ' ',  
"CMRATE08"   NUMBER(5,2)    default 0  CONSTRAINT CMRATE08_1_to_100 CHECK(CMRATE08 between 0 and  100), 
"ZINSTYP09"   CHAR(3 CHAR)   default ' ',  
"CMRATE09"   NUMBER(5,2)     default 0 CONSTRAINT CMRATE09_1_to_100 CHECK(CMRATE09 between 0 and  100), 
"ZINSTYP10"   CHAR(3 CHAR)  default ' ',  
"CMRATE10"   NUMBER(5,2)     default 0 CONSTRAINT CMRATE10_1_to_100 CHECK(CMRATE10 between 0 and  100), 
"CLNTNUM"   CHAR(8 CHAR)   NOT NULL   ENABLE, 
"ZDRAGNT"   VARCHAR2(1 CHAR)   NOT NULL   ENABLE
 );
 
 
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZAREFNUM" 	IS 'OLD AGENT NUMBER                  ';   
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."AGTYPE"   	IS 'AGENT TYPE                        ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."AGNTBR"   	IS 'AGENT BRANCH                      ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."SRDATE"   	IS 'START DATE                        ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."DATEEND"  	IS 'END DATE                          ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."STCA"     	IS 'STATISTICAL CODE A (TERRITORY)    ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."RIDESC"   	IS 'REINSURANCE DESCRIPTION           ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."AGCLSD"   	IS 'AGENT COMMISSION CLASS DESCRIPTION';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZREPSTNM" 	IS 'REPRESENTATIVE NAME               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZAGREGNO" 	IS 'AGENCY REGISTRATION NO            ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CPYNAME"  	IS 'PROXY APPLICATION COMPANY         ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZTRGTFLG" 	IS 'TARGET FLAG                       ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."COUNT"    	IS 'COUNT                             ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."DCONSIGNEN"	IS 'ITEM OF CONSIGNMENT               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZCONSIDT" 	IS 'DATE OF CONSIGNMENT               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP01"	IS 'INSURANCE TYPE  - 1               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE01" 	IS 'COMMISSION RATE - 1               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP02"	IS 'INSURANCE TYPE  - 2               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE02" 	IS 'COMMISSION RATE - 2               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP03"	IS 'INSURANCE TYPE  - 3               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE03" 	IS 'COMMISSION RATE - 3               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP04"	IS 'INSURANCE TYPE  - 4               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE04" 	IS 'COMMISSION RATE - 4               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP05"	IS 'INSURANCE TYPE  - 5               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE05" 	IS 'COMMISSION RATE - 5               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP06"	IS 'INSURANCE TYPE  - 6               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE06" 	IS 'COMMISSION RATE - 6               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP07"	IS 'INSURANCE TYPE  - 7               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE07" 	IS 'COMMISSION RATE - 7               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP08"	IS 'INSURANCE TYPE  - 8               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE08" 	IS 'COMMISSION RATE - 8               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP09"	IS 'INSURANCE TYPE  - 9               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE09" 	IS 'COMMISSION RATE - 9               ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZINSTYP10"	IS 'INSURANCE TYPE  - 10              ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CMRATE10" 	IS 'COMMISSION RATE - 10              ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."CLNTNUM"  	IS 'CLIENT NUMBER                     ';
COMMENT ON COLUMN "STAGEDBUSR"."TITDMGAGENTPJ"."ZDRAGNT"  	IS 'Direct Handling                   ';
--------------------------------------------------------
--  DDL for Table TITDMGBILL1
--------------------------------------------------------

 drop table "STAGEDBUSR"."TITDMGBILL1" ;
  CREATE TABLE "STAGEDBUSR"."TITDMGBILL1" 
   (	"RECIDXBILL1" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"TRREFNUM" VARCHAR2(15 CHAR), 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"PRBILFDT" NUMBER(8,0), 
	"PRBILTDT" NUMBER(8,0), 
	"PREMOUT" VARCHAR2(1 CHAR), 
	"ZCOLFLAG" VARCHAR2(1 CHAR), 
	"ZACMCLDT" NUMBER(8,0), 
	"ZPOSBDSM" NUMBER(2,0), 
	"ZPOSBDSY" NUMBER(4,0), 
	"ENDSERCD" VARCHAR2(2 CHAR), 
	"TFRDATE" NUMBER(8,0), 
	"POSTING" VARCHAR2(1 CHAR),
	"NRFLAG" VARCHAR2(1 CHAR),
	"ZPDATATXFLG" VARCHAR2(1 CHAR),
	"TRANNO" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGBILL2
--------------------------------------------------------

 drop table "STAGEDBUSR"."TITDMGBILL2" ;
  CREATE TABLE "STAGEDBUSR"."TITDMGBILL2" 
   (	"RECIDXBILL2" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"TRREFNUM" VARCHAR2(15 CHAR), 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"TRANNO" NUMBER(5,0), 
	"PRODTYP" VARCHAR2(4 CHAR), 
	"BPREM" NUMBER(15,2), 
	"GAGNTSEL01" VARCHAR2(8 CHAR), 
	"GAGNTSEL02" VARCHAR2(8 CHAR), 
	"GAGNTSEL03" VARCHAR2(8 CHAR), 
	"GAGNTSEL04" VARCHAR2(8 CHAR), 
	"GAGNTSEL05" VARCHAR2(8 CHAR), 
	"CMRATE01" NUMBER(5,2), 
	"CMRATE02" NUMBER(5,2), 
	"CMRATE03" NUMBER(5,2), 
	"CMRATE04" NUMBER(5,2), 
	"CMRATE05" NUMBER(5,2), 
	"COMMN01" NUMBER(17,2), 
	"COMMN02" NUMBER(17,2), 
	"COMMN03" NUMBER(17,2), 
	"COMMN04" NUMBER(17,2), 
	"COMMN05" NUMBER(17,2), 
	"ZAGTGPRM01" NUMBER(17,2), 
	"ZAGTGPRM02" NUMBER(17,2), 
	"ZAGTGPRM03" NUMBER(17,2), 
	"ZAGTGPRM04" NUMBER(17,2), 
	"ZAGTGPRM05" NUMBER(17,2), 
	"ZCOLLFEE01" NUMBER(17,2),
	"MBRNO" VARCHAR2(5 CHAR), 
	"DPNTNO" VARCHAR2(2 CHAR),
	"PRBILFDT" NUMBER(8,0), 
	"REFNUMCHUNK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGCAMPCDE
--------------------------------------------------------
drop table "STAGEDBUSR"."TITDMGCAMPCDE" ;
CREATE TABLE "STAGEDBUSR"."TITDMGCAMPCDE" 
   (	"RECIDXCAMP" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ZCMPCODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"ZPETNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"ZPOLCLS" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"ZENDCODE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"GPOLTYP" VARCHAR2(3 CHAR), 
	"ZAGPTID" VARCHAR2(8 CHAR), 
	"RCDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"ZCMPFRM" NUMBER(8,0) NOT NULL ENABLE, 
	"ZCMPTO" NUMBER(8,0) NOT NULL ENABLE, 
	"ZMAILDAT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZACLSDAT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZDLVCDDT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZVEHICLE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"ZSTAGE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"ZSCHEME01" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZSCHEME02" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZCRTUSR" VARCHAR2(10 CHAR), 
	"ZAPPDATE" NUMBER(8,0), 
	"ZCCODIND" VARCHAR2(1 CHAR), 
	"EFFDATE" NUMBER(8,0), 
	"STATUS" VARCHAR2(2 CHAR), 
	 CONSTRAINT "PK1_TITDMGCAMPCDE" PRIMARY KEY ("ZCMPCODE"),
   CONSTRAINT "COND_TITDMGCAMPCDE" check((zpolcls = 'G' and CHDRNUM is not null) or (zpolcls = 'I' and ZAGPTID is not null and GPOLTYP is not NULL))
   );
--------------------------------------------------------
--  DDL for Table TITDMGCLNTBANK
--------------------------------------------------------

 drop table "STAGEDBUSR"."TITDMGCLNTBANK" ;

   CREATE TABLE "STAGEDBUSR"."TITDMGCLNTBANK" 
   (	"RECIDXCLBK" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"REFNUM" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"SEQNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"CURRTO" NUMBER(8,0), 
	"BANKCD" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"BRANCHCD" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"FACTHOUS" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"BANKACCKEY" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CRDTCARD" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"BANKACCDSC" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"BNKACTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"TRANSHIST" VARCHAR2(1 CHAR) NOT NULL ENABLE
   );

  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGCLNTBANK" ON "STAGEDBUSR"."TITDMGCLNTBANK" ("REFNUM", "SEQNO", "BANKCD", "BRANCHCD", "BANKACCKEY", "CRDTCARD") ;

   
 --------------------------------------------------------
--  DDL for Table TITDMGENDSPCFC
--------------------------------------------------------
  drop table "STAGEDBUSR"."TITDMGENDSPCFC" ;
    CREATE TABLE "STAGEDBUSR"."TITDMGENDSPCFC" 
   (	"RECIDXCLEN" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"REFNUM" VARCHAR2(15 CHAR) NOT NULL   ENABLE, 
	"ZENDCDE"       VARCHAR2(20 CHAR) NOT NULL   ENABLE,
	"ZENSPCD01"     VARCHAR2(70 CHAR) ,
	"ZENSPCD02"     VARCHAR2(70 CHAR) ,
	"ZCIFCODE"    VARCHAR2(15 CHAR) 
   );

--------------------------------------------------------
--  DDL for Table TITDMGCLNTCORP
--------------------------------------------------------

  drop table "STAGEDBUSR"."TITDMGCLNTCORP" ;
  
  CREATE TABLE "STAGEDBUSR"."TITDMGCLNTCORP" 
   (	"RECIDXCLCORP" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"CLTTYPE" VARCHAR2(1 CHAR), 
	"CLTADDR01" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CLTADDR02" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CLTADDR03" VARCHAR2(30 CHAR), 
	"CLTADDR04" VARCHAR2(30 CHAR), 
	"ZKANADDR01" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ZKANADDR02" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ZKANADDR03" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ZKANADDR04" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CLTPCODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CLTPHONE01" VARCHAR2(16 CHAR), 
	"CLTPHONE02" VARCHAR2(16 CHAR), 
	"CLTDOBX" NUMBER(8,0), 
	"CLTSTAT" VARCHAR2(2 CHAR), 
	"FAXNO" VARCHAR2(16 CHAR), 
	"LSURNAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ZKANASNM" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CLNTKEY" VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	"AGNTNUM" CHAR(8 BYTE), 
	"MPLNUM" CHAR(8 BYTE), 
	 CONSTRAINT "PK_TITDMGCLNTCORP" PRIMARY KEY ("CLNTKEY", "AGNTNUM", "MPLNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 5 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;

--------------------------------------------------------
--  DDL for Table TITDMGCLNTPRSN
--------------------------------------------------------

 drop table "STAGEDBUSR"."TITDMGCLNTPRSN" ;
  CREATE TABLE "STAGEDBUSR"."TITDMGCLNTPRSN" 
   (	"UNIQUE_NUMBER" NUMBER(18,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"REFNUM" VARCHAR2(15 CHAR), 
	"LSURNAME" VARCHAR2(60 CHAR), 
	"LGIVNAME" VARCHAR2(60 CHAR), 
	"ZKANAGIVNAME" VARCHAR2(60 CHAR), 
	"ZKANASURNAME" VARCHAR2(60 CHAR), 
	"CLTADDR01" VARCHAR2(60 CHAR), 
	"CLTADDR02" VARCHAR2(60 CHAR), 
	"CLTADDR03" VARCHAR2(60 CHAR), 
	"CLTADDR04" VARCHAR2(60 CHAR), 
	"ZKANADDR01" VARCHAR2(30 CHAR), 
	"ZKANADDR02" VARCHAR2(30 CHAR), 
	"ZKANADDR03" VARCHAR2(30 CHAR), 
	"ZKANADDR04" VARCHAR2(30 CHAR), 
	"CLTSEX" VARCHAR2(1 CHAR), 
	"ADDRTYPE" VARCHAR2(1 CHAR), 
	"CLTPHONE01" VARCHAR2(16 CHAR), 
	"CLTPHONE02" VARCHAR2(16 CHAR), 
	"OCCPCODE" VARCHAR2(4 CHAR), 
	"SERVBRH" VARCHAR2(2 CHAR), 
	"CLTDOB" NUMBER(8,0), 
	"ZOCCDSC" VARCHAR2(50 CHAR), 
	"ZWORKPLCE" VARCHAR2(25 CHAR), 
	"TRANSHIST" VARCHAR2(1 CHAR), 
	"ASRF" VARCHAR2(4 CHAR), 
	"CLTPCODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGCLTRNHIS
--------------------------------------------------------
 Drop table "STAGEDBUSR"."TITDMGCLTRNHIS" ;
  CREATE TABLE "STAGEDBUSR"."TITDMGCLTRNHIS" 
   (	
	"RECIDXCLHIS" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"REFNUM" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"ZSEQNO" NUMBER(3,0) NOT NULL ENABLE, 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"LSURNAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"LGIVNAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ZKANAGIVNAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ZKANASURNAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ZKANASNMNOR" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ZKANAGNMNOR" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CLTPCODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CLTADDR01" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CLTADDR02" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CLTADDR03" VARCHAR2(50 CHAR), 
	"ZKANADDR01" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ZKANADDR02" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CLTSEX" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"ADDRTYPE" VARCHAR2(1 CHAR) DEFAULT ' ', 
	"CLTPHONE01" VARCHAR2(16 CHAR) DEFAULT '       ' NOT NULL ENABLE, 
	"CLTPHONE02" VARCHAR2(16 CHAR) DEFAULT '       ', 
	"OCCPCODE" VARCHAR2(4 CHAR), 
	"CLTDOB" NUMBER(8,0) NOT NULL ENABLE, 
	"ZOCCDSC" VARCHAR2(50 CHAR) DEFAULT '                                                  ', 
	"ZWORKPLCE" VARCHAR2(25 CHAR) DEFAULT '                         ', 
	"ZALTRCDE01" VARCHAR2(4 CHAR), 
	"TRANSHIST" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"ZENDCDE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CLNTROLEFLG" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"POLICYSTATUS" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"POLICYTYPE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PRIORTY" VARCHAR2(1 CHAR) NOT NULL ENABLE
   );
--------------------------------------------------------
--  DDL for Table TITDMGCOLRES
--------------------------------------------------------

 Drop table "STAGEDBUSR"."TITDMGCOLRES" ;

  CREATE TABLE "STAGEDBUSR"."TITDMGCOLRES" 
   (	"RECIDXCAMP" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"TRREFNUM" VARCHAR2(8 CHAR), 
	"TFRDATE" NUMBER(8,0), 
	"DSHCDE" VARCHAR2(2 CHAR),
	"PRBILFDT" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGLETTER
--------------------------------------------------------

 Drop table "STAGEDBUSR"."TITDMGLETTER" ;

  CREATE TABLE "STAGEDBUSR"."TITDMGLETTER" 
   (	"RECIDXLETR" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"LETTYPE" VARCHAR2(8 CHAR), 
	"LREQDATE" NUMBER(8,0), 
	"ZDSPCATG" VARCHAR2(1 CHAR), 
	"ZLETVERN" VARCHAR2(3 CHAR), 
	"ZLETDEST" VARCHAR2(1 CHAR), 
	"ZCOMADDR" VARCHAR2(6 CHAR), 
	"ZLETCAT" VARCHAR2(1 CHAR), 
	"ZAPSTMPD" VARCHAR2(1 CHAR), 
	"ZDESPER" VARCHAR2(7 CHAR),
	"ZLETEFDT" NUMBER(8,0),
	"ZLETTRNO" NUMBER(5,0),
	"STAGECLNTNO" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGMBRINDP1
--------------------------------------------------------

 -------------------------------------------------------
 drop table "STAGEDBUSR"."TITDMGMBRINDP1" ;
  
  CREATE TABLE "STAGEDBUSR"."TITDMGMBRINDP1" 
   (	"RECIDXMBINP1" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"CLIENT_CATEGORY" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"REFNUM" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR), 
	"ZINSROLE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"TRANNOMIN" NUMBER(5,0)NOT NULL ENABLE,
    "TRANNONBRN" NUMBER(5,0)NOT NULL ENABLE,
	"TRANNOMAX" NUMBER(5,0)NOT NULL ENABLE, 
	"CLIENTNO" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"OCCDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"GPOLTYPE" VARCHAR2(3 CHAR), 
	"ZENDCDE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ZCMPCODE" VARCHAR2(6 CHAR), 
	"MPOLNUM" VARCHAR2(8 CHAR), 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"ZPOLPERD" NUMBER(3,0), 
	"ZMARGNFLG" VARCHAR2(1 CHAR), 
	"ZDFCNCY" VARCHAR2(1 CHAR), 
	"DOCRCVDT" NUMBER(8,0) NOT NULL ENABLE, 
	"HPROPDTE" NUMBER(8,0) NOT NULL ENABLE, 
	"ZTRXSTAT" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"ZSTATRESN" VARCHAR2(4 CHAR), 
	"ZANNCLDT" NUMBER(10,0), 
	"ZCPNSCDE02" VARCHAR2(5 CHAR), 
	"ZSALECHNL" VARCHAR2(2 CHAR), 
	"ZSOLCTFLG" VARCHAR2(1 CHAR), 
	"CLTRELN" VARCHAR2(4 CHAR), 
	"ZPLANCDE" VARCHAR2(30 CHAR), 
	"CRDTCARD" VARCHAR2(16 CHAR), 
	"PREAUTNO" VARCHAR2(8 CHAR), 
	"BNKACCKEY01" VARCHAR2(20 CHAR), 
	"ZENSPCD01" VARCHAR2(70 CHAR), 
	"ZENSPCD02" VARCHAR2(70 CHAR), 
	"ZCIFCODE" VARCHAR2(15 CHAR), 
	"DTETRM" NUMBER(8,0) NOT NULL ENABLE, 
	"CRDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"CNTTYPIND" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"PTDATE" NUMBER(8,0), 
	"BTDATE" NUMBER(8,0), 
	"STATCODE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"ZWAITPEDT" NUMBER(8,0), 
	"ZCONVINDPOL" VARCHAR2(8 CHAR), 
	"ZPOLTDATE" NUMBER(8,0), 
	"OLDPOLNUM" VARCHAR2(8 CHAR), 
	"ZPGPFRDT" NUMBER(8,0), 
	"ZPGPTODT" NUMBER(8,0), 
	"SINSTNO" NUMBER(3,0), 
	"TREFNUM" VARCHAR2(8 CHAR), 
	"ENDSERCD" VARCHAR2(2 CHAR), 
	"ISSDATE" NUMBER(8,0), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR), 
	"ZRWNLAGE" NUMBER(3,0), 
	"ZNBMNAGE" NUMBER(3,0), 
	"TERMAGE" NUMBER(3,0), 
	"ZBLNKPOL" VARCHAR2(1 CHAR), 
	"PLNCLASS" VARCHAR2(1 CHAR), 
    "ZRNWCNT"  NUMBER(3,0) NOT NULL ENABLE,
    "ZLAPTRX" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"PERIOD_NO" NUMBER(2,0) NOT NULL ENABLE,
    "TOTAL_PERIOD_COUNT" NUMBER(2,0) NOT NULL ENABLE,
    "LAST_TRXS" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	-- CONSTRAINT "CK_1" CHECK ((CLIENT_CATEGORY =0 and TRIm(OCCdate) IS not null) or (CLIENT_CATEGORY =1 and TRIm(OCCdate) IS  null)) ENABLE, 
	 CONSTRAINT "CK_2" CHECK ((CLIENT_CATEGORY =0 and TRIm(MBRNO) IS  null) or (CLIENT_CATEGORY =1 and TRIm(MBRNO) IS not  null)) ENABLE, 
	 CONSTRAINT "CK_3" CHECK ((CLIENT_CATEGORY =0 and TRIm(CLTRELN  ) IS  null) or (CLIENT_CATEGORY =1 and TRIm(CLTRELN  ) IS not  null)) ENABLE, 
	 CONSTRAINT "CK_6" CHECK ((CLIENT_CATEGORY =0 and TRIm(ZPLANCDE    ) IS  null) or (CLIENT_CATEGORY =1 and TRIm(ZPLANCDE   ) IS not  null)) ENABLE
	-- CONSTRAINT "CK_4" CHECK ((CLIENT_CATEGORY =0 and TRIm(STATCODE) IS not null) or (CLIENT_CATEGORY =1 and TRIm(STATCODE) IS  null)) ENABLE
   );


--------------------------------------------------------
--  DDL for Table TITDMGMBRINDP2
--------------------------------------------------------
  drop table "STAGEDBUSR"."TITDMGMBRINDP2";
  CREATE TABLE "STAGEDBUSR"."TITDMGMBRINDP2" 
   (	"RECIDXMBINDP2" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"REFNUM" VARCHAR2(15 CHAR) NOT NULL ENABLE,
	"ZSEQNO" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"DPNTNO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PRODTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"APREM" NUMBER(15,2) NOT NULL ENABLE, 
	"HSUMINSU" NUMBER(13,0) NOT NULL ENABLE, 
	"ZTAXFLG" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"NDRPREM" NUMBER(15,2), 
	"PRODTYP02" VARCHAR2(4 CHAR), 
	"TRANNO" NUMBER(8,0),
    "ZPLANCDE" VARCHAR2(30 CHAR),
	 CONSTRAINT "CK_COV1" CHECK ((NDRPREM > 0 and TRIM(PRODTYP02) is not  null) or (NDRPREM = 0 and TRIM(PRODTYP02) IS null)) ENABLE
	 ) NOCOMPRESS NOLOGGING;
  


--------------------------------------------------------
--  DDL for Table TITDMGAPIRNO
--------------------------------------------------------
  drop table "STAGEDBUSR"."TITDMGAPIRNO";

  CREATE TABLE "STAGEDBUSR"."TITDMGAPIRNO" 
   (	"RECIDXAPIRNO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"ZAPIRNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"FULLKANJINAME" VARCHAR2(120 CHAR) NOT NULL ENABLE,
	"TRANNO" NUMBER(8,0)
   ) NOCOMPRESS NOLOGGING;
  
--------------------------------------------------------
--  DDL for Table TITDMGPOLTRNH
--------------------------------------------------------

 drop table "STAGEDBUSR"."TITDMGPOLTRNH" ;
 
  CREATE TABLE "STAGEDBUSR"."TITDMGPOLTRNH" 
   (
    "RECIDXPHIST" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"ZSEQNO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"EFFDATE" NUMBER(8,0) NOT NULL ENABLE, 
	"CLIENT_CATEGORY" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"CLTRELN" VARCHAR2(2 CHAR), 
	"ZINSROLE" VARCHAR2(1 CHAR), 
	"CLIENTNO" VARCHAR2(10 CHAR), 
	"ZALTREGDAT" NUMBER(8,0) NOT NULL ENABLE, 
	"ZALTRCDE01" VARCHAR2(4 CHAR), 
	"ZINHDSCLM" VARCHAR2(1 CHAR), 
	"ZUWREJFLG" VARCHAR2(1 CHAR), 
	"ZSTOPBPJ" VARCHAR2(1 CHAR), 
	"ZTRXSTAT" VARCHAR2(2 CHAR), 
	"ZSTATRESN" VARCHAR2(4 CHAR), 
	"ZACLSDAT" NUMBER(8,0), 
	"APPRDTE" NUMBER(8,0), 
	"ZPDATATXDTE" NUMBER(8,0), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR), 
	"ZREFUNDAM" NUMBER(17,2), 
	"ZPAYINREQ" VARCHAR2(1 CHAR), 
	"CRDTCARD" VARCHAR2(16 CHAR), 
	"PREAUTNO" VARCHAR2(8 CHAR), 
	"BNKACCKEY01" VARCHAR2(20 CHAR), 
	"ZENSPCD01" VARCHAR2(70 CHAR), 
	"ZENSPCD02" VARCHAR2(70 CHAR), 
	"ZCIFCODE" VARCHAR2(15 CHAR), 
	"ZDDREQNO" VARCHAR2(8 CHAR), 
	"ZWORKPLCE2" VARCHAR2(25 CHAR), 
	"BANKACCDSC01" VARCHAR2(30 CHAR), 
	"BANKKEY" VARCHAR2(10 CHAR), 
	"BNKACTYP01" VARCHAR2(4 CHAR), 
	"CURRTO" NUMBER(8,0), 
	"B1_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B2_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B3_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B4_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B5_ZKNJFULNM" VARCHAR2(120 CHAR), 
	"B1_CLTADDR01" VARCHAR2(60 CHAR), 
	"B2_CLTADDR01" VARCHAR2(60 CHAR), 
	"B3_CLTADDR01" VARCHAR2(60 CHAR), 
	"B4_CLTADDR01" VARCHAR2(60 CHAR), 
	"B5_CLTADDR01" VARCHAR2(60 CHAR), 
	"B1_BNYPC" NUMBER(5,2), 
	"B2_BNYPC" NUMBER(5,2), 
	"B3_BNYPC" NUMBER(5,2), 
	"B4_BNYPC" NUMBER(5,2), 
	"B5_BNYPC" NUMBER(5,2), 
	"B1_BNYRLN" VARCHAR2(8 CHAR), 
	"B2_BNYRLN" VARCHAR2(8 CHAR), 
	"B3_BNYRLN" VARCHAR2(8 CHAR), 
	"B4_BNYRLN" VARCHAR2(8 CHAR), 
	"B5_BNYRLN" VARCHAR2(8 CHAR), 
	"ZSOLCTFLG" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"ZPLANCDE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ZCMPCODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"ZCPNSCDE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"ZSALECHNL" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"TRANCDE" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"TRANNO" NUMBER(5,0),
	"MINTRANNO" NUMBER(5,0),  
	"BTDATE" NUMBER(8,0), 
	"INTREFUND" NUMBER(17,2)
	--CONSTRAINT "CK_PH2" CHECK (TRIM(B1_ZKNJFULNM) is not null OR B2_ZKNJFULNM is not null OR B3_ZKNJFULNM is not null OR B4_ZKNJFULNM is not null or B5_ZKNJFULNM is not null) ENABLE  --#ZJNPG-9739
   ) NOCOMPRESS NOLOGGING;
  
--------------------------------------------------------
--  DDL for Table TITDMGREF1
--------------------------------------------------------
drop table "STAGEDBUSR"."TITDMGREF1"; 

  CREATE TABLE "STAGEDBUSR"."TITDMGREF1" 
   (	"RECIDXREFB1" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"REFNUM" VARCHAR2(15 CHAR), 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"ZREFMTCD" VARCHAR2(3 CHAR), 
	"EFFDATE" NUMBER(8,0), 
	"PRBILFDT" NUMBER(8,0), 
	"PRBILTDT" NUMBER(8,0), 
	"ZPOSBDSM" NUMBER(2,0), 
	"ZPOSBDSY" NUMBER(4,0), 
	"ZALTRCDE01" VARCHAR2(4 CHAR), 
	"ZREFUNDBE" NUMBER(17,2), 
	"ZREFUNDBZ" NUMBER(17,2), 
	"ZENRFDST" VARCHAR2(2 CHAR), 
	"ZZHRFDST" VARCHAR2(2 CHAR), 
	"BANKKEY" VARCHAR2(10 CHAR), 
	"BANKACOUNT" VARCHAR2(20 CHAR), 
	"BANKACCDSC" VARCHAR2(30 CHAR), 
	"BNKACTYP" VARCHAR2(4 CHAR), 
	"ZRQBKRDF" VARCHAR2(1 CHAR), 
	"REQDATE" NUMBER(8,0), 
	"ZCOLFLAG" VARCHAR2(1 CHAR), 
	"PAYDATE" NUMBER(8,0), 
	"RDOCPFX" VARCHAR2(2 CHAR), 
	"RDOCCOY" VARCHAR2(1 CHAR), 
	"RDOCNUM" VARCHAR2(8 CHAR), 
	"ZPDATATXFLG" VARCHAR2(1 CHAR),
	"NRFLAG" VARCHAR2(1 CHAR),
	"TRANNO" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGREF2
--------------------------------------------------------

drop table "STAGEDBUSR"."TITDMGREF2"; 
  CREATE TABLE "STAGEDBUSR"."TITDMGREF2" 
   (	"RECIDXREFB2" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"TRREFNUM" VARCHAR2(15 CHAR), 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"ZREFMTCD" VARCHAR2(3 CHAR), 
	"PRODTYP" VARCHAR2(4 CHAR), 
	"BPREM" NUMBER(15,2), 
	"GAGNTSEL01" VARCHAR2(8 CHAR), 
	"GAGNTSEL02" VARCHAR2(8 CHAR), 
	"GAGNTSEL03" VARCHAR2(8 CHAR), 
	"GAGNTSEL04" VARCHAR2(8 CHAR), 
	"GAGNTSEL05" VARCHAR2(8 CHAR), 
	"CMRATE01" NUMBER(5,2), 
	"CMRATE02" NUMBER(5,2), 
	"CMRATE03" NUMBER(5,2), 
	"CMRATE04" NUMBER(5,2), 
	"CMRATE05" NUMBER(5,2), 
	"COMMN01" NUMBER(17,2), 
	"COMMN02" NUMBER(17,2), 
	"COMMN03" NUMBER(17,2), 
	"COMMN04" NUMBER(17,2), 
	"COMMN05" NUMBER(17,2), 
	"ZAGTGPRM01" NUMBER(17,2), 
	"ZAGTGPRM02" NUMBER(17,2), 
	"ZAGTGPRM03" NUMBER(17,2), 
	"ZAGTGPRM04" NUMBER(17,2), 
	"ZAGTGPRM05" NUMBER(17,2), 
	"ZCOLLFEE01" NUMBER(17,2),
	"MBRNO" CHAR(5 CHAR),
	"DPNTNO" CHAR(2 CHAR),
	"TRANNO" NUMBER(5,0),
	"REFNUMCHUNK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGSALEPLN1
--------------------------------------------------------

drop table "STAGEDBUSR"."TITDMGSALEPLN1"; 

  CREATE TABLE "STAGEDBUSR"."TITDMGSALEPLN1" 
   (	"RECIDXSLPL1" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ZSALPLAN" VARCHAR2(30 CHAR), 
	"ZINSTYPE" VARCHAR2(3 CHAR), 
	"PRODTYP" VARCHAR2(4 CHAR), 
	"SUMINS" NUMBER(17,2), 
	"ZCOVRID" VARCHAR2(1 CHAR), 
	"ZIMBRPLO" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Table TITDMGZCSLPF
--------------------------------------------------------

drop table "STAGEDBUSR"."TITDMGZCSLPF"; 

 CREATE TABLE "STAGEDBUSR"."TITDMGZCSLPF" 
   (	"RECIDXSLPL2" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ZCMPCODE" VARCHAR2(6 CHAR), 
	"OLD_ZSALPLAN" VARCHAR2(30 CHAR),
	"ZSALPLAN" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Index PK_TITDMGAGENTPJ
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGAGENTPJ" ON "STAGEDBUSR"."TITDMGAGENTPJ" ("ZAREFNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;

--------------------------------------------------------
--  DDL for Index PK_TITDMGBILL2
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGBILL2" ON "STAGEDBUSR"."TITDMGBILL2" ("TRREFNUM", "CHDRNUM", "PRODTYP", "MBRNO", "DPNTNO", "PRBILFDT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;



--------------------------------------------------------
--  DDL for Index PK_TITDMGCLTRNHIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGCLTRNHIS" ON "STAGEDBUSR"."TITDMGCLTRNHIS" ("REFNUM", "ZSEQNO", "EFFDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;

--------------------------------------------------------
--  DDL for Index PK_TITDMGLETTER
--------------------------------------------------------

 -- CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGLETTER" ON "STAGEDBUSR"."TITDMGLETTER" ("CHDRNUM", "LETTYPE", "LREQDATE") 
 -- PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 -- STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 -- PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  --BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  --TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Index PK_TITDMGMBRINDP1
--------------------------------------------------------

 CREATE INDEX "STAGEDBUSR"."NOUNI_IDX1" ON "STAGEDBUSR"."TITDMGMBRINDP1" ("REFNUM") ;

  CREATE UNIQUE INDEX "STAGEDBUSR"."UNI_IDX1" ON "STAGEDBUSR"."TITDMGMBRINDP1" ("REFNUM", "ZINSROLE");
--------------------------------------------------------
--  DDL for Index NORMAL_REFNUM
--------------------------------------------------------

  CREATE INDEX "STAGEDBUSR"."NORMAL_REFNUM" ON "STAGEDBUSR"."TITDMGMBRINDP2" ("REFNUM") ;
--------------------------------------------------------
--  DDL for Index PK_TITDMGMBRINDP2
--------------------------------------------------------

	CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGMBRINDP2" ON "STAGEDBUSR"."TITDMGMBRINDP2" ("REFNUM", "ZSEQNO", "MBRNO", "DPNTNO", "PRODTYP");
	CREATE INDEX "STAGEDBUSR"."IDX_TITDMGMBRINDP2" ON "STAGEDBUSR"."TITDMGMBRINDP2" ("REFNUM", "MBRNO", "DPNTNO", "TRANNO");

--------------------------------------------------------
--  DDL for Index PK_TITDMGPOLTRNH
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGPOLTRNH" ON "STAGEDBUSR"."TITDMGPOLTRNH" ("CHDRNUM", "ZSEQNO", "EFFDATE", "MBRNO");

--------------------------------------------------------
--  DDL for Index PK_TITDMGREF1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGREF1" ON "STAGEDBUSR"."TITDMGREF1" ("REFNUM", "CHDRNUM", "ZREFMTCD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
--------------------------------------------------------
--  DDL for Index PK_TITDMGREF2
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGREF2" ON "STAGEDBUSR"."TITDMGREF2" ("TRREFNUM", "CHDRNUM", "ZREFMTCD", "PRODTYP","MBRNO","DPNTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;



--------------------------------------------------------
--  Constraints for Table TITDMGBILL1
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" ADD CONSTRAINT "PK_TITDMGBILL1" PRIMARY KEY ("TRREFNUM", "CHDRNUM", "PRBILFDT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("ENDSERCD" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("ZPOSBDSY" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("ZPOSBDSM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("ZCOLFLAG" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("PREMOUT" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("PRBILTDT" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("PRBILFDT" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("CHDRNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("TRREFNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("NRFLAG" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL1" MODIFY ("TRANNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TITDMGBILL2
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" ADD CONSTRAINT "PK_TITDMGBILL2" PRIMARY KEY ("TRREFNUM", "CHDRNUM", "PRODTYP", "MBRNO", "DPNTNO", "PRBILFDT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("GAGNTSEL01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("BPREM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("PRODTYP" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("TRANNO" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("CHDRNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("TRREFNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("ZCOLLFEE01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("ZAGTGPRM01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("COMMN01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("CMRATE01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("MBRNO" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("DPNTNO" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGBILL2" MODIFY ("PRBILFDT" NOT NULL ENABLE);


--------------------------------------------------------
--  Constraints for Table TITDMGCLTRNHIS
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGCLTRNHIS" ADD CONSTRAINT "PK_TITDMGCLTRNHIS" PRIMARY KEY ("REFNUM", "ZSEQNO", "EFFDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TITDMGCOLRES
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGCOLRES" MODIFY ("PRBILFDT" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGCOLRES" MODIFY ("DSHCDE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGCOLRES" MODIFY ("TFRDATE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGCOLRES" MODIFY ("TRREFNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGCOLRES" MODIFY ("CHDRNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGCOLRES" ADD CONSTRAINT "PK_TITDMGCOLRES" PRIMARY KEY ("CHDRNUM", "TRREFNUM", "TFRDATE", "PRBILFDT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TITDMGLETTER
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("ZAPSTMPD" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("ZLETCAT" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("ZCOMADDR" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("ZLETDEST" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("ZLETVERN" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("ZDSPCATG" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("LREQDATE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("LETTYPE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" MODIFY ("CHDRNUM" NOT NULL ENABLE);
--  ALTER TABLE "STAGEDBUSR"."TITDMGLETTER" ADD CONSTRAINT "PK_TITDMGLETTER" PRIMARY KEY ("CHDRNUM", "LETTYPE", "LREQDATE")
 -- USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE "STAGEDBTS"  ENABLE;


--------------------------------------------------------
--  Constraints for Table TITDMGREF1
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("NRFLAG" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("ZCOLFLAG" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("REQDATE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("ZRQBKRDF" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("ZREFUNDBZ" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("ZREFUNDBE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("PRBILTDT" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("PRBILFDT" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("EFFDATE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("ZREFMTCD" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("CHDRNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" MODIFY ("REFNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF1" ADD CONSTRAINT "PK_TITDMGREF1" PRIMARY KEY ("REFNUM", "CHDRNUM", "ZREFMTCD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TITDMGREF2
--------------------------------------------------------
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("MBRNO" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("DPNTNO" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("ZCOLLFEE01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("ZAGTGPRM01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("COMMN01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("CMRATE01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("GAGNTSEL01" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("BPREM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("PRODTYP" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("ZREFMTCD" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("CHDRNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" MODIFY ("TRREFNUM" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGREF2" ADD CONSTRAINT "PK_TITDMGREF2" PRIMARY KEY ("TRREFNUM", "CHDRNUM", "ZREFMTCD", "PRODTYP","MBRNO","DPNTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TITDMGSALEPLN1
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGSALEPLN1" MODIFY ("ZIMBRPLO" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGSALEPLN1" MODIFY ("ZCOVRID" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGSALEPLN1" MODIFY ("SUMINS" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGSALEPLN1" MODIFY ("PRODTYP" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGSALEPLN1" MODIFY ("ZINSTYPE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGSALEPLN1" MODIFY ("ZSALPLAN" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGSALEPLN1" ADD CONSTRAINT "PK_TITDMGSALEPLN1" PRIMARY KEY ("ZSALPLAN", "ZINSTYPE", "PRODTYP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TITDMGZCSLPF
--------------------------------------------------------

  ALTER TABLE "STAGEDBUSR"."TITDMGZCSLPF" MODIFY ("ZSALPLAN" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGZCSLPF" MODIFY ("ZCMPCODE" NOT NULL ENABLE);
  ALTER TABLE "STAGEDBUSR"."TITDMGZCSLPF" ADD CONSTRAINT "PK_TITDMGSALEPLN2" PRIMARY KEY ("ZCMPCODE", "ZSALPLAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS"  ENABLE;


DROP TABLE  "STAGEDBUSR"."TITDMGENDCTPF";

CREATE TABLE "STAGEDBUSR"."TITDMGENDCTPF"
(
"RECIDXMPGCTPF" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
"CHDRNUM" VARCHAR2(11 CHAR) ,
"ZCRDTYPE" VARCHAR2(1 CHAR) ,
"ZCARDDC" NUMBER(2,0) ,
"ZCNBRFRM" VARCHAR2(16 CHAR) ,
"ZCNBRTO" VARCHAR2(16 CHAR) ,
"ZMSTID" CHAR(15 CHAR) ,
"ZMSTSNME" CHAR(60 CHAR) ,
"ZMSTIDV" VARCHAR2(15 CHAR) ,
"ZMSTSNMEV" VARCHAR2(60 CHAR) ,
---CONSTRAINT "PK_TITDMGENDCTPF" PRIMARY KEY ("CHDRNUM", "ZCRDTYPE","ZCARDDC","ZCNBRFRM","ZCNBRTO","ZMSTID","ZMSTSNME","ZMSTIDV","ZMSTSNMEV")
  CONSTRAINT "PK_TITDMGENDCTPF" PRIMARY KEY ("RECIDXMPGCTPF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

DROP TABLE  "STAGEDBUSR"."TITDMGINSSTPL";

CREATE TABLE "STAGEDBUSR"."TITDMGINSSTPL"
(
"RECIDXMPISTP" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
"CHDRNUM" VARCHAR2(11 CHAR) ,
"PLNSETNUM" NUMBER(1) ,
"ZINSTYPE1" CHAR(3 CHAR) ,
"ZINSTYPE2" CHAR(3 CHAR) ,
"ZINSTYPE3" CHAR(3 CHAR) ,
"ZINSTYPE4" CHAR(3 CHAR) ,
--CONSTRAINT "PK_TITDMGINSSTPL" PRIMARY KEY ("CHDRNUM", "PLNSETNUM")
CONSTRAINT "PK_TITDMGINSSTPL" PRIMARY KEY ("RECIDXMPISTP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


DROP TABLE  "STAGEDBUSR"."TITDMGMASPOL";

CREATE TABLE "STAGEDBUSR"."TITDMGMASPOL"
(
"RECIDXMPMSPOL" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
--- "CHDRNUM" CHAR(11 CHAR) NOT NULL ENABLE,
--- "CNTTYPE" CHAR(3 CHAR) NOT NULL ENABLE,
--- "STATCODE" CHAR(2 CHAR) NOT NULL ENABLE,
--- "ZAGPTNUM" NUMBER(8) NOT NULL ENABLE,
--- "CCDATE" NUMBER(8) NOT NULL ENABLE,
--- "CRDATE" NUMBER(8) NOT NULL ENABLE,
--- "RPTFPST" CHAR(1 CHAR) NOT NULL ENABLE,
--- "ZENDCDE" CHAR(10 CHAR) NOT NULL ENABLE,
--- "RRA2IG" CHAR(40 CHAR) NOT NULL ENABLE,
--- "B8TJIG" CHAR(30 CHAR) NOT NULL ENABLE,
--- "ZBLNKPOL" CHAR(1 CHAR) NOT NULL ENABLE,
--- "B8O9NB" NUMBER(6) ,
--- "B8GPST" CHAR(1) NOT NULL ENABLE,
--- "B8GOST" CHAR(1) NOT NULL ENABLE,
"CHDRNUM" CHAR(11 CHAR),
"CNTTYPE" CHAR(3 CHAR),
"STATCODE" CHAR(2 CHAR),
"ZAGPTNUM" VARCHAR2(8),
"CCDATE" NUMBER(8),
"CRDATE" NUMBER(8),
"RPTFPST" CHAR(1 CHAR),
"ZENDCDE" CHAR(10 CHAR),
"RRA2IG" CHAR(40 CHAR),
"B8TJIG" CHAR(30 CHAR),
"ZBLNKPOL" CHAR(1 CHAR),
"B8O9NB" NUMBER(6) ,
"B8GPST" CHAR(1),
"B8GOST" CHAR(1),
"ZNBALTPR" CHAR(8 CHAR) ,
"CANCELDT" NUMBER(8) ,
"EFFDATE" NUMBER(8) ,
"PNDATE" NUMBER(8) ,
"OCCDATE" NUMBER(8) ,
"INSENDTE" NUMBER(8) ,
"ZPENDDT" NUMBER(8) ,
"ZCCDE" CHAR(15 CHAR) ,
"ZCONSGNM" CHAR(60 CHAR) ,
"ZBLADCD" CHAR(15 CHAR) ,
"CLNTNUM" CHAR(12 CHAR) 
--CONSTRAINT "PK_TITDMGMASPOL" PRIMARY KEY ("CHDRNUM", "CCDATE")
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;





--------------------------------------------------------
--  DDL for Table TITDMGMBRINDP3
--------------------------------------------------------
 DROP  TABLE "STAGEDBUSR"."TITDMGMBRINDP3";
 
 CREATE TABLE "STAGEDBUSR"."TITDMGMBRINDP3" 
   (	"RECIDXMBINDP3" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"OLDPOLNUM" VARCHAR2(10 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 5 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
  CREATE UNIQUE INDEX "STAGEDBUSR"."PK_TITDMGMBRINDP3" ON "STAGEDBUSR"."TITDMGMBRINDP3" ("OLDPOLNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGEDBTS" ;
ALTER TABLE "STAGEDBUSR"."TITDMGMBRINDP3" ADD CONSTRAINT "PK_TITDMGMBRINDP3" PRIMARY KEY ("OLDPOLNUM")
  USING INDEX "STAGEDBUSR"."PK_TITDMGMBRINDP3"  ENABLE;
  




--------------------------------------------------------
--  DDL for Table TITDMGRNWDT1
--------------------------------------------------------
DROP TABLE "STAGEDBUSR"."TITDMGRNWDT1" cascade constraints;

CREATE TABLE "STAGEDBUSR"."TITDMGRNWDT1" 
   (	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"ZRNDTFRM" NUMBER(8,0) NOT NULL ENABLE, 
	"ZRNDTTO" NUMBER(8,0) NOT NULL ENABLE, 
	"ZALTRCDE" VARCHAR2(3 CHAR), 
	"ZRNDTREG" NUMBER(8,0), 
	"ZRNDTAPP" NUMBER(8,0), 
	"ZINSROLE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"STAGECLNTNO" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"ZTERMFLG" VARCHAR2(1 CHAR), 
	"ZSALPLAN" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ZRNDTRCD" VARCHAR2(3 CHAR), 
	"ZINSRNWAGE" NUMBER(3,0), 
	"INPUT_SOURCE_TABLE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "SPK_RNWDT1" PRIMARY KEY ("CHDRNUM", "MBRNO"));

--------------------------------------------------------
--  DDL for Table TITDMGRNWDT2
--------------------------------------------------------

DROP TABLE "STAGEDBUSR"."TITDMGRNWDT2" cascade constraints;

CREATE TABLE "STAGEDBUSR"."TITDMGRNWDT2" 
   (	"CHDRNUM" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"MBRNO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"DPNTNO" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PRODTYP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"SUMINS" NUMBER(17,2) NOT NULL ENABLE, 
	"DPREM" NUMBER(15,2) NOT NULL ENABLE, 
	"ZINSTYPE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"PRODTYP02" VARCHAR2(4 CHAR), 
	"NDR_DPREM" NUMBER(15,2), 
	"INPUT_SOURCE_TABLE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_RNWDT2" PRIMARY KEY ("CHDRNUM", "MBRNO", "DPNTNO", "PRODTYP"));

 CREATE INDEX "STAGEDBUSR"."POLHIST_TRANNO_INDX1" ON "STAGEDBUSR"."TITDMGPOLTRNH" ("CHDRNUM", "ZSEQNO"); --Ticket #ZJNPG-9739
 CREATE INDEX "STAGEDBUSR"."POLHIST_TRANNO_INDX2" ON "STAGEDBUSR"."TITDMGPOLTRNH" ("CHDRNUM", "ZSEQNO", "MBRNO");  --Ticket #ZJNPG-9739
 CREATE INDEX "STAGEDBUSR"."COV_TRANNO_INDX1" ON "STAGEDBUSR"."TITDMGMBRINDP2" ("REFNUM", "ZSEQNO") ; --Ticket #ZJNPG-9739
 CREATE INDEX "STAGEDBUSR"."COV_TRANNO_INDX2" ON "STAGEDBUSR"."TITDMGMBRINDP2" ("REFNUM", "ZSEQNO", "MBRNO");  --Ticket #ZJNPG-9739
 CREATE INDEX "STAGEDBUSR"."APIRNO_TRANNO_INDX1" ON "STAGEDBUSR"."TITDMGAPIRNO" ("CHDRNUM") ;--Ticket #ZJNPG-9739
 
 -------------------------------------------------------------------
--  DDL for Table TITDMGCORADDR
--------------------------------------------------------
DROP TABLE "STAGEDBUSR"."TITDMGCORADDR" cascade constraints;

  CREATE TABLE "STAGEDBUSR"."TITDMGCORADDR" 
   (	"RECCORADR" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"CHDRNUM" VARCHAR2(8 CHAR), 
	"ZKANASNM" VARCHAR2(60 CHAR), 
	"ZKANAGNM" VARCHAR2(60 CHAR), 
	"LSURNAME" VARCHAR2(60 CHAR), 
	"LGIVNAME" VARCHAR2(60 CHAR), 
	"CLTPCODE" VARCHAR2(10 CHAR), 
	"CLTADDR01" VARCHAR2(60 CHAR), 
	"CLTADDR02" VARCHAR2(60 CHAR), 
	"CLTADDR03" VARCHAR2(60 CHAR), 
	"CLTADDR04" VARCHAR2(60 CHAR), 
	"ZKANADDR01" VARCHAR2(60 CHAR), 
	"ZKANADDR02" VARCHAR2(60 CHAR), 
	"ZKANADDR03" VARCHAR2(60 CHAR), 
	"ZKANADDR04" VARCHAR2(60 CHAR), 
	"CLTPHONE01" VARCHAR2(16 CHAR)
	)
	NOCOMPRESS NOLOGGING;
CREATE UNIQUE INDEX "STAGEDBUSR"."TITDMGCORADDR" ON "STAGEDBUSR"."TITDMGCORADDR" ("CHDRNUM") ;
--------------------No Logging :START-----
alter table TITDMGAGENTPJ nologging;
alter table TITDMGAPIRNO nologging;
alter table TITDMGBILL1 nologging;
alter table TITDMGBILL2 nologging;
alter table TITDMGCAMPCDE nologging;
alter table TITDMGCLNTBANK nologging;
alter table TITDMGCLNTCORP nologging;
alter table TITDMGCLNTPRSN nologging;
alter table TITDMGCLTRNHIS nologging;
alter table TITDMGCOLRES nologging;
alter table TITDMGENDCTPF nologging;
alter table TITDMGENDSPCFC nologging;
alter table TITDMGINSSTPL nologging;
alter table TITDMGLETTER nologging;
alter table TITDMGMASPOL nologging;
alter table TITDMGMBRINDP1 nologging;
alter table TITDMGMBRINDP2 nologging;
alter table TITDMGMBRINDP3 nologging;
alter table TITDMGPOLTRNH nologging;
alter table TITDMGREF1 nologging;
alter table TITDMGREF2 nologging;
alter table TITDMGRNWDT1 nologging;
alter table TITDMGRNWDT2 nologging;
alter table TITDMGSALEPLN1 nologging;
alter table TITDMGZCSLPF nologging;
-----No logging :END
-------Init Trans 5 : START -------------
alter table TITDMGAGENTPJ MOVE INITRANS 5;
alter table TITDMGAPIRNO MOVE INITRANS 5;
alter table TITDMGBILL1 MOVE INITRANS 5;
alter table TITDMGBILL2 MOVE INITRANS 5;
alter table TITDMGCAMPCDE MOVE INITRANS 5;
alter table TITDMGCLNTBANK MOVE INITRANS 5;
alter table TITDMGCLNTCORP MOVE INITRANS 5;
alter table TITDMGCLNTPRSN MOVE INITRANS 5;
alter table TITDMGCLTRNHIS MOVE INITRANS 5;
alter table TITDMGCOLRES MOVE INITRANS 5;
alter table TITDMGENDCTPF MOVE INITRANS 5;
alter table TITDMGENDSPCFC MOVE INITRANS 5;
alter table TITDMGINSSTPL MOVE INITRANS 5;
alter table TITDMGLETTER MOVE INITRANS 5;
alter table TITDMGMASPOL MOVE INITRANS 5;
alter table TITDMGMBRINDP1 MOVE INITRANS 5;
alter table TITDMGMBRINDP2 MOVE INITRANS 5;
alter table TITDMGMBRINDP3 MOVE INITRANS 5;
alter table TITDMGPOLTRNH MOVE INITRANS 5;
alter table TITDMGREF1 MOVE INITRANS 5;
alter table TITDMGREF2 MOVE INITRANS 5;
alter table TITDMGRNWDT1 MOVE INITRANS 5;
alter table TITDMGRNWDT2 MOVE INITRANS 5;
alter table TITDMGSALEPLN1 MOVE INITRANS 5;
alter table TITDMGZCSLPF MOVE INITRANS 5;

------Init Trans 5 :END----

----Rebuild:start--
alter index PK1_TITDMGCAMPCDE rebuild;
alter index PK_TITDMGCLNTBANK rebuild;
alter index PK_TITDMGENDCTPF rebuild;
alter index PK_TITDMGINSSTPL rebuild;
alter index NOUNI_IDX1 rebuild;
alter index UNI_IDX1 rebuild;
alter index NORMAL_REFNUM rebuild;
alter index PK_TITDMGMBRINDP2 rebuild;
alter index IDX_TITDMGMBRINDP2 rebuild;
alter index PK_TITDMGPOLTRNH rebuild;
alter index SPK_RNWDT1 rebuild;
alter index PK_RNWDT2 rebuild;
alter index PK_TITDMGAGENTPJ rebuild;
alter index PK_TITDMGBILL1 rebuild;
alter index PK_TITDMGBILL2 rebuild;
alter index PK_TITDMGCLNTCORP rebuild;
--alter index PK_TITDMGCLNTPRSN rebuild;
alter index PK_TITDMGCLTRNHIS rebuild;
alter index PK_TITDMGCOLRES rebuild;
alter index PK_TITDMGMBRINDP3 rebuild;
alter index PK_TITDMGREF1 rebuild;
alter index PK_TITDMGREF2 rebuild;
alter index PK_TITDMGSALEPLN1 rebuild;
alter index PK_TITDMGSALEPLN2 rebuild;
ALTER INDEX "STAGEDBUSR"."POLHIST_TRANNO_INDX1" REBUILD;--Ticket #ZJNPG-9739
ALTER INDEX "STAGEDBUSR"."POLHIST_TRANNO_INDX2" REBUILD; --Ticket #ZJNPG-9739
ALTER INDEX "STAGEDBUSR"."COV_TRANNO_INDX1" REBUILD; --Ticket #ZJNPG-9739
ALTER INDEX "STAGEDBUSR"."COV_TRANNO_INDX2" REBUILD; --Ticket #ZJNPG-9739
ALTER INDEX "STAGEDBUSR"."APIRNO_TRANNO_INDX1" REBUILD; --Ticket #ZJNPG-9739
---Rebuild:end---