--Grant on all the stage tables.
grant ALL on STAGEDBUSR.TITDMGAGENTPJ to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGCLNTBANK to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGCLNTCORP to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGCLNTPRSN to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGCLTRNHIS to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGCAMPCDE to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGLETTER to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGMBRINDP1 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGMBRINDP2 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGMBRINDP3 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGPOLTRNH to Jd1dta;  
grant ALL on STAGEDBUSR.TITDMGSALEPLN1 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGSALEPLN2 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGBILL1 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGBILL2 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGCOLRES to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGREF1 to Jd1dta;   
grant ALL on STAGEDBUSR.TITDMGREF2 to Jd1dta;   


---Special grant 
GRANT CREATE TABLE , CREATE SESSION , INSERT ANY TABLE , CREATE ANY PROCEDURE , CREATE PROCEDURE TO Jd1dta;

