ALTER PROCEDURE BQ9S5_AG01_AGENCY COMPILE;
ALTER PROCEDURE BQ9TL_BL01_COLLRSLT COMPILE ;
ALTER PROCEDURE BQ9RU_CB01_CLTBNK COMPILE;
ALTER PROCEDURE BQ9Q7_CL01_CORPCLT COMPILE;
ALTER PROCEDURE BQ9Q6_CL02_PERCLT COMPILE;
ALTER PROCEDURE BQ9TV_CL02_2_CLNTHIST COMPILE;
ALTER PROCEDURE BQ9S8_CM01_CAMPCD COMPILE;
ALTER PROCEDURE BQ9RF_LT01_LETR COMPILE;
ALTER PROCEDURE BQ9SC_MB01_MBRIND COMPILE;
ALTER PROCEDURE BQ9SF_SP01_SALPLN COMPILE;
ALTER PROCEDURE BQ9UT_MB01_DISHONOR COMPILE;
ALTER PROCEDURE BQ9TK_BL01_BILLHIST COMPILE;
ALTER PROCEDURE BQ9UU_MB01_POLHIST COMPILE;
ALTER PROCEDURE BQ9UX_BL01_REFUNDBL COMPILE;



COMMIT;