create or replace FUNCTION GET_STAGE_TABLE_NAME(bprogram IN VARCHAR2)
  RETURN VARCHAR2 AS
BEGIN
  IF TRIM(bprogram) = 'BQ9Q6' THEN
    RETURN 'TITDMGCLNTPRSN';
  END IF;
  IF TRIM(bprogram) = 'BQ9S8' THEN
    RETURN 'TITDMGCAMPCDE';
  END IF;
  IF TRIM(bprogram) = 'BQ9SC' THEN
    RETURN 'TITDMGMBRINDP1';
  END IF;
  IF TRIM(bprogram) = 'BQ9UT' THEN
    RETURN 'TITDMGMBRINDP3';
  END IF;
  IF TRIM(bprogram) = 'BQ9SF' THEN
    RETURN 'TITDMGSALEPLN1';
  END IF;
  IF TRIM(bprogram) = 'BQ9Q7' THEN
    RETURN 'TITDMGCLNTCORP';
  END IF;
  IF TRIM(bprogram) = 'BQ9TV' THEN
    RETURN 'TITDMGCLTRNHIS';
  END IF;
  IF TRIM(bprogram) = 'BQ9RU' THEN
    RETURN 'TITDMGCLNTBANK';
  END IF;
  IF TRIM(bprogram) = 'BQ9RF' THEN
    RETURN 'TITDMGLETTER';
  END IF;
  IF TRIM(bprogram) = 'BQ9TK' THEN
    RETURN 'TITDMGBILL1';
  END IF;
  IF TRIM(bprogram) = 'BQ9S5' THEN
    RETURN 'TITDMGAGENTPJ';
  END IF;
  IF TRIM(bprogram) = 'BQ9UU' THEN
    RETURN 'TITDMGPOLTRNH';
  END IF;
    IF TRIM(bprogram) = 'BQ9TL' THEN
    RETURN 'TITDMGCOLRES';
  END IF;
  IF TRIM(bprogram) = 'BQ9UX' THEN
    RETURN 'TITDMGREF1';
  END IF;
  RETURN NULL;
END;
/