create or replace FUNCTION GET_PRIOR_PROCESS_NAME(
    rprocess IN VARCHAR2)
  RETURN VARCHAR2
AS
BEGIN
 IF TRIM(rprocess) ='BQ9V0' THEN
  RETURN 'BQ9S5' ;
END IF;
IF TRIM(rprocess) ='BQ9V1' THEN
  RETURN 'BQ9Q7';
END IF;
IF TRIM(rprocess) ='BQ9V2' THEN
  RETURN 'BQ9Q6';
END IF;
IF TRIM(rprocess) ='BQ9V3' THEN
  RETURN 'BQ9TV';
END IF;
IF TRIM(rprocess) ='BQ9V4' THEN
  RETURN 'BQ9RU';
END IF;
IF TRIM(rprocess) ='BQ9V5' THEN
  RETURN 'BQ9SF';
END IF;
IF TRIM(rprocess) ='BQ9V6' THEN
  RETURN 'BQ9S8';
END IF;
IF TRIM(rprocess) ='BQ9V7' THEN
  RETURN 'BQ9SC ';
END IF;
IF TRIM(rprocess) ='BQ9V8' THEN
  RETURN 'BQ9UT';
END IF;
IF TRIM(rprocess) ='BQ9V9' THEN
  RETURN 'BQ9UU';
END IF;
IF TRIM(rprocess) ='BQ9VA' THEN
  RETURN 'BQ9TK';
END IF;
IF TRIM(rprocess) ='BQ9VB' THEN
  RETURN 'BQ9TL ';
END IF;
IF TRIM(rprocess) ='BQ9VC' THEN
  RETURN 'BQ9UX';
END IF;
IF TRIM(rprocess) ='BQ9VD' THEN
  RETURN 'BQ9RF';
END IF;

RETURN NULL;
END;
/