
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAIB','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAIA','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAI8','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAI9','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAID','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAIC','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAIE','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAJL','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAIG','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));
Insert into UTRCPF (USERID,COMPANY,TRANSCD,USRPRF,JOBNM,DATIME) values ('UNDERWR1  ','*','BAIZ','UNDERWR1  ','UNDERWR1  ',to_timestamp(SYSDATE));