OPTIONS (DIRECT=TRUE)
UNRECOVERABLE
LOAD DATA
REPLACE
INTO TABLE STAGEDBUSR.TITPAMMONTRF_BKP
FIELDS TERMINATED BY "," ENCLOSED BY '"'
TRAILING NULLCOLS
(
RECIDXMONTRF,
RECSTATUS   ,
TRANDATE    ,
TFRDATE     ,
CHDRNUM     ,
BANKKEY     ,
BANKACCKEY  ,
BBKACTYP    ,
CBANKKEY    ,
CBANKACKEY  ,
CBBKACTYP   ,
DSHCDE
)
