set pagesize 0 trimspool on linesize 32700 underline off term off feed off

spool &1/TITPAMCAMPAIGN.csv;
select '"'||RECIDXCAMP||'","'||CREDITCARDNO||'","'||ACCHOLDERNAME_COLLECT||'","'||BK_ACC_NO_PAYM||'","'||ACCHOLDERNAME_PAYM||'","'||SURNAMEKANA||'","'||GIVENNAMEKANA||'","'||SURNAMEKANJI||'","'||GIVENNAMEKANJI||'","'||ADDRESSINKANA_1||'","'||ADDRESSINKANA_2||'","'||ADDRESSINKANA_3||'","'||ADDRESSINKANA_4||'","'||ADDRESSINKANJI_1||'","'||ADDRESSINKANJI_2||'","'||ADDRESSINKANJI_3||'","'||ADDRESSINKANJI_4||'","'||SURNAMEGUARDIANKANJI||'","'||GIVENNAMEGUARDIANKANJI||'","'||SURNAMEGUARDIANKANA||'","'||GIVENNAMEGUARDIANKANA||'","'||POSTALCODEGUARDIAN||'","'||ADDRGUARDIANKANA_1||'","'||ADDRGUARDIANKANA_2||'","'||ADDRGUARDIANKANA_3||'","'||ADDRGUARDIANKANA_4||'","'||ADDRGUARDIANKANJI_1||'","'||ADDRGUARDIANKANJI_2||'","'||ADDRGUARDIANKANJI_3||'","'||ADDRGUARDIANKANJI_4||'","'||TELNOGUARDIAN||'"' from STAGEDBUSR.TITPAMCAMPAIGN;
spool off;
