OPTIONS (DIRECT=TRUE)
UNRECOVERABLE
LOAD DATA
REPLACE
INTO TABLE STAGEDBUSR.TOTPAMRFDPREM_BKP
FIELDS TERMINATED BY "," ENCLOSED BY '"'
TRAILING NULLCOLS
(
RECIDXRFDPRM,
RECSTATUS   ,
CHDRNUM     ,
PAYAMT      ,
EFFDATE     ,
BANKKEY     ,
BANKACCKEY  ,
BANKACCDSC  ,
BBKACTYP    ,
CURRFROMX   ,
ENDREASN    ,
IGTRANNO
)
